### ISSUE TITLE
C++14 dialect unavailable in Xcode 5.1.1 / OS X 10.8.5

### ISSUE THREAD

**Issue by pizthewiz** [cinder/Cinder#1005]
Follow up to #919, annoyingly it appears as though Xcode 5.1.1 does *not* support the c++14 dialect, sorry for the bad guidance.

<img src="http://i.imgur.com/Oc0cWMs.png">

**Comment by richardeakin** [comment]
Hm.  Well these are our options as I see it:

* a) ship with samples / templates set to C++14 so you get features like make_unique() and lambdas with auto out of the box, even if we don't use them in cinder core codebase for the time being.  If we were to do this, I guess it would mean we'd have to instruct Xcode 5 users to change the value to C++11 if they need to stay on that IDE.
* b) declare minimum Xcode version to be 6.
* c) revert the commit making the jump to C++14.

I'm okay with any of the above, although I do like the idea of shipping with the latest C++ standard enabled by default.

**Comment by pizthewiz** [comment]
Good news, Clang 3.4 included with Xcode 5.1 _does_ support C++14 but [it turns out](http://stackoverflow.com/a/23018783) one must use an earlier name of the dialect `c++1y` and I quickly tested it with the BasicApp sample in a VM running OS X 10.9.5 with Xcode 5.1.1.

For compilers (Xcode 6+) that do support the `c++14` dialect, I wonder if treats `c++1y` as `c++14`?

**Comment by pizthewiz** [comment]
Would it make sense to externalize the Xcode project settings into an `xcconfig` file, perhaps only for the samples?

**Comment by richardeakin** [comment]
We discussed just reverting the bump to C++14 until next dev cycle, at which point we can also bump the required xcode version. I think this is good for now, seeing as how we're trying to stir the waters as little as possible until 0.9.0 is shipped.

xcconfigs... well that's a separate yet debatable topic, going to leave it at that. :)

**Comment by pizthewiz** [comment]
Sounds like a good plan for 0.9.0.
