### ISSUE TITLE
Multiplication order of gl::rotate and Matrix44<T>::createRotation

### ISSUE THREAD

**Issue by tek-nishi** [cinder/Cinder#1009]
Cinder 0.8.6 is great framework!!

But, I have a worrisome thing.

void rotate( const Vec3f &xyz )
{
	glRotatef( xyz.x, 1.0f, 0.0f, 0.0f );
	glRotatef( xyz.y, 0.0f, 1.0f, 0.0f );
	glRotatef( xyz.z, 0.0f, 0.0f, 1.0f );
}

Matrix44<T> Matrix44<T>::createRotation( const Vec3<T> &eulerRadians )
{
	// The ordering for this is XYZ. In OpenGL, the ordering
	// is the same, but the operations needs to happen in
	// reverse: 
	//
	//     glRotatef( eulerRadians.z, 0.0f, 0.0f 1.0f );
	//     glRotatef( eulerRadians.y, 0.0f, 1.0f 0.0f );
	//     glRotatef( eulerRadians.x, 1.0f, 0.0f 0.0f );
	//

}

The order of the multiplication of 2 functions is reverse.

Why??

Thank you.

**Comment by andrewfb** [comment]
Hi - we have since moved to [glm](http://glm.g-truc.net/0.9.6/index.html) partially to address inconsistencies like this. If you are able to move your project to the `master` branch I'd recommend that as we're working toward shipping 0.9.0.

**Comment by tek-nishi** [comment]
Thank you.
I try to move my project to the master at the near future.
