### ISSUE TITLE
Corrupted Surface data

### ISSUE THREAD

**Issue by araid** [cinder/Cinder#1011]
Creating a Surface8uRef from a buffer and making a Texture2dRef from it results in:
- A correct texture if they were both created in the same function:
<img width="712" alt="screen shot 2015-07-05 at 5 56 20 pm" src="https://cloud.githubusercontent.com/assets/237888/8513569/3a97f54e-233f-11e5-81cc-bacd8385f860.png">

- Random black pixels if the SurfaceRef was returned from a different function:
<img width="712" alt="screen shot 2015-07-05 at 5 54 52 pm" src="https://cloud.githubusercontent.com/assets/237888/8513570/408bc0f2-233f-11e5-8f64-55d9145dc7c3.png">
<img width="712" alt="screen shot 2015-07-05 at 5 55 12 pm" src="https://cloud.githubusercontent.com/assets/237888/8513571/40948796-233f-11e5-9a6a-40ad3d1efc1e.png">

You can try it with this test app: https://gist.github.com/araid/c83ecc0a59e75ac963bf

**Comment by andrewfb** [comment]
This constructor [does not assume ownership](https://github.com/cinder/Cinder/blob/master/include/cinder/Surface.h#L116) of the memory. When the local variable `buffer` goes out of scope the resulting Surface8uRef is still pointing at this memory. There are a couple of ways to solve this. One would be to construct a temporary Surface8u similarly to how you are now, and then call `copyFrom()` on a normally constructed Surface8u with this temporary surface as the input.

**Comment by araid** [comment]
My bad, I should have read the comment. I figured that, because it was a shared pointer, I wasn't freeing the data, but I didn't think about the original vector.

I can probably just store the buffer as a class member. I'm not quite sure what you mean with "normally constructed" Surface8u.

**Comment by andrewfb** [comment]
One approach would be something like this:
```
Surface8u temp( buffer.data(), width, 1, width * 4, SurfaceChannelOrder::RGBA );
Surface8u result( width, 1, true ); // does own its memory
result.copyFrom( temp, temp.getBounds() );
```

**Comment by araid** [comment]
Oh, I see. Thanks for the clarification!
