### ISSUE TITLE
Early EOF

### ISSUE THREAD

**Issue by Ghirigoro** [cinder/Cinder#1021]
I'm trying to clone the master repository and git clone keeps failing with a "fatal: early EOF, fatal: index-pack failed" error. I've tried increasing the amount of memory available to git but it still fails. I've never had this problem cloning the cinder repository before. Is there something about the recent changes that is causing this? Is anyone else experiencing this?

**Comment by pizthewiz** [comment]
Very bizarre, I just cloned the repo in a VM about an hour ago and didn't have any trouble - what version of git are you using? How far through the clone does it get before dying?

**Comment by Ghirigoro** [comment]
I used git version 2.3.2 (Apple Git-55) and 2.2.1. The first one is the one that comes with OSX 10.10 and the second one is the one that's included in SourceTree for OSX. It seems to fail far into the process but looking at the log I can't say at which point exactly. This happened to me yesterday as well.

**Comment by paulhoux** [comment]
No problems here, either. Maybe you can try the suggestions in this post? :
http://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed

**Comment by Ghirigoro** [comment]
Thanks Paul. I tried upping the memory for Git like they describe in that SO post but I haven't tried to clone in individual "tiers". I'll try that but since no one else is experiencing the issue I'm wondering if the issue is related to the fact that I'm trying to do this on relatively slow hotel connection. I know very little about Git, but maybe there's a very large file that is timing out internally and producing the error. In any case it seems to be a Git issue and not a Cinder issue.
