### ISSUE TITLE
Git setup document uses non-existent branch

### ISSUE THREAD

**Issue by Ghirigoro** [cinder/Cinder#1022]
The git setup document mentions that to clone the repository you should clone the dev branch (i.e. git clone -b dev --recursive git://github.com/cinder/Cinder.git cinder_master ) but that branch no longer exists

**Comment by pizthewiz** [comment]
The document is more current in the repo:
  https://github.com/cinder/Cinder/blob/master/docs/welcome/GitSetup.html

The team might be waiting for the 0.9.0 release until deploying to libcinder.org.
