### ISSUE TITLE
Make GlslProg 'Unknown attribute' a warning instead of error.

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1028]
I think some of these were downgraded to warnings (unknown uniforms I believe), though [here](https://github.com/cinder/Cinder/blob/master/src/cinder/gl/GlslProg.cpp#L602) is a case where I'm seeing an error message because the attribute is not in use and has been optimized out.

**Comment by richardeakin** [comment]
Should also do the same for uniform block (are there others that should be warnings instead of errors?).

**Comment by num3ric** [comment]
Regarding the attribute error, I would agree with the warning conversion. I also think the log message should be at least *"unknown/unused attribute"*.

It took me a while to remember about this behavior (http://stackoverflow.com/a/7203402/570738)...

**Comment by ryanbartley** [comment]
I'm fine with downgrading it to warning. I think that's totally reasonable. My thinking, when writing the error, was that if you've written code that expects it and it doesn't exist something is wrong, but I have run up against it myself and it's obviously not a breaking problem most of the time. I can update and push a commit.
