### ISSUE TITLE
.colors() not working on ci::geom::RoundedRect

### ISSUE THREAD

**Issue by dmelancon** [cinder/Cinder#1045]
.colors() doesn't seem to be doing anything. 
See sample here: https://gist.github.com/dmelancon/7c67ede247383a596724

**Comment by ryanbartley** [comment]
What do you see? It isn't red?

**Comment by dmelancon** [comment]
The Rect is red, the RoundedRect is white.

**Comment by ryanbartley** [comment]
I see what's going on. I'll push a fix momentarily.
