### ISSUE TITLE
PickingFbo sample broken

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#1049]
I think it does not work anymore, because blending is enabled by default, which interferes with the picking index.

**Comment by gaborpapp** [comment]
`gl::ScopedBlend blend( false );` in `PickingFBOApp::renderScene` fixes it, although I'm not sure if this is the best solution, because picking would work with blending enabled if the picking index did not use alpha.

**Comment by paulhoux** [comment]
I'll have a look, Gabor. Should have replied earlier. Busy busy :)

**Comment by andrewfb** [comment]
Thanks - Paul fixed it with the above.

**Comment by gaborpapp** [comment]
Thanks!
