### ISSUE TITLE
Tutorial should be updated for 0.9.0

### ISSUE THREAD

**Issue by ulyssesp** [cinder/Cinder#1053]
There are a number of changes between 0.8.6 and 0.9.0 including the use of glm vectors and `gl::Batch` instead of the gl utility methods.

I'm going through the tutorial right now using `master`, so if it's helpful I'm happy to update the tutorial docs.

**Comment by richardeakin** [comment]
The tutorial (in 'tour' folder) was removed from the master branch because it was so far out of date, including the drawing techniques that it used, that it would need to rewrite. So I think what you're editing locally should be untracked files.

**Comment by ulyssesp** [comment]
Ahh the doxygen files aren't edited directly? Taking a look at those I see what you mean - they haven't been edited in 4 years! 

Is this something that still needs to be done prior to release 0.9.0 even if it's outside the repository?
