### ISSUE TITLE
MotionBlurVelocityBuffer sample is no longer working

### ISSUE THREAD

**Issue by BanTheRewind** [cinder/Cinder#1055]
https://github.com/cinder/Cinder/tree/master/samples/_opengl/MotionBlurVelocityBuffer

I can't get this sample to run correctly on OSX or Windows anymore. It runs, but no blur occurs. On OSX, the first velocity  buffer is just added and never cleared. The second buffer is never used.

Thoughts, @sansumbrella ?

**Comment by gaborpapp** [comment]
What about disabling blending in `MotionBlurVelocityBufferApp::draw()`?

**Comment by BanTheRewind** [comment]
Yeah, tried turning off and changing blend modes. No luck. Haven't had time to dig in. Would like to get this one working again as it's a nice techni
