### ISSUE TITLE
Icosphere UV coordinates

### ISSUE THREAD

**Issue by araid** [cinder/Cinder#1083]
I'm trying to map an ``Icosphere`` with a texture of the earth, and noticed that the poles are too large and the texture appears stretched down. It also needs to be loaded top-down, as opposed to ``Sphere``.

Would it be possible to have both of them act the same way when it comes to UV coordinates, so they are easily replaceable?

This is from the Arcball sample. Sphere:
![screen shot 2015-08-26 at 12 39 03 pm](https://cloud.githubusercontent.com/assets/237888/9499861/fba677aa-4bef-11e5-910d-5565e8d2614e.png)

Icosphere:
<img width="752" alt="screen shot 2015-08-26 at 12 39 41 pm" src="https://cloud.githubusercontent.com/assets/237888/9499860/fba405a6-4bef-11e5-950d-7541deec10b7.png">

Loading the geometry sample you can see the differences in UV coords, plus a strange artifact on the side when using Texturing mode: sampler. 

![screen shot 2015-08-26 at 12 32 11 pm](https://cloud.githubusercontent.com/assets/237888/9499898/28905628-4bf0-11e5-8571-f2c073aae559.png)
![screen shot 2015-08-26 at 12 32 16 pm](https://cloud.githubusercontent.com/assets/237888/9499897/289051b4-4bf0-11e5-9fa8-da687df57a9b.png)
![screen shot 2015-08-26 at 12 32 00 pm](https://cloud.githubusercontent.com/assets/237888/9499899/2894b790-4bf0-11e5-9bb4-f53edb637573.png)

thanks!

**Comment by num3ric** [comment]
Hey Adria,

Here's a trick (with Paul taught me) that you can use to get perfect spherical texture mapping before these issues are fixed, if they can be. Use the vertex normal (or position if it is centered at origin) directly as a texcoord:

https://github.com/num3ric/Cinder-OculusRift/blob/master/samples/SphericalStereo/assets/stereo.frag#L16

**Comment by num3ric** [comment]
In fact, it should be possible to use the same method offline to uniformly bake the correct texcoords into these geoms, no?

**Comment by paulhoux** [comment]
Hi Adria, thanks for reporting this. While calculating UV-coordinates for an icosphere is far from straightforward (see: http://mft-dev.dk/uv-mapping-sphere/ ), I agree that it should produce similar results to the sphere. I'll look into it.

@num3ric : calculating the uv-coordinates in the **fragment** shader indeed works well, probably even better than using the supplied uv-coordinates. Just make sure to do it in the fragment shader, not the vertex shader. It works because it allows you to jump from x=0.999 to x=0.000 within the polygon, avoiding any seams. Unfortunately, it's not possible to bake this into the geometry.

**Comment by araid** [comment]
Thanks Paul!

2015-08-31 13:20 GMT-04:00 Paul Houx <notifications@github.com>:

**Comment by paulhoux** [comment]
Hi Adria, this should now be fixed.

**Comment by paulhoux** [comment]
Side note @num3ric  : I've used a different algorithm to calculate the uv's, which is probably faster than the method you're using in your shader, Eric:
```
const float kOneOverPi = 1.0 / 3.14159265;
float u = 0.5 - 0.5 * atan( N.x, -N.z ) * kOneOverPi;
float v = 1.0 - acos( N.y ) * kOneOverPi;
```

**Comment by araid** [comment]
Nice! The UV coordinates look exactly like the Sphere now, but it looks like the zipper from the last image is still there?

**Comment by paulhoux** [comment]
Zipper should be gone, too. I fixed that in a separate commit. The texture in the Geometry sample was not set to repeat, which is required for the Icosphere UV-mapping. If you still see the zipper in your own code, make sure to also set texture wrapping to GL_REPEAT.

**Comment by araid** [comment]
Thanks for the tip. The updated Icosphere works great now.

**Comment by jjxtra** [comment]
The fragment shader works great except for the 6 triangles at each pole for the ico sphere
