### ISSUE TITLE
gl::enableAlphaBlending( bool ) is inconsistent

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1093]
[This method](https://github.com/cinder/Cinder/blob/5cc0ce0cae1a7d412efd6fbcdeb1601bdbb9d600/include/cinder/gl/wrapper.h#L120).

After making the changes in #629.  Seems like we should make that bool enable or disable alpha blending, and add different methods for premultiplied alpha blending.

**Comment by paulhoux** [comment]
Absolutely. Must be an oversight.

**Comment by num3ric** [comment]
Agreed.

**Comment by andrewfb** [comment]
This is subtler than it seems I think, in ways that parallel the depth naming questions. Similar to depth test (but not to be confused with alpha test), there's a piece of boolean state GL_BLEND, and then a separate blending function. The average user probably just thinks of alpha blending as on or off, and is not concerned with this. They're definitely not generally thinking in terms of premult vs. unpremult. I think that what would be the best combination of "correct" and simple is this:
 * `gl::enableBlending( bool enable )` - this only affects the global blending state but does not affect the function
 * `gl::enableAlphaBlending( bool enable )` - enables blending when true, and sets blend func to unpremult alpha. Disables blending when false.
 * `gl::enableAlphaBlendingPremult()` - enables blending and sets blend func to premult alpha.
 * `gl::enableAdditiveBlending()` - enables blending and sets blend func to additive.

**Comment by richardeakin** [comment]
I wanted to note that the functions @andrewfb proposes nearly map the same as the `ScopedBlend*` versions ([here](https://github.com/cinder/Cinder/blob/e58c8cce028cdb72591496d237b7c94b034d717f/include/cinder/gl/scoped.h#L79-L108)). Is it worth making the names and arguments match? In the scoped variants, we went with the Alpha / Additive word as appended to the base `ScopedBlend`, it works well in practice although I can't say I prefer one over the other (just that I think it is good to use consistent method names).

**Comment by andrewfb** [comment]
Addressed by #1123
