### ISSUE TITLE
settings->setDisplay(DisplayRef display) has no effect on MSW

### ISSUE THREAD

**Issue by indefinit** [cinder/Cinder#1111]
Testing on Windows 8.1 via Bootcamp.  MBP with 2 external displays connected via DisplayPort.  Code for issue repro:
```
#include "cinder/app/App.h"
#include "cinder/app/RendererGl.h"
#include "cinder/gl/gl.h"

using namespace ci;
using namespace ci::app;
using namespace std;

class WinMultiDisplayTestApp : public App {
  public:
	void draw() override;
};
void WinMultiDisplayTestApp::draw()
{
	gl::clear( Color( 0, 0, 0 ) ); 
}
CINDER_APP(WinMultiDisplayTestApp, RendererGl, [&](App::Settings *settings){
	vector<DisplayRef> displays = Display::getDisplays();
	if (displays.size() > 1) {
		settings->setDisplay(displays[1]);
	}
})
```
Above code works as expected in Mac OSX (default window constructed on 2nd display) but on MSW no difference between displays[0], 1, 2, etc.

**Comment by indefinit** [comment]
Hi @andrewfb, Thanks for this fix, however I noticed now that calls to settings->setWindowPos(x,y) do not reference the per display origins.  Here's my forum post for more context: https://forum.libcinder.org/topic/multiple-displays-support-on-windows 

I know this is slightly different than the original topic of this issues thread, so should I go ahead and create a new issue? Or is this a known limitation of MSW in general?  Thanks!

**Comment by paulhoux** [comment]
Hi, see b140169aed68bcfa64e07 for a fix to ```settings->setWindowPos()```
