### ISSUE TITLE
Patch boost::filesystem to allow linking on < OS X 10.10 and iOS < 8

### ISSUE THREAD

**Issue by pizthewiz** [cinder/Cinder#1116]
Sadly it appears as though `boost::filesystem` shipped broken for OS X < 10.10 and iOS < 8, as it attempts to use the symbol `fchmodat` that wasn't made available until then. This has been fixed in 1.60 but we will need to patch 1.58 to allow linking.

[Boost #10591](https://svn.boost.org/trac/boost/ticket/10591) has the details and the [patch](https://svn.boost.org/trac/boost/attachment/ticket/10591/boost-fs-fchmodat-darwin.patch) is pretty small. I've locally grabbed and built `boost::filesystem` with the patch applied in an OS X 10.8.5 VM and it all seems sorted.

**Comment by andrewfb** [comment]
Addressed by #1126
