### ISSUE TITLE
MovieWriter.cpp Compilation Issue with VS2015

### ISSUE THREAD

**Issue by RomSteady** [cinder/Cinder#1118]
If you attempt to compile Cinder 0.9.0 from commit b140169aed68bcfa64e076172bd744e0d987add0 using Visual Studio 2015, you are blocked by a single error in MovieWriter.cpp, line 399:

    mMultiPassFrameCache = readWriteFileStream( fs::unique_path( tempDir / ( "multipass_%%%%-%%%%-%%%%-%%%%" ) ) );

It doesn't appear that the STL in VS2015 implements std::tr2::sys::unique_path.  The errors you get are:

    error C2039: 'unique_path': is not a member of 'std::tr2::sys'
    error C3861: 'unique_path': identifier not found

**Comment by andrewfb** [comment]
Thanks for this - should be fixed by 12850f0. MS seems to believe unique_path is implemented according to their docs, but obviously it's not there in practice.

**Comment by RomSteady** [comment]
Verified fixed in Debug, Debug_ANGLE, Release, Release_ANGLE builds.  

VS2015 able to compile 12850f0 without errors.
