### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [cinder/Cinder#112]
I have looked at a few source files for your current software. I have noticed that a few checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [realloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/realloc.html "memory reallocator") ⇒ [Buffer::resize](https://github.com/cinder/Cinder/blob/bb12d03d49f830cca68df4c1e9684fbbb59f6e81/src/cinder/Buffer.cpp#L67)
- [OpenClipboard](http://msdn.microsoft.com/en-us/library/windows/desktop/ms649048.aspx "Opens the clipboard for examination") ⇒ [clipboardContainsFormat](https://github.com/cinder/Cinder/blob/89c2112c81318d80ab712525ea5a75e11d93042f/src/cinder/Clipboard.cpp#L55)

**Comment by andrewfb** [comment]
It's not clear how we'd handle a realloc() failure in the Buffer::resize() case so I'm leaving that alone for now. However I fixed the OpenClipboard error testing: 162fa11f2b86d8b6d01d2851d042e3f1c55d10e7
