### ISSUE TITLE
Where to put code examples for documentation?

### ISSUE THREAD

**Issue by WesleyYue** [cinder/Cinder#1124]
I am not extremely experienced with C++ and was trying to figure out how to use the option chaining with the InterfaceGL ```addParam()``` instead of the optionsStr way. I figured it out and was looking to add some examples on how to use it in the documentation but I'm not really sure where I can do that. I know the doxygen convention is to put example code in the ```EXAMPLE_PATH``` defined in the doxyfile but it seems that path is undefined. Where should I add code examples to the documentation?

For now and for reference in case somebody looking for the same thing came upon this issue, an example of using the new ```addParam()``` is:

```
mParams -> addParam<float>("Angle 1", &mAngle1).min(1.0f).max(50.0f).step(1.0f);
```

where ```mAngle1``` is a float you want to change through the interface and ```mParams``` is the instance created by ```params::InterfaceGl::create()``` and ```max()``` ```min()``` are options. Full list of options can be found here: http://anttweakbar.sourceforge.net/doc/tools:anttweakbar:varparamsyntax

**Comment by lucasvickers** [comment]
There are two ways to add example code.  The first is via a sample application in the [samples](https://github.com/cinder/Cinder/tree/master/samples/) folder.  The second is via a guide in the new [docs system](https://forum.libcinder.org/#Topic/23286000002431027).

With that said, I think your example is covered in the [ParamsBasic](https://github.com/cinder/Cinder/blob/master/samples/ParamsBasic/src/ParamsBasicApp.cpp#L63) example.

**Comment by WesleyYue** [comment]
Ah I see; wish I'd found that folder earlier.

**Comment by lucasvickers** [comment]
The new documentation (released soon) should probably help you out.  Sorry you didn't find the examples earlier!
