### ISSUE TITLE
Improve implementation of constructors

### ISSUE THREAD

**Issue by elfring** [cinder/Cinder#113]
I have noticed that some assignments are used in the constructor bodies.

Examples:
- [FontManager](https://github.com/cinder/Cinder/blob/0f58230c22034daa1f93abe8949acf15da9ee578/src/cinder/Font.cpp#L95)
- [DataSourceBuffer](https://github.com/cinder/Cinder/blob/f9d347af1b34db82e19059d1f4ab29cad7c898b6/src/cinder/DataSource.cpp#L126)

The recommended way for performing efficient construction is to use [the initialisation list](http://dietmar-kuehl.de/mirror/c++-faq/ctors.html#faq-10.6 "Should my constructors use 'initialization lists' or 'assignment'?").

**Comment by andrewfb** [comment]
We generally do use initialization lists in cases where it affects performance. In the DataSourceBuffer example, `mBuffer` is a member of the parent and can't be init'd with an initialization list. However we'll keep an eye out for this.
