### ISSUE TITLE
Where is v0.9.0?

### ISSUE THREAD

**Issue by WesleyYue** [cinder/Cinder#1135]
Where exactly can I get the v0.9.0 release? Is this repo up to date? I was checking out the new website but the link for the v0.9.0 release is dead (https://libcinder.org/docs/release/0.9.0/ and https://libcinder.org/download/) and there doesn't seem to be a v0.9.0 release on this repo yet.

Also, since the website has been updated (love the new layout and design btw), all the documentation for the previous releases seem to have disappeared (https://libcinder.org/docs/v0.8.6, for example). There are also tons of dead links scattered in the guides. I was looking into making a pull request on the guides to see if I can fix some of the dead links but it doesn't look like the html files for the guides are the ones that are live on the website either.

**Comment by gaborpapp** [comment]
v0.9.0 is about to be released. It is the git master branch.

**Comment by andrewfb** [comment]
Yes sorry - please bear with us as we redo the site and release a new version simultaneously. To work from 0.9.0 (out very shortly) just work with the github `master` branch.

**Comment by WesleyYue** [comment]
Ok, cool. Will the documentation for the older releases be restored? It'd be quite a shame to have them all 404 as there are lots of backlinks to them from forums an google. Perhaps you could add a banner at the top to tell users that a newer version is available?

**Comment by pauljurczak** [comment]
The [Download Page](https://libcinder.org/download/) link is broken. Maybe it should be replaced by link to [github releases](https://github.com/cinder/Cinder/releases/tag/v0.9.0)?

**Comment by pizthewiz** [comment]
I think the GitHub Releases has source archives while the download page has binary releases.

**Comment by pauljurczak** [comment]
I see. The URL is wrong: "https://libcinder.org/download/" should be "https://libcinder.org/download".

**Comment by pizthewiz** [comment]
Indeed - is there somewhere on the new site that is still pointing to the old download page URL?

**Comment by pauljurczak** [comment]
[Windows Setup](https://libcinder.org/docs/guides/windows-setup/index.html) does.

**Comment by pizthewiz** [comment]
Good catch, the download links should have been fixed in PR #1183, but I think that PR didn't get merged into the release_v0.9.0 branch / deployed to the site?

**Comment by mhintz** [comment]
This issue seems like it was fixed? Propose to close
