### ISSUE TITLE
Docs html processor appears to change values inside <code><pre>

### ISSUE THREAD

**Issue by lucasvickers** [cinder/Cinder#1139]
I'm working on writing a logging guide, and in a block of example code, found [here](https://github.com/lucasvickers/Cinder/blob/loggingDocs/docs/htmlsrc/guides/logging/index.html#L123-L124).

I have a code example that looks like this in html
```
<pre><code class="language-cpp">// gets the active LoggerSystem and sets the minimum level to LEVEL_ERROR
log::logManager::getLoggers<LoggerSystem>()[0].setLoggingLevel(log::LEVEL_ERROR);</code></pre>
```
In the output, it appears to make the first ```<LoggerSystem>``` lowercase, and also auto adds ```</loggersystem>``` to the end.  See image below.

![screen shot 2015-09-30 at 10 24 29 pm](https://cloud.githubusercontent.com/assets/1099950/10211597/d970a14e-67c2-11e5-9e90-c07410f08872.png)

Please let me know what you find.

**Comment by paulhoux** [comment]
You'll probably have to escape those characters (use &lt; and &gt;), text within a block code is still translated by the HTML parser as far as I know.

**Comment by gregkepler** [comment]
I'm not sure if it's the preprocessor "fixing" the open tag or prism doing it. I'll look into. Regardless, it may best to escape your < and > characters as Paul suggested to ensure the correct output.

If it's on the pythons script end, I'll fix and let you know.

**Comment by lucasvickers** [comment]
Thanks guys.  I'll move forward w/ escaping it.  Will be curious to hear what you find.

**Comment by lucasvickers** [comment]
HTML does process ```<``` inside of ```<pre>``` tags.  I assumed it didn't.
Sorry to waste your time on this!
