### ISSUE TITLE
Render broken after commit 5af6fe35..

### ISSUE THREAD

**Issue by MattijsKneppers** [cinder/Cinder#1142]
Hi, 

It looks like after pulling commit 5af6fe35fcddbdacd680729988f24ed68ef7ab60, the output of an application I am building changed from [this](http://showsync.info/before.mov) to [this](http://showsync.info/after.mov) (see the linked mov files).

I guess something is broken, or maybe not backwards compatible. I will try to isolate what exactly causes the issue.

Best,
Mattijs

**Comment by ryanbartley** [comment]
Could [this](https://forum.libcinder.org/#Topic/23286000002466019) be the cause?

**Comment by MattijsKneppers** [comment]
Aah yup. That could very well be the case, thanks.

**Comment by richardeakin** [comment]
Closing, let us know if you couldn't resolve the problem.

**Comment by MattijsKneppers** [comment]
Ah yes, the problem was resolved by consistently using the same wrappers for setting blending modes throughout the application.

I did notice though that the various ways of setting blend modes (wrappers at different levels) don't play nice together. When I have more time I will try to isolate and post a new issue.
