### ISSUE TITLE
TinderBox: Windows Screensaver projects don't load in vc2013

### ISSUE THREAD

**Issue by paulhoux** [cinder/Cinder#1146]
Reason is the specified target extension (```.sCr```) generates an incorrect tag in the ```.vcxproj``` file:

Wrong:
```<TargetExt Condition="Debug|Win32">.sCr</TargetExt>```
```<TargetExt Condition="Release|Win32">.sCr</TargetExt>```

Correct:
```<TargetExt Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">.sCr</TargetExt>```
```<TargetExt Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">.sCr</TargetExt>```

**Comment by andrewfb** [comment]
This has not been reflected in TinderBox binaries yet, but should fixed by [this commit](https://github.com/cinder/TinderBox/commit/01e123228c9d59141ff3ff1bbc4fae81fa49c790)
