### ISSUE TITLE
Can't copy text from docs

### ISSUE THREAD

**Issue by drewish** [cinder/Cinder#1154]
I'm not sure this is the right place to report bugs with the website. If it's not I'd love to be pointed in the right direction.

Noticed an issue with https://libcinder.org/docs/guides/transition_0_9/index.html 
Using Chrome Version 45.0.2454.101 (64-bit) on OS X 10.10.5
I didn't try replicating it on other pages or with other browsers.

I cannot copy highlighted text by pressing `Cmd` + `C`. The text is deselected and I jump to the top of the page. I spent a bunch of time boiling it down to this simple example:
- Scroll down the page
- Left click
- Press a key (control, option, command, shift)

You'll jump to the top of the screen. So seems like some errant JS capturing key down events.

The work around is to use the Copy command in the Edit or right-click context menu... still jumps to the top of the page though.

**Comment by drewish** [comment]
So second data point with Safari Version 9.0 (10601.1.56.2) it's got the same issue. Upside with Safari is right-click then Copy doesn't jump to the top of the page.

**Comment by gregkepler** [comment]
I PR'ed a fix for this. Sorry about that.

**Comment by richardeakin** [comment]
Fixed by #1155.

**Comment by richardeakin** [comment]
Just noticed this is still a problem, I couldn't copy the method signature for ip::resize() [here](https://libcinder.org/docs/namespacecinder_1_1ip.html#accc5f40c4880b82e77998494afbbeba4) without the page jumping to the top. I'm using Chrome latest on a mac.

**Comment by sansumbrella** [comment]
Extra data point:

If you resize the window after loading the page, it avoids this problem.

If there is some resize/reflow code that manages the fix, it probably needs to be run on load, too.
Chrome latest on OSX.

**Comment by drewish** [comment]
@sansumbrella the resize trick doesn't seem to work on safari

**Comment by wdlindmeier** [comment]
It doesn't look like the changes in #1155 have been propagated to the live website.

**Comment by braitsch** [comment]
+1 still seeing this behavior as of 12/14/15.

**Comment by drewish** [comment]
I'm ready to propose just removing the search feature. It's both irritating and useless. I just tried searching for `keyDown` and got nothing: https://libcinder.org/docs/search.html?keyDown

I'll open another issue for this.

**Comment by drewish** [comment]
Ugg, and the form element doesn't have `autocomplete="off"` to disable the browser's autocomplete so they end up battling each other.

**Comment by richardeakin** [comment]
This looks fixed to me in master branch, needs to be merged into release_v0.9.0 but there is a separate issue tracking that (#1213).

Tested with original repro steps here: https://libcinder.org/docs/branch/master/guides/transition_0_9/index.html
