### ISSUE TITLE
cinder::app::Platform::getAssetPath 

### ISSUE THREAD

**Issue by nien** [cinder/Cinder#1156]
getAssetPath is undefined. 

```
Undefined symbols for architecture x86_64:
  "cinder::app::Platform::getAssetPath(boost::filesystem::path const&) const", referenced from:
      cinder::app::AppBase::getAssetPath(boost::filesystem::path const&) const in PaletteBrowserApp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Running _timeline/PaletteBrowser from samples folder. On OSX Yosemite.

**Comment by richardeakin** [comment]
Just built from latest master branch and it is working here. What version of cinder are you using and where did it come from?

Try rebuilding cinder and running the sample again.

**Comment by pizthewiz** [comment]
Yep, the sample builds/links/run for me on OS X 10.11 with the master branch too.

**Comment by nien** [comment]
Yep, rebuilding cinder did the trick. Sorry for the trouble.
