### ISSUE TITLE
Arcball::setWindowSize() is useless

### ISSUE THREAD

**Issue by artm** [cinder/Cinder#116]
Method Arcball::setWindowSize() sets a private field which is never used and can't be queried. A constructor with screen size parameter sets the same private field, but in addition initializes the arcball sphere to fit the screen. Was the point of the setWindowSize() to fit the sphere as well?

the field Arcball::mWindowSize is useless as is now.

**Comment by andrewfb** [comment]
Cleaning up old issues - this should be fixed these days.
