### ISSUE TITLE
Provide a way to set mTextureMappingRectangleArb on ShaderDef directly

### ISSUE THREAD

**Issue by igierard** [cinder/Cinder#1160]
When creating a ShaderDef using the texture() setter there is no way to specify that the texture is ARB or not without having the texture you will use. This can be a problem if using something like a texture from a Quicktime video where the texture is not available right away.

**Comment by simongeilfus** [comment]
Hey,
I might not understand the question but isn't [this](https://github.com/cinder/Cinder/blob/master/src/cinder/gl/Shader.cpp#L54) what you are looking for?

Ex:
```c++
gl::ShaderDef().color().texture( GL_TEXTURE_RECTANGLE_ARB )
```

**Comment by mhintz** [comment]
Propose to close this issue, since @simongeilfus is right
