### ISSUE TITLE
BasicAppMultiWindow sample crashes

### ISSUE THREAD

**Issue by Hurleyworks** [cinder/Cinder#1165]
The BasicAppMultiWindow sample crashes inside draw() because the pointer returned by getWindow()->getUserData() is null.

If the createNewWindow() call inside setup() is removed then the sample works as expected.

using vc2013/vc2015  on Windows 8.1

**Comment by richardeakin** [comment]
Thanks for reporting and apologies for the delay. However I can't reproduce on Windows 8.1 with VS2015 running the v120 compiler - for me I see two windows open at app start, I can add or remove windows without problems.  Can you list the exact steps to reproduce the crash?

**Comment by Hurleyworks** [comment]
Hi Richard,

I've since upgraded to Windows 10 and I just tried this sample again using
the very latest vs2013 Cinder from github and it doesn't crash here either.

When I did experience the crash it was during app startup, so I never saw
any windows. The crash occurred during  the first call to draw() and
debugging showed that draw::getWindow()->getUserData<WindowData>() was
returning a nullptr.

-Steve


On Fri, Nov 27, 2015 at 1:59 AM, Richard Eakin <notifications@github.com>
wrote:

> Thanks for reporting and apologies for the delay. However I can't
> reproduce on Windows 8.1 with VS2015 running the v120 compiler - for me I
> see two windows open at app start, I can add or remove windows without
> problems. Can you list the exact steps to reproduce the crash?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cinder/Cinder/issues/1165#issuecomment-160055431>.
>



-- 
-Steve
http://www.hurleyworks.com

**Comment by richardeakin** [comment]
Would it be possible that your cinder.lib was out of date (for example, you had pulled latest master branch without rebuilding cinder)?

**Comment by Hurleyworks** [comment]
Certainly possible, but too far back for me to remember clearly.  One other
possibility is that when I first started out using Cinder I built Cinder
and the samples using the DLL Runtime Library  since all my other useful
libraries were built using that option. I have no idea if this  could cause
the crash but it's possible that I was running the samples using the (/MDd)
option.  These days I'm using the Static Runtime

On Fri, Nov 27, 2015 at 3:51 PM, Richard Eakin <notifications@github.com>
wrote:

> Would it be possible that your cinder.lib was out of date (for example,
> you had pulled latest master branch without rebuilding cinder)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cinder/Cinder/issues/1165#issuecomment-160202097>.
>



-- 
-Steve
http://www.hurleyworks.com

**Comment by richardeakin** [comment]
Hm, I wouldn't think it would let you build if you were using a different runtime then what cinder.lib was built with. Still, it sounds to me like there was something stale in the static library biting you. Going to close, please reopen if this issue comes up again.
