### ISSUE TITLE
getSignalDisplayDisconnected() on MSW compiler errors

### ISSUE THREAD

**Issue by indefinit** [cinder/Cinder#1166]
I'm not sure if this is programmer error or a bug. I'm trying to detect when a display is disconnected from my system and to emit a quit() call callback.  VS2013 is giving me a "term does not evaluate to a function taking 1 argument".  Code to reproduce:

```
getSignalDisplayDisconnected().connect([this]{this->quit();});
```

Trying this on Windows 8.1, VS2013

Thanks for any help in advance

**Comment by gaborpapp** [comment]
The function required for this signal needs to be like this: `void fn(const DisplayRef &display)`
Try this:
```getSignalDisplayDisconnected().connect([this](const DisplayRef &display) {this->quit();});```

**Comment by indefinit** [comment]
Ah ok, now I get it!  Thanks
