### ISSUE TITLE
Create a DataSourceRef from a std::string?

### ISSUE THREAD

**Issue by sansumbrella** [cinder/Cinder#1167]
Is there a way to create a DataSource from a string? I'm interested in writing tests for the ObjLoader and would prefer to create the assets inline in the test. If not, I'll create separate files.

**Comment by richardeakin** [comment]
I could have sworn I've done this before, but can't find where at the moment. I believe I packed the std::string into a ci::BufferRef, then created a DataSourceBuffer with that.

**Comment by andrewfb** [comment]
```
auto stream = IStreamMem::create( myString.c_str(), myString.size() );
ObjLoader obj( stream );
```

**Comment by sansumbrella** [comment]
Thanks!
