### ISSUE TITLE
OSX 10.8 support

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#1180]
I think OSX 10.8 is still supposed to be supported, but there are 3 errors reported when building 0.9.0.

```
cinder/src/cinder/app/cocoa/AppImplMac.mm:357:50: error: use of undeclared identifier 'kIOPMAssertPreventUserIdleSystemSleep'
IOReturn status = IOPMAssertionCreateWithName( kIOPMAssertPreventUserIdleSystemSleep, kIOPMAssertionLevelOn, reasonForActivity, &mIdleSleepAssertionID );

cinder/src/cinder/app/cocoa/AppImplMac.mm:362:41: error: use of undeclared identifier 'kIOPMAssertPreventUserIdleDisplaySleep'
status = IOPMAssertionCreateWithName( kIOPMAssertPreventUserIdleDisplaySleep, kIOPMAssertionLevelOn, reasonForActivity, &mDisplaySleepAssertionID );

cinder/src/cinder/app/cocoa/PlatformCocoa.cpp:409:81: error: property 'firstObject' not found on object of type 'NSArray *'
NSString *displayName = [localizedNames objectForKey:[localizedNames allKeys].firstObject];
```

**Comment by pizthewiz** [comment]
Hmm, what version of Xcode are you using? I was able to build the master branch on OS X 10.8.5 with Xcode 5.1.1, the [minimum version required by Cinder 0.9.0](https://libcinder.org/docs/guides/mac-setup/index.html), without incident.

**Comment by gaborpapp** [comment]
Oh, sorry about this. I got Xcode 5.0.2. Thanks. Closing the issue.

**Comment by pizthewiz** [comment]
Ahh, definitely give 5.1.1 a try, Software Update should offer to upgrade your 5.0.2 or you could always download it directly from the developer portal.
