### ISSUE TITLE
Cannot combine more than two geom::Sources with geom::SourceMods

### ISSUE THREAD

**Issue by sansumbrella** [cinder/Cinder#1199]
`append`ing more than one geom::Source to a geom::SourceModes object results in only the final source being drawn.

```
auto source = geom::SourceMods(geom::Cone().height(6.0f).radius(3.0f, 0.0f) >> geom::Rotate(Tau / 2.0f, vec3(0, 0, 1)));
source.append(geom::Cylinder().height(10.0f).radius(1.0f));
source.append(geom::Cube().size(vec3(5.0f)));

auto batch = gl::Batch::create(source, gl::getStockShader(gl::ShaderDef().color()));
```

Expected behavior: three shapes are created within the batch.
Actual behavior: only a cube is created.

**Comment by andrewfb** [comment]
Thanks for the report; should be fixed by the above. Was a bug in SourceMods::append() which caused different behavior from the & operator. As an aside, the code above could also be written as:

```
auto source = geom::Cone().height(6.0f).radius(3.0f, 0.0f) >> geom::Rotate(Tau / 2.0f, vec3(0, 0, 1))
	& geom::Cylinder().height(10.0f).radius(1.0f)
	& geom::Cube().size(vec3(5.0f));
```
