### ISSUE TITLE
Docs code styling is unreadable

### ISSUE THREAD

**Issue by wdlindmeier** [cinder/Cinder#1202]
Code samples shown in the docs (e.g. under a function) is formatted in a narrow column. It seems to be adding a new line for every space, making the code unreadable.

For example, open glm::mix here:
https://libcinder.org/docs/group__core__func__common.html

Using Chrome on a Mac.

**Comment by richardeakin** [comment]
Going to leave open until we can verify the fix on the live website.

**Comment by richardeakin** [comment]
It looks updated on the website to me, so closing unless others think there is more work needed here..
