### ISSUE TITLE
BasicApp crashes on Fedora 23 (x86-64)

### ISSUE THREAD

**Issue by gabbayo** [cinder/Cinder#1209]
Hi,
I saw today the port of cinder to Linux and thought about trying it out.
I'm using Fedora 23 (64-bit of course) and have a Haswell laptop with integrated Intel graphics
I cloned the repo, installed the dependencies and built cinder.

I then built the basic app sample and run it.
However, it immediately crashed :(         with "Segmentation fault (core dumped)"

I debugged it a little and got:
Program received signal	SIGSEGV, Segmentation fault.
0x00000000009a380b in (anonymous namespace)::filename_pos(std::string const&, unsigned long) ()

Further investigation led to Platform::findAndAddDefaultAssetPath(), where it fails in the first line of the for loop.

Finally, stepping into further got me to /home/ogabbay/trees/Cinder/include/boost/filesystem/path.hpp:490
bool has_parent_path() const     { return !parent_path().empty(); }
The above line causes the crash.

Trying to do: "p parent_path()" gave me:

Program received signal	SIGSEGV, Segmentation fault.
0x00000000009a380b in (anonymous namespace)::filename_pos(std::string const&, unsigned long) ()
The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(boost::filesystem::path::parent_path() const) will be abandoned.
When the function is done executing, GDB will silently stop.

That's it for me. I don't have a lot of time but I'm willing to help debug this.
Thanks.

**Comment by chaoticbob** [comment]
Hi gabbayo,

Can you share what compiler Cinder and BasicApp was built with? 

Thanks,
Hai

**Comment by gabbayo** [comment]
This is for cinder:

Building Cinder in Debug mode with 4 compile processes
...created dir: /home/ogabbay/trees/Cinder/tools/linux/../../linux/Debug/ogl
-- The C compiler identification is Clang 3.7.0
-- The CXX compiler identification is Clang 3.7.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CINDER_ARCH: x86_64

CINDER_INC_DIR: /home/ogabbay/trees/Cinder/include
CINDER_SRC_DIR: /home/ogabbay/trees/Cinder/src

LIBRARY_OUTPUT_PATH: 

CMAKE_C_COMPILER  : /usr/bin/clang
CMAKE_CXX_COMPILER: /usr/bin/clang++
CMAKE_AR          : llvm-ar
CMAKE_LINKER      : llvm-link
CMAKE_NM          : llvm-nm 
CMAKE_RANLIB      : llvm-ranlib

-- Found OpenGL: /usr/lib64/libGL.so  
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Found CURL: /usr/lib64/libcurl.so (found version "7.43.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'fontconfig'
--   found fontconfig, version 2.11.94
-- Found Fontconfig: /usr/lib64/libfontconfig.so  
-- Found MPG123: /usr/lib64/libmpg123.so (found version "1.22.4") 
--   using MPG123 headers at: /usr/include
-- Found SNDFILE: /usr/lib64/libsndfile.so (found version "1.0.25") 
--   using SNDFILE headers at: /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ogabbay/trees/Cinder/linux/Debug/ogl


This is for BasicApp:

$ ./build 
Building a app...
Cleaning Debug ...
...deleted dir: /home/ogabbay/trees/Cinder/samples/BasicApp/linux/Debug/ogl
---------------------------------------------------------------------------------
Building Cinder in Debug mode with 4 compile processes
...created dir: /home/ogabbay/trees/Cinder/samples/BasicApp/linux/Debug/ogl
-- The C compiler identification is Clang 3.7.0
-- The CXX compiler identification is Clang 3.7.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works

**Comment by chaoticbob** [comment]
Thanks. What version of GCC do you have installed on your system?

**Comment by gabbayo** [comment]
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/5.1.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --disable-libgcj --with-isl --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 5.1.1 20150618 (Red Hat 5.1.1-4) (GCC)

**Comment by chaoticbob** [comment]
Looks like clang is probably using the STL with the new C++11 ABI in GCC 5.1. I just updated the build files to force the the old ABI when GCC 5.x is present: https://github.com/cinder/Cinder/pull/1210

Do a pull and rebuild and let me know how it goes.

**Comment by gabbayo** [comment]
Thanks!
Program now doesn't crash on that STL issue.
However, it still crashes but with the following error:

getStockShader error: VERTEX: 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

 1: #version 150
 2: uniform mat4 ciModelViewProjection;
 3: in vec4 ciPosition;
 4: in vec4 ciColor;
 5: out lowp vec4 Color;
 6: void main( void )
 7: {
 8: 	gl_Position = ciModelViewProjection * ciPosition;
 9: 	Color = ciColor;
10: }

Illegal instruction (core dumped)

Are you using mesa ?
If not, how are you interacting with the GPU ? Directly through libdrm ?

btw, glxinfo gives me:

glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.0.6 (git-2555e00)
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.0.6 (git-2555e00)
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.0.6 (git-2555e00)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by chaoticbob** [comment]
That's odd, based on glxinfo - your machine should be able to create a 3.3 core profile. But the shader compiler seems to only want to support up to version 3.0. Look like I'll need to force the core profile in GLFW. Let me look into this a bit further.

In the meantime, if you want to give ES2 or ES3 a try - looks like your system supports it:
./build -es2 OR ./build -es3  on both Cinder and the BasicApp.

I'm not using full mesa. The system I'm currently on has an NVIDIA card so the mesa libs are only there to support it.

**Comment by gabbayo** [comment]
ok, thanks for the info
Just so I would understand, cinder implements GL API itself but using LibGL.so to interact with the GPU ?

**Comment by chaoticbob** [comment]
It uses libGL. If you add -v on the ./build for the app - you can see it link against GL.

**Comment by chaoticbob** [comment]
I just committed an update that hints at GLFW to use the core profile with support for specific versions: https://github.com/cinder/Cinder/pull/1211.

**Comment by gabbayo** [comment]
Thanks!
BasicApp is working now.
Tried a couple of other samples (not all of them).
Some are working (BasicAppMultiWindow, CameraPersp), some are failing to build (CaptureCube, QuaternionAccum, MotionBasic) and some are crashing (VoronoiGpu, Earthquake)
I will try to follow this project.

**Comment by chaoticbob** [comment]
Try the ones in samples/_opengl !! :) You might enjoy them visually.
