### ISSUE TITLE
Merge documentation PRs into release_v0.9.0?

### ISSUE THREAD

**Issue by pizthewiz** [cinder/Cinder#1213]
Several documentation fix PRs have been merged into master but didn't make it into 0.9.0, so the _Latest Release_ docs on the site in some cases still have bad info. A few of these have been mentioned in other issues as well e.g. #1135.

<img width="602" alt="screen shot 2015-12-03 at 10 52 55" src="https://cloud.githubusercontent.com/assets/648369/11570423/0ae3c876-99ac-11e5-99db-1bab58a53d28.png">

The PRs I'm thinking of are below, but there could certainly be others:
- Update TinderBox link (#1197)
- Fix download links and migrate links to https (#1183)
- Updated git guide. Fixed outdated/broken links. (#1148) (strangely the PR now looks weird but the important commit seems to be 995c7b93)

**Comment by pizthewiz** [comment]
To be a bit more specific, I'm thinking documentation PRs that cover functionality shipped in 0.9.0.

**Comment by richardeakin** [comment]
Are you electing to prepare this? :) We also need a link on the Guides page to the new logging guide, which hasn't been added to master yet even.

**Comment by pizthewiz** [comment]
I could if helpful, though it might be a bit of cherrypicking since I can't find a PR with the Git Guide fixes.

**Comment by richardeakin** [comment]
I think it would be, obviously we can't directly merge master into release_v0.9.0 so it will be a bit of manual preparation to create a branch that can be merged into the release one with only the right commits (the docs additions in this case). @andrewfb correct me if I'm wrong, but the plan is that cherry picking is OK to go into release_* branches because they will never be merged back with master, correct?

**Comment by andrewfb** [comment]
Yes I'd say cherry-picking is fair game for the release_v* branches so let's do it...

**Comment by pizthewiz** [comment]
I'll spend a bit of time with this soon and PR it. As a shortcut I'll first look at all changes to `/docs` but then take a more careful browse to make sure it is all relevant and doesn't reflect new code changes only in the master branch.

Relatedly, is there any policy for documentation changes for code PRs? It seems as though it would be nice, but it might also be a big ask for contributors to be familiar with the API docs/guides?

**Comment by pizthewiz** [comment]
I'm not able to PR this at present if anyone else has some spare cycles…

**Comment by drewish** [comment]
Since I'm the one complaining about the docs, I'm happy to take a swing at this.

**Comment by drewish** [comment]
Here's the specific list of commits I'm looking to pull in. Call it out if I'm missing something.

#1148 Updated git guide. Fixed outdated/broken links.
- f0c04ba49cfbe91a224132e4af184ca4d552dab3
- f1b930f432582c01846651d379251ec3de15a8c6

#1155 Dox next fixes
- 2820edbb23a60e95fceeb684a59dd73c18474928
- 1f0eeead8ef15dca7784e27ad523dfbe974588d2
- 71feb3ed6819c114f81c56a5fb9d3590f2aa6b1c

#1183 Fix download links and migrate links to https
- a1b89a9f0517057952c4e03b3a06eb677f83a60e

#1197 Update TinderBox link
- f1a0fdf65d35bff0e268ae675f703f9b38a8b3f3

#1233 Audio doc cleanup
- e8e9e50edef1b3c49dc36460032bb547de4a6996
- 9bc804418cd337a25adc231cb43d88ae643065ac

**Comment by richardeakin** [comment]
I think this can be safely closed as v0.9.1 was released a while back.
