### ISSUE TITLE
Can we remove/disable the docs search?

### ISSUE THREAD

**Issue by drewish** [cinder/Cinder#1243]
I'd love to just remove the search box from the docs pages. There a plenty of issues with it:
- Interferes with the ability to copy text from the docs (#1154).
- Doesn't have `autocomplete="off"` on the form element so its autocomplete happens along with the browser's autocomplete.
- Only lists classes in search results. So if you search for a method like `keyDown` you'll be confusingly presented with a list of classes (https://libcinder.org/docs/search.html?keyDown) rather than showing the methods in the class to help guide you in.

**Comment by braitsch** [comment]
I also support removing it as it does not function correctly and makes the site feel broken. The docs should be cached in a datastore and properly indexed to allow for a fast and comprehensive search through them.

**Comment by richardeakin** [comment]
Who is 'we' in this case? :)

I think the search is a necessary tool. Seems like it can be improved but please remember, the current docs were close to a one man operation by @gregkepler in his spare time at work, so hats off to him for getting it so far along. We could be stuck with doxygen search toolbar still, which his just plain ugly. But it will obviously take continual effort to function as well as many other websites that we're used to. I know there was still quite a long feature list that Greg was looking at, but the decision was made not to prolong the 0.9.0 release any longer, which included the new website + docs.

Concerning the `autocomplete="off"` thing, this is out of bounds concerning things I know about, but is it something that you or someone else could PR as a fix and we could test it?

As for populating the search with method names and other things than classes, I'm not sure but I think this could be added fairly easily, I opened an issue for it (#1244).

**Comment by drewish** [comment]
Ugg apologies I get that it's a volunteer effort but I find mysel continually frustrated by the current search so that carried over into my tone. Yeah I'm happy to open a PR but I find it a little concerning that the past fix for #1154 never seemed to make it out to the website. Is there a specific branch or different repo that the changes should go into?

**Comment by richardeakin** [comment]
Thanks for helping out! Yes currently it is a hassle right now that we need to merge doc commits into the release branch for them to show up on the website's 'main' docs page, but if you click on the link that says "Master (v0.9.1dev)" then you'll see what has been pushed to github master branch (there was something broken on the server that wasn't pulling but I believe it has been fixed).

As an aside, we really should only be pushing commits to release branch if they are bug fixes, but that's just the way it is currently.

Going to close this one as there are other github issues for remaining issues, although anyone feel free to voice your opinion on how we can continue to improve docs.

**Comment by mottosso** [comment]
> but if you click on the link that says "Master (v0.9.1dev)"

Thank you! This solved it for me. Was really frustrating as I first couldn't tell why it kept scrolling to the top of the page at the press of a key and only now managed to properly search for a fix.

I would try and get this into the 0.9.0 release, as that's what a new user such as myself is using. It also affects the [guides](https://libcinder.org/docs/release/v0.9.0/guides/opengl/part5.html) which harms first impressions.

**Comment by drewish** [comment]
I believe it was back ported but not deployed
