### ISSUE TITLE
linux linker errors

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1249]
Just pulled latest cinder/android_linux branch and followed instructions [here](https://github.com/cinder/Cinder/wiki/Cinder-for-Linux-%7C-Ubuntu-15.X-on-x86_64). Cinder builds fine but I'm getting the following linker errors when trying to build any sample (below is for BasicApp). This is on Ubuntu 15.10, haven't had time to investigate further yet and this is the first thing I've tried to compile on this linux machine..

```
/media/r/go/code/cinder/cinder-master/lib/linux/x86_64/libcinder_d.a(linux_joystick.c.o): In function `pollJoystickEvents':
/media/r/go/code/cinder/cinder-master/src/glfw/src/linux_joystick.c:124: undefined reference to `regexecA'
/media/r/go/code/cinder/cinder-master/lib/linux/x86_64/libcinder_d.a(linux_joystick.c.o): In function `_glfwInitJoysticks':
/media/r/go/code/cinder/cinder-master/src/glfw/src/linux_joystick.c:220: undefined reference to `regcompA'
/media/r/go/code/cinder/cinder-master/src/glfw/src/linux_joystick.c:236: undefined reference to `regexecA'
/media/r/go/code/cinder/cinder-master/lib/linux/x86_64/libcinder_d.a(linux_joystick.c.o): In function `_glfwTerminateJoysticks':
/media/r/go/code/cinder/cinder-master/src/glfw/src/linux_joystick.c:278: undefined reference to `regfreeA'
collect2: error: ld returned 1 exit status
CMakeFiles/Basic.dir/build.make:105: recipe for target 'Basic' failed
make[2]: *** [Basic] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/Basic.dir/all' failed
make[1]: *** [CMakeFiles/Basic.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ryanbartley** [comment]
I had this problem the other day. Hai told me to remove [these](https://github.com/cinder/Cinder/blob/android_linux/linux/CMakeLists.txt#L325-L332) lines from the CMake. Hai told me that boost has a macro called regcomp and it replaces the regular recomp function with recompA which is undefined.

**Comment by chaoticbob** [comment]
This is my fault. Was moving some stuff around in anticipation for cross compiling. I'll fix it here in a sec once I get Linux installed on a VM.

**Comment by richardeakin** [comment]
Thanks Ryan, that fixed it for me, although I'll leave open until a fix makes it into android_linux branch.

Shouldn't need to add an extra header search path for boost, right?

**Comment by chaoticbob** [comment]
Nope, that was a vestigial thing from the early days of the port. A bit surprising that it didn't show up until now.

**Comment by chaoticbob** [comment]
Fixed in the latest PR. https://github.com/cinder/Cinder/commit/0f43d89c850989a60dc722e21ccf6bed7f208436
