### ISSUE TITLE
gl::drawVector() fails on direction is (0,1,0)

### ISSUE THREAD

**Issue by Hurleyworks** [cinder/Cinder#1251]
When the vector direction is straight up, the head cylinder is drawn incorrectly as in screen grab.

Easy way to reproduce is using the Picking3D sample app. Use a Cube instead of the Teapot and disable the animating code in update().

![drawvector](https://cloud.githubusercontent.com/assets/8120255/11998061/a9f82be4-aa5c-11e5-961b-ff9ae0f74370.jpg)

**Comment by Hurleyworks** [comment]
After thinking  a little more maybe 0,1,0 is the "only" one that's right, though it would look better if the arrow was a the top of the line segment. The vectors on the other cube faces all point toward the surface which would be the opposite of where a surface normal points

**Comment by gaborpapp** [comment]
I looked into this briefly and it seems to be caused by [this line](https://github.com/cinder/Cinder/blob/master/src/cinder/GeomIo.cpp#L2416). The quaternion returned is the identity for (0, 1, 0) and (0, -1, 0), which is wrong, that's why the arrow head is not rotated.

**Comment by paulhoux** [comment]
Why is that wrong? The cylinder is defined around the y-axis, so if the direction is parallel to the y-axis, the quaternion should be identity.

**Comment by gaborpapp** [comment]
I might be wrong but I was expecting that the the quaternion rotates the first vector to the other, which is not the case here. And I don't think it will happen even if the direction is normalized. I think glm should handle opposite direction vectors, and it tries to do it according to the comment [here](https://github.com/g-truc/glm/blob/master/glm/gtx/quaternion.inl#L255).

**Comment by paulhoux** [comment]
Ah OK, so the problem is that it returns identity for both (0,1,0) and (0,-1,0)? Yeah, that would be a bug in GLM if that were the case.

**Comment by gaborpapp** [comment]
Thanks for fixing this, Paul.

**Comment by paulhoux** [comment]
Thank you, too, @gaborpapp . I noticed you created an issue for this in the GLM repo, too. Hopefully it will be fixed in a future release. Until then, we'll have this work-around which is just as fine.
