### ISSUE TITLE
bacth defined by geom::Cone renders incorrectly for some parameters

### ISSUE THREAD

**Issue by jonaslindemann** [cinder/Cinder#1260]
A batch created with a default geom::Cone renders fine. However a batch created with a geom::Cone and the height attribute set generates a black cone under the lambert shader. Any ideas?

Example code:

auto batch = gl::Batch::create(geom::Cone().radius(0.5, 0.25), shader); // Works
auto batch = gl::Batch::create(geom::Cone().radius(0.5, 0.25).height(0.5), shader); // Black cone

Thanks in advance!

**Comment by jonaslindemann** [comment]
It seems the normals are inverted. 

auto batch = gl::Batch::create(geom::Cone().radius(0.5, 0.25).height(0.5) >> geom::Invert( geom::NORMALS));

displays correctly. It think the behavior should be consistent. 

Same problems has been found with geom::Torus(...) as well.

**Comment by paulhoux** [comment]
Hi Jonas,

I'm not able to reproduce the issue. Here's a cone using the following setting:
```geom::Cone().height( 0.5f ).radius( 0.5f, 0.25f )```
![2016-01-05_195223](https://cloud.githubusercontent.com/assets/304908/12132042/07475e36-b3e6-11e5-9e71-79fbd6fc0541.png)

As you can see, the normals are pointing outward and the shading is correct. I suspect an issue in your shader. Are you properly calculating the normals in your vertex shader? Something like this:

    #version 150
    
    uniform mat4 ciModelView;
    uniform mat4 ciProjectionMatrix;
    uniform mat3 ciNormalMatrix;

    in vec4 ciPosition;
    in vec3 ciNormal; 

    out vec4 vertPosition;
    out vec3 vertNormal;

    void main(void)
    {
        vertPosition = ciModelView * ciPosition;
        vertNormal = ciNormalMatrix * ciNormal;
        gl_Position = ciProjectionMatrix * vertPosition;
    }

Also compare the following images:

![2016-01-05_195256](https://cloud.githubusercontent.com/assets/304908/12132060/31353de4-b3e6-11e5-8c4f-8e1f525f3c5a.png)
```geom::Cone().height( 2.0f ).radius( 0.5f, 0.25f )```

![2016-01-05_195348](https://cloud.githubusercontent.com/assets/304908/12132069/4120e848-b3e6-11e5-92bf-aa4c4347fc60.png)
```geom::Cone().height( 20.0f ).radius( 0.5f, 0.25f )```

![2016-01-05_195647](https://cloud.githubusercontent.com/assets/304908/12132097/703e237a-b3e6-11e5-93e0-db247cf47866.png)
```geom::Torus().ratio( 0.25f ).subdivisionAxis( 60 ).subdivisionHeight( 60 )```

**Comment by jonaslindemann** [comment]
Skickat från min iPhone

6 jan. 2016 kl. 02:02 skrev Paul Houx <notifications@github.com<mailto:notifications@github.com>>:


Hi Jonas,

I'm not able to reproduce the issue. Here's a cone using the following setting:
geom::Cone().height( 0.5f ).radius( 0.5f, 0.25f )
[2016-01-05_195223]<https://cloud.githubusercontent.com/assets/304908/12132042/07475e36-b3e6-11e5-9e71-79fbd6fc0541.png>

As you can see, the normals are pointing outward and the shading is correct. I suspect an issue in your shader. Are you properly calculating the normals in your vertex shader? Something like this:

#version 150

uniform mat4 ciModelView;
uniform mat4 ciProjectionMatrix;
uniform mat3 ciNormalMatrix;

in vec4 ciPosition;
in vec3 ciNormal;

out vec4 vertPosition;
out vec3 vertNormal;

void main(void)
{
    vertPosition = ciModelView * ciPosition;
    vertNormal = ciNormalMatrix * ciNormal;
    gl_Position = ciProjectionMatrix * vertPosition;
}


Also compare the following images:

[2016-01-05_195256]<https://cloud.githubusercontent.com/assets/304908/12132060/31353de4-b3e6-11e5-8c4f-8e1f525f3c5a.png>
geom::Cone().height( 2.0f ).radius( 0.5f, 0.25f )

[2016-01-05_195348]<https://cloud.githubusercontent.com/assets/304908/12132069/4120e848-b3e6-11e5-92bf-aa4c4347fc60.png>
geom::Cone().height( 20.0f ).radius( 0.5f, 0.25f )

[2016-01-05_195647]<https://cloud.githubusercontent.com/assets/304908/12132097/703e237a-b3e6-11e5-93e0-db247cf47866.png>
geom::Torus().ratio( 0.25f ).subdivisionAxis( 60 ).subdivisionHeight( 60 )

I am not sure what happened here. For the cone it could have been me calling it with the wrong parameters,but I have the same issue with the torus all the time. So now I do a geom::Invert before passing it to batch. Also I am using the stock lambert shader. I can send you an example of the code.

Jonas

**Comment by jonaslindemann** [comment]
I am attaching the project I am working on (a simple scene graph library). Please note the code in HelixNode and TorusNode:

    this->update(torus >> geom::Invert(geom::NORMAL));

and

    this->update(helix >> geom::Invert(geom::NORMAL));

[CinderDemo.zip](https://github.com/cinder/Cinder/files/79748/CinderDemo.zip)

**Comment by paulhoux** [comment]
Hi Jonas,

I am able to reproduce the issue with the code you provided, but haven't figured out what's going on. I'll let you know when I find out what's wrong.

-Paul

**Comment by jonaslindemann** [comment]
Skickat från min iPhone

9 jan. 2016 kl. 05:15 skrev Paul Houx <notifications@github.com<mailto:notifications@github.com>>:


Hi Jonas,

I am able to reproduce the issue with the code you provided, but haven't figured out what's going on. I'll let you know when I find out what's wrong.

Thanks!

Jonas

-Paul

**Comment by paulhoux** [comment]
Hi Jonas,

I know what's wrong: your major radius is smaller than your minor radius, so you're effectively turning the primitive inside-out. If you adjust your parameters, the problem is gone.
![mimxrtor](https://cloud.githubusercontent.com/assets/304908/12241206/ca3bac8a-b85f-11e5-815b-3118a8a00027.png)

-Paul

**Comment by jonaslindemann** [comment]
Thanks! Great support. I will try to see if I can contribute back somehow.
