### ISSUE TITLE
Visual Studio 2015 Update 1 no longer ships v120

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1261]
I just did a fresh install on a new PC and I can't build cinder without switching the toolset to v120. First note I see is:

```
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
```

which is misleading as I've installed the VC++ component (you have to manually select it now, it isn't installed by default).  However after restarting Visual Studio I see the message:

```
C:\Users\rtepu\code\cinder\cinder-master\vc2013\cinder.vcxproj : warning  : The build tools for Visual Studio 2013 (v120) cannot be found. To build using the Visual Studio 2015 (v140) build tools, either click the Project menu or right-click the solution, and then select "Upgrade Solution...". Install Visual Studio 2013 (v120) to build using the Visual Studio 2013 (v120) build tools.
```

So unless someone knows how to get v120 toolset installed some other way, it looks like we can't use VS2015 to build a VS2013 project anymore, so cinder doesn't build by default when you clone it. :/

**Comment by paulhoux** [comment]
AFAIK, you have to install VS2013 first, followed by VS2015.

**Comment by richardeakin** [comment]
Ah, I see, that makes sense - v120 only ships with VS2013. Well at least I left a mark for other poor souls.
