### ISSUE TITLE
Raspbian threading issues

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#1262]
I tried to share a GLES 2 context that resulted in weird crashes. According to @chaoticbob it might be a  broken thread_local issue. More info in the forum https://forum.libcinder.org/#Topic/23286000002564013

**Comment by gaborpapp** [comment]
If I build cinder with gcc 4.9 instead of clang, threading works. It would be nice to avoid gcc if possible, as it is much slower to build with, and I had to reduce the memory split and the number of build jobs to prevent crashing during build.

**Comment by PetrosKataras** [comment]
This [PR](https://github.com/chaoticbob/Cinder/pull/85) should fix context sharing on the RPi2 .

For more info regarding compilers and available options check [this](https://forum.libcinder.org/#Topic/23286000002564013) forum thread.

**Comment by gaborpapp** [comment]
This seems to be caused by a clang bug in Raspbian (https://llvm.org/bugs/show_bug.cgi?id=23165). Fixed in clang 3.7.1, while current Raspbian Jessie has clang 3.5.0.

**Comment by chaoticbob** [comment]
We can't do much about what clang version Jessie ships with. I'll update the wiki to suggest clang 3.7.1 or later to avoid any threading issues.

**Comment by gaborpapp** [comment]
I just double checked this with clang 3.7.1 downloaded from [llvm.org](http://llvm.org/releases/3.7.1/clang+llvm-3.7.1-armv7a-linux-gnueabihf.tar.xz), and the issue still persists unfortunately.
