### ISSUE TITLE
What does this comment on VboMesh::create( numVertices, ... ) mean?

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1264]
On the last two [VboMesh::create()](https://github.com/cinder/Cinder/blob/dd16254f0f4ab2276df845f45b604355e64299f2/include/cinder/gl/VboMesh.h#L86-L89) methods, the last thing it says is "creates a static VBO if none provided." What does this mean? With the first variant I need to provide a VBO in the `std::pair<geom::BufferLayout,VboRef>`, and in the second one I provide a `VboMesh::Layout`, where I can specify `GLenum usage` to be whatever I want, yet I don't explicitly provide a Vbo to that second constructor. Are those comments just from an older time or is it a different notion of static?

**Comment by andrewfb** [comment]
The phrase is in reference to the preceding part of the sentence: `Allows optional \a indexVbo to enable indexed vertices;` - if you don't provide an indexVbo argument then we create a static index VBO automatically.

**Comment by drewish** [comment]
One thing that might be nice is an example of how to pass in the indices. I think I was scratching my head until I looked at one of Paul's examples.

**Comment by richardeakin** [comment]
@andrewfb Oh okay that makes sense I think just writing it as 'creates a static _index_ VBO if none is provided.." would clear it up, given that it is a pretty long sentence. I know I asked a couple other dudes and they also were a little unclear what that line meant. Happy to do it if you agree.

**Comment by andrewfb** [comment]
Yeah I definitely agree, not well-phrased. Your suggestion would definitely improve it IMO.
