### ISSUE TITLE
CameraUi still sets events as handled when disable()d

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1283]
Reported by @drewish on this [forum post](https://forum.libcinder.org/topic/camui-vs-app-mousedown#23286000002587007)

[Looks like](https://github.com/cinder/Cinder/blob/bf2e23d56e1960ea5a87fb41f722ac6a13456fbc/src/cinder/CameraUi.cpp#L113-L158) the connected mouse handlers still call `event.setHandled()`. A simple solution would be to change that to

```cpp
event.setHandled( mEnabled );
```

since the non signal `mouse*()` methods are checking for mEnabled already and returning early.

We could also easily add a method like `CameraUi::isConnected()` that returns whether the window signals are currently connect or not, as that was also requested.

**Comment by andrewfb** [comment]
Ah sorry about that - I'll fix it.

**Comment by drewish** [comment]
Oh awesome, thanks for such a quick response.
