### ISSUE TITLE
Doesn't works windowSize

### ISSUE THREAD

**Issue by meshedwell** [cinder/Cinder#1285]
**# ## i wanna make 100px x 100px windowsize.
but it is not work.
it's 640 x 480 same size T- T..
what's wrong..? i'm using visual studio 2013 community..!
**
--------------------------------------------------------------------------------------------------------
#include "cinder/app/App.h"
#include "cinder/app/RendererGl.h"
#include "cinder/gl/gl.h"

using namespace ci;
using namespace ci::app;
using namespace std;

class CinderProject2App : public App {
  public:
	void setup() override;
	void mouseDown( MouseEvent event ) override;
	void update() override;
	void draw() override;
	void prepareSettings(Settings * settings);
};

void CinderProject2App::prepareSettings(Settings * settings)
{
	settings->setWindowSize(100, 100);
}

void CinderProject2App::setup()
{
}

void CinderProject2App::mouseDown( MouseEvent event )
{
}

void CinderProject2App::update()
{
}

void CinderProject2App::draw()
{
	gl::clear( Color( 0, 0, 0 ) ); 
}

CINDER_APP( CinderProject2App, RendererGl )

**Comment by brucelane** [comment]
prepareSettings is not called

**Comment by meshedwell** [comment]
bruce thanks for responce.
i did it but error appears

-------------------------------------------------------------------------------------------------------------
CINDER_APP( CinderProject2App, RendererGl, &CinderProject2App::prepareSettings )
--------------------------------------------------------------------------------------------------------------

Error	1	error C2664: 'void std::_Func_class<_Ret,cinder::app::AppMsw::Settings *>::_Set(std::_Func_base<_Ret,cinder::app::AppMsw::Settings *> *)' : cannot convert argument 1 from '_Myimpl *' to 'std::_Func_base<_Ret,cinder::app::AppMsw::Settings *> *'	c:\program files (x86)\microsoft visual studio 12.0\vc\include\functional	506	1	CinderProject2

**Comment by ryanbartley** [comment]
Needs to be static in this case. Or could be free floating function.

**Comment by meshedwell** [comment]
wow! raybartley and brucelane! 
it's works!
SOLVED!!! thanks very much ♥♥♥♥♥♥

i should study harder! thank you :)
