### ISSUE TITLE
Doesn't works loading Image.

### ISSUE THREAD

**Issue by meshedwell** [cinder/Cinder#1286]
i studied cinder using this web book under URL. 
"https://www.packtpub.com/packtlib/book/Big%20Data%20&%20Business%20Intelligence/9781849519564/5/ch05lvl1sec35/Loading%20an%20image"
almost is good.but importance of few code in this book is wrong like vec2f,prepareSettings  etc ...
maybe i guess this book focused on older version of cinder.
anyway i want to study cinder lately version.
how can i study and get formal information about lately cinder?

For loading image what's wrong code in this?
-----------------------------------------------------------------------------------------------------------------------------
#include "cinder/app/App.h"
#include "cinder/app/RendererGl.h"
#include "cinder/gl/gl.h"
#include "cinder/ImageIo.h"
#include "cinder/gl/Texture.h"

using namespace ci;
using namespace ci::app;
using namespace std;

class LoadingImageApp : public App {
  public:
	void setup() override;
	void mouseDown( MouseEvent event ) override;
	void update() override;
	void draw() override;
	gl::Texture myimage;
	
};

void LoadingImageApp::setup()
{
	myimage = gl::Texture(loadImage("assets/image.jpg"));
}

void LoadingImageApp::mouseDown( MouseEvent event )
{
}

void LoadingImageApp::update()
{
}

void LoadingImageApp::draw()
{	
	gl::clear( Color( 0, 0, 0 ) ); 
	gl::draw( myimage, getWindowBounds());
}

CINDER_APP( LoadingImageApp, RendererGl )

**Comment by gaborpapp** [comment]
Cinder has been updated since then. The book is outdated. See this related forum post: https://forum.libcinder.org/#Topic/23286000002574063

**Comment by ryanbartley** [comment]
There's much more information at the website, https://libcinder.org/docs/.

**Comment by meshedwell** [comment]
Thanks for Reply:) i should be there!
