### ISSUE TITLE
tinderbox window is too small to choose a visual studio project on a 4k screen

### ISSUE THREAD

**Issue by vertgo** [cinder/Cinder#1287]
Using an UHD monitor, tinderbox won't let you generate a cinder project in windows 10
![tinderbug](https://cloud.githubusercontent.com/assets/769494/12768593/a02a10d6-c9de-11e5-938e-f2a42412db5c.png)

**Comment by richardeakin** [comment]
Now that TinderBox is [open source](https://github.com/cinder/TinderBox), can you report the issue there so its in the tracker when maintenance comes around?

**Comment by richardeakin** [comment]
Also just to check, do you have any text scaling going on in display settings?

**Comment by richardeakin** [comment]
This issue was moved to cinder/TinderBox#11
