### ISSUE TITLE
cross-platform cmake

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1301]
Both android and linux are using cmake as a build system, we're planning to unify this and support other platforms as well as an alternative build system, initially Windows and OS X.

Related discussion: https://github.com/cinder/Cinder/issues/1250

Checklist:
- [x] Linux support
- [x] Mac OS X support
- [X] Windows support
   - not complete, but added enough support to realize the MinGW toolchain isn't currently adequate to build libcinder so moving on for now as users should almost always be using the VS toolchain on windows if they care about performance on windows.
- [X] Android support
  - moved to #1484
- [x] export configuration from main cinder cmake config that can be imported by projects that depend on cinder
- [x] define variables like `CINDER_TARGET` and `CINDER_TARGET_GL` in a common cmake file that can be included by both libcinder and projects that depend on cinder (samples)
- [x] make sure variables match the naming scheme defined by #1303
- [x] remove old platform-specific cmake files
- [x] add support for building all samples

**Comment by richardeakin** [comment]
Closed with #1481.

**Comment by ulyssesp** [comment]
Looks like after these changes the old instructions for building the samples don't apply anymore. @richardeakin are there new instructions somewhere?
