### ISSUE TITLE
OSC: nullptr exception when using the copy constructor for received messages

### ISSUE THREAD

**Issue by ulyssesp** [cinder/Cinder#1308]
In the new OSC block the copy constructor gives a nullptr exception. It seems to be because `message.mCache` is undefined and `ByteBuffer` calls `size` which requires a reference to `this` (which it doesn't have). 

By changing [this line](https://github.com/cinder/Cinder/blob/master/blocks/OSC/src/Osc.cpp#L113) to `mCache( nullptr )` the problem is fixed, but `mCache` should probably be initialized if `mIsCached` is true.

This happens on Windows, I have not tested on other platforms.

**Comment by ryanbartley** [comment]
Thanks for reporting it. What was the scenario that you were using this with? From the other posting, I certainly need to create a default constructor that's not just `= default`, so that I can set mIsCached to false. Does that fix this scenario? As in, did this come up because the mIsCached variable was uninitialized?

**Comment by ulyssesp** [comment]
@ryanbartley Yes, that would fix this scenario. Updated #1309 to implement that.

Here's the interesting thing. `default` should initialize `mIsCached` to `false`, right? But it doesn't seem to be doing that. The other solution I toyed around is caching by default by running `createCache` at the end of `bufferCache`, but that seems a little heavy-handed.

The situation where this came up is updating code to the new OSC block. The osc messaging system is abstracted from the rest of the program and one of the first things that I do with an osc message is create a copy to pass along to the main thread.

**Comment by ryanbartley** [comment]
That was my bad for sure. When using default, the constructor just default initializes the class. For built-in types like int, float, bool, etc., their initialization is undefined. In the case of bool, sometimes it will be false, often times it'll be true. Good to know people are using it :)
