### ISSUE TITLE
Problems with build of Vulkan version

### ISSUE THREAD

**Issue by acterhd** [cinder/Cinder#1322]
I can't build Cinder by reasons: 
- Boost not found
- Vulkan not found
- Errors with int uint (boost 1.60)

I don't understand how to compile Cinder with Vulkan? 

Tool: Visual Studio 2015.

**Comment by pizthewiz** [comment]
It sounds as though your clone was not done properly, the [README.md](https://github.com/cinder/Cinder/blob/master/README.md) says:
```sh
$ git clone --recursive https://github.com/cinder/Cinder.git
```

this will clone the repo _AND_ the submodules which you have called out as _not found_ above. Worth noting, the command above will recursively clone the repo's master branch, you could add `--branch vulkan` on an initial clone to grab the vulkan branch and its submodules.

The [7.11 Git Tools - Submodules](http://git-scm.com/book/en/v2/Git-Tools-Submodules) chapter from the git book goes into greater detail.

**Comment by acterhd** [comment]
When I try build VS2013 project (not winrt), I get errors with Int <->
Uint.
Used: Visual Studio 2015.

2016-02-22 3:00 GMT+08:00 pizthewiz <notifications@github.com>:

**Comment by chaoticbob** [comment]
I think you're going to need to post the actual error message and more detail on what's happening. The branch is known to work on both Visual Studio 2013 and Visual Studio 2015.

**Comment by acterhd** [comment]
I sent message error, in PNG.

**Comment by chaoticbob** [comment]
Looks like you turned on "Treat Warnings As Errors". The warnings it's catching are harmless.

**Comment by acterhd** [comment]
Not, is not turned on.

**Comment by acterhd** [comment]
Problems again.
