### ISSUE TITLE
Cinder Vulkan back-end: Image views are created without aspect mask being correctly defined for the specified subresource range

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1328]
(to reproduce this issue, we used Fish Tornado application).

We're seeing an issue in ImageView::initialize() function implementation, where imageViewCreateInfo.subresourceRange.aspectMask is being set to 0:

![image](https://cloud.githubusercontent.com/assets/9154207/13245919/b5c54a18-da10-11e5-89f9-a2b08a3fb6b4.png)

This is illegal as per the following spec language, and will cause issues on our implementation:

![image](https://cloud.githubusercontent.com/assets/9154207/13245967/01eb73cc-da11-11e5-9333-f9c51ac9534b.png)

We would like to take this opportunity to recommend Cinder project team to use Khronos validation layers for Vulkan, which would let you quickly capture this and other issues in Vulkan-related code.

**Comment by chaoticbob** [comment]
@kbiElude Thanks! I was wondering when someone like you would show up. :) We're working on incorporating the validation layers as soon as possible. 

The aspectMask is a bug. I thought I had resolved but that it's still there. Will take a look.

**Comment by chaoticbob** [comment]
Fixed: https://github.com/cinder/Cinder/commit/29eeac978bd8009ead24ac13d47ad0b2dffe230e
