### ISSUE TITLE
Cinder Vulkan back-end: Depth images are used as render-targets but are not initialized with DEPTH_STENCIL_ATTACHMENT_BIT usage bit.

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1329]
This issue occurs when setting up the D32_SFLOAT image when Fish Tornado application initializes and will prevent the application from running correctly on our hardware.

**Comment by kbiElude** [comment]
Note that this issue may also affect other images initialized by & later used by the app.

**Comment by chaoticbob** [comment]
Should be addressed in: https://github.com/cinder/Cinder/commit/0b5cdc89eba732bc4440514e1276c00daef0ff18 and
https://github.com/cinder/Cinder/commit/99776f3147df2681940085b90e588314283d52a2.
