### ISSUE TITLE
Cinder Vulkan back-end: Depth attachments should not be transferred to COLOR_ATTACHMENT_OPTIMAL layout

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1330]
In RenderPass.cpp::RenderPass::beginRenderExplicit(), we have:

![image](https://cloud.githubusercontent.com/assets/9154207/13247708/2cb9e034-da1b-11e5-9d79-ed1a16bc56e5.png)

The image memory barrier which transfers each image to the COLOR_ATTACHMENT_OPTIMAL layout is also recorded for depth attachment of a framebuffer used by FishTornadoApp::Light class, which is invalid.

**Comment by chaoticbob** [comment]
Updated the memory barrier transitions to account for color and depth/stencil: https://github.com/cinder/Cinder/commit/1a3463245c082e3b9312ef9715c7e4fffe0d52d0.

Let me know how this goes.

**Comment by kbiElude** [comment]
Yup, that works fine, thanks!
