### ISSUE TITLE
Cinder Vulkan back-end (Fish Tornado test app): Invalid VkPipelineColorBlendAttachmentState structure passed when creating a graphics pipeline

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1332]
Consider the following stack:
![image](https://cloud.githubusercontent.com/assets/9154207/13250310/921587a4-da29-11e5-861a-7c97536d21bc.png)

From what I'm seeing, the test application appears to be trying to create a graphics pipeline whose renderpass:

- defines 3 attachments (1 depth, 2 color)
- defines first subpass for shadow map rendering purposes, implying it only uses the depth attachment (which happens to be specified as zeroth framebuffer attachment)

In PipelineSelector::getSelectedPipeline(), the GFX pipeline is created:

![image](https://cloud.githubusercontent.com/assets/9154207/13250423/2affd87a-da2a-11e5-81ec-3217431d2fe7.png)

There's a few interesting things here:

1. From the screenshot and the discussion above, this pipeline is only going to be used to render to the depth attachment.
2. However, the app defines pColorBlendState field. This is wrong, as according to the spec:

```
(VkGraphicsPipelineCreateInfo::)pColorBlendState is a pointer to an instance of the VkPipelineColorBlendStateCreateInfo structure, or NULL if the pipeline has rasterization disabled or if the subpass of the render pass the pipeline is created against does not use any color attachments.
```

..and we already agreed there's no color attachments used by this subpass.

This ultimately leads to a crash in the driver layer since pColorBlendState->attachmentCount is 1 (which is  invalid too, as there are no color attachments defined for this subpass, so this should actually be zero).

**Comment by chaoticbob** [comment]
This is more than likely a bug in the Pipeline selector. I'll take a look soon. Thanks for providing such detailed issues.

**Comment by chaoticbob** [comment]
Fixed: https://github.com/cinder/Cinder/commit/43f83ecfa50d5973180815b1676e453dd9b1d52d.
