### ISSUE TITLE
RendererVk.cpp no longer builds

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1334]
It seems like Cinder includes an outdated Vulkan header which causes building problems with the latest version:
![image](https://cloud.githubusercontent.com/assets/9154207/13315477/317eab90-dbab-11e5-9611-7ac5ce561bce.png)

VK_API_VERSION is 1.0.1, whereas SDK version is 1.0.3

**Comment by chaoticbob** [comment]
The submodule was just updated to include the 1.0.3 headers. Did you try:
```
git submodule update --recursive
```

**Comment by kbiElude** [comment]
Gotcha, my bad!

**Comment by chaoticbob** [comment]
You just happen to catch at the right time. :) I don't know of any easy way to tell the containing repo a submodule has been updated.
