### ISSUE TITLE
Cinder Vulkan back-end (Fish Tornado test app): App issues implicit LOD texture fetches from vertex shader(s)

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1335]
Depth.vert issues a number of texture() function calls without specifying LOD explicitly. These are converted to OpImageSampleImplicitLod SPIR-V instructions. As per SPIR-V spec:

```
This instruction is only valid in the Fragment Execution Model
```

Other shaders may also be affected by this problem.

**Comment by kbiElude** [comment]
This could actually be a bit more complex, since the texture() calls are being made for rect textures. I'll get back to you on this.

**Comment by chaoticbob** [comment]
Please correct me if I'm wrong, but these calls are made to an texture is using unnormalizedCoordinates -- these can only have 1 mipmap level and 1 layer right?

**Comment by kbiElude** [comment]
You're right that the samplers should configure unnormalizedCoordinates to achieve rectangle texture functionality. However, Vulkan does not recognize the concept of rectangle samplers on the API level. Instead, a 2D sampler should be declared in the shader. The solution therefore is to replace all sampler2DRect types with sampler2D.

**Comment by kbiElude** [comment]
Oh, and in this case, you're also going to need to replace texture() calls with textureLod() of course :)

**Comment by chaoticbob** [comment]
Hah, alright. Thanks for all this. I will take a look in the morning. It's PST here.

**Comment by kbiElude** [comment]
Sorry, didn't want to wake you up! :-)

**Comment by chaoticbob** [comment]
No worries. it was just approaching my bed time. 

I've made the fixes that you've suggested: https://github.com/cinder/Cinder/commit/6b0c1729b6506a1cf9d005b226152bebf60ffcc2.

Everything seems to work on my system.

**Comment by kbiElude** [comment]
Magic, thanks!
