### ISSUE TITLE
Cinder Vulkan back-end (Fish Tornado test app): App attempts to begin recording the same command buffer without ending the previous recording session.

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1336]
If the same command buffer is to be re-used, vkBeginCommandBuffer() should be preceded by a vkEndCommandBuffer() call first.

Obligatory call stack:
![image](https://cloud.githubusercontent.com/assets/9154207/13318197/b32b38d0-dbb9-11e5-96b1-d24c46a16256.png)

To reproduce, replace CommandBuffer::begin() with:

![image](https://cloud.githubusercontent.com/assets/9154207/13318228/fa20d48e-dbb9-11e5-9610-420b354022f3.png)

..and hook a breakpoint in the new if() block contents. When you enter this block, insert a new breakpoint at the beginning of CommandBuffer::begin() entry-point. 352th invocation is invalid. This assumes only one thread is used to initialize the app.

**Comment by chaoticbob** [comment]
Any chance you can give a bit more detail on this? I can't reproduce this issue on my 7970M.

**Comment by kbiElude** [comment]
Try adding a boolean to CommandBuffer. Set it to true at begin() time, reset it back to false at end() call time, and add an assertion check in begin(), verifying that the variable is true before proceeding with vkBeginCommandBuffer() call time.

I'll re-check this with HEAD version shortly.

**Comment by kbiElude** [comment]
No longer reproduces with the latest version
