### ISSUE TITLE
Cinder Vulkan back-end (Fish Tornado test app): vkFreeDescriptorSets() is called for a descriptor, whose parent pool is not init'ed with CREATE_FREE_DESCRIPTOR_SET_BIT flag

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1337]
As per spec:

```
If flags includes VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT, then descriptor sets can return their individual allocations to the pool, i.e. all of vkAllocateDescriptorSets, vkFreeDescriptorSets, and vkResetDescriptorPool are allowed. Otherwise, descriptor sets allocated from the pool must not be individually freed back to the pool, i.e. only vkAllocateDescriptorSets and vkResetDescriptorPool are allowed.
```

While I have not yet got to a point where DescriptorSet::destroy() is called, that function does call vkFreeDescriptorSets() and nowhere in Cinder library is a descriptor pool initialized with that flag defined.

**Comment by kbiElude** [comment]
Also, for performance reasons, please consider whether you actually need to use vkFreeDescriptorSets() at all. The flag has notable perf implications you may prefer to avoid.

**Comment by chaoticbob** [comment]
Added Options to pool to allow for the control of this. Descriptors are only freed if the pool is created with CREATE_FREE_DESCRIPTOR_SET_BIT set.
