### ISSUE TITLE
Cinder Vulkan back-end (Fish Tornado test app): App uses descriptor pools in an incorrect manner

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1338]
There are two misinterpretations I'd like to describe under this ticket, both directly causing our driver to report an error or crash when the Tornado test app is initializing.

The application initializes a number of descriptor pools for its usage. Each descriptor pool allocation usually uses non-trivial (>1) <poolSizeCount> and <maxSets> parameter declarations. For simplicity, let's say we have a pool A which has had M uniform buffer and N storage image descriptor slots requested. Later on, as the app continues to initialize, it issues a number of vkAllocateDescriptorSets() calls on pool A, each invocation setting VkDescriptorSetAllocateInfo::descriptorSetCount field to 1, and requesting M uniform buffers and N storage images.

Now, let's have a look at the spec. For VkDescriptorPoolCreateInfo::pPoolSizes, the following information regarding valid usage is included:

pPoolSizes is a pointer to an array of VkDescriptorPoolSize structures, each containing a descriptor type and number of descriptors of that type to be allocated **in the pool**.

The bold part is very easy to omit and it's crucial for our driver. Cinder framework appears to assume that, as a client, it is guaranteed to be able to carve M*maxSets UB and N*maxSets SI descriptors before being returned an error, whereas the truth is you can allocate **up to** M uniform buffer descriptors and **up to** N storage image descriptors in total, before running out of preallocated space. You can distribute these preallocated descriptors to as many as maxSets descriptor sets, but no more than that.

Furthermore, another problem I see is that the framework has no way of handling situations where descriptor set allocations fail for reasons like fragmentation. I haven't analyzed the implementation to determine whether that's something you should be worried about, but I did see that the framework may call vkFreeDescriptorSets() at some point, which can lead to alloc failures in longer runs. You should definitely have a fall-back path for such scenarios.

**Comment by chaoticbob** [comment]
The first part: I actually wondered about this when I first implemented it, but I couldn't find a clear answer on it. Your description makes sense. This also sounds like it may be cause of the crash that I'm seeing in the other samples. I'll revisit both of these later today.

**Comment by chaoticbob** [comment]
I've updated the logic for the how the descriptor pool handles the slot reservations. We're still working out how to make this part of the code robust. Our current and overly simplistic and inefficient use case is that there's a pool allocated against every descriptor set. By this logic, a free probably isn't required.

That being said, that's not the intention of how Cinder should work. I'll leave this issue open as a reminder to update the descriptor pool more robust.

**Comment by kbiElude** [comment]
Seems like the first problem has been addressed, judging by the HEAD version. :-) Haven't had a look at how you worked around it, but at least our driver is now happy.

**Comment by chaoticbob** [comment]
Closing since the driver is happy. :) Please reopen if the second issue wasn't resolved with this.
