### ISSUE TITLE
Cinder Vulkan back-end (ShadowMappingBasic test app): Depth image is not assigned VK_IMAGE_DEPTH_STENCIL_ATTACHMENT_BIT usage flag at creation time

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1341]
The application sets up a depth image in ShadowMappingBasic::setup():

![image](https://cloud.githubusercontent.com/assets/9154207/13355187/5f927a8a-dc9f-11e5-985f-755658a85085.png)

..and later tries to use a child image view as a depth attachment for a subpass. However, for that operation to succeed, the image must be defined as "depth-renderable" (for the lack of better formal Vulkan wording) at creation time.

**Comment by kbiElude** [comment]
Similar issue exists in the ShadowMapping test app.

**Comment by chaoticbob** [comment]
All these got fixed last night. Sorry I didn't commit yet. :)

**Comment by chaoticbob** [comment]
Fixed all both ShadowMapping and ShadowMapping basic in _vulkan and _vulkan_explicit: https://github.com/cinder/Cinder/commit/c4e576aa7a185936dfde93a3eb1f2ccaa9051110. Massive PR.
