### ISSUE TITLE
Cinder Vulkan back-end (NormalMappingBasic test app): ciBlock1T UB is assigned a 12-byte range of a buffer view

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1342]
Consider the following UB declaration from one of the app shaders:

![image](https://cloud.githubusercontent.com/assets/9154207/13356635/aa057eda-dca6-11e5-9812-572fe7cb0391.png)

The problem I have with this is that, in SPIR-V, this block does not end up annotated as laid out in manner described for std140 layout. It's effectively platform-specific. However, in Vulkan, there's no reflection mechanism you could use to check whether the block is 12-bytes (std140) long or perhaps larger (platform-specific). Later on, the app attaches a 12-byte block to the binding via descriptor set, which is not cross-platform. For std140, it should be 16-byte long.

I believe this problem applies to other example projects as well.

**Comment by chaoticbob** [comment]
Thanks! I ran into this last night as well when investigating the descriptor set issue you mentioned. I'll commit the fix later today.

**Comment by kbiElude** [comment]
Oh, come to think of it, apologies if I wasn't clear here. What I was trying to convey here was that I'd suggest annotating all uniform blocks with std140 layout qualifier and making sure the framework uses the right offsets & sizes for the block members.

**Comment by chaoticbob** [comment]
Gotcha. I figured that was what you meant. Fixed here: https://github.com/cinder/Cinder/commit/78da66a5f8aa4888dc41fd62e870dec921547a81

**Comment by kbiElude** [comment]
Are you sure that commit also fixes the problem of the buffer memory region, which gets attached to the uniform block , being 12-bytes, instead of 16-bytes long, as per std140 layout qualifier definition?

**Comment by chaoticbob** [comment]
Hmm..you're right. This is a bit odd. The block size is actually being pulled back using glslang's reflection API - which should apply all the std140 rules.

**Comment by kbiElude** [comment]
Oh, with the new annotation, it may now be 16b long then. I haven't re-checked it today, just thought it would be a good idea to verify this before closing the ticket.

**Comment by chaoticbob** [comment]
Sorry, I "verified" by stepping through to see if the update to the UBO was okay. ButI I just looked at the size coming back from glslang and it is 12 bytes. IIRC, the rule for vec2/vec3 and friends is 4 times the the machine size of a component. Which should be 16 bytes for all stand alone vec2 and vec3. Is it resulting in a crash on your end?

**Comment by chaoticbob** [comment]
This can probably be filed under "paranoia fixes": https://github.com/cinder/Cinder/commit/e594bb3b2f55ee2ee8933ebd3c2fa25d2db4ffd4. To avoid any ambiguity, uniform interface blocks now padded out to end on 16 byte boundaries. I'll double check with the glslang group to see what "in practice" implications are for cases like this.

**Comment by kbiElude** [comment]
Don't mind paranoia, when it comes to coding :) Please consider filing this bug in glslangvalidator project, just so that their team can fix it on their end.

If I were to nitpick, I'd also suggest adding an assertion check which would confirm the UB is annotated with std140 before assuming the block size has to be rounded up on 16-byte boundary. Not sure if that info is exposed by glslangvalidator, but if it is, it would help the library users identify the issue at an instant, in case they forget to define the layout qualifier in their shaders.

Can't tell for sure if that bug on its own resulted in a crash in our driver, as there were other problems about the code which definitely did cause one, but it was one of the things that caught my attention when I was debugging the library.

**Comment by chaoticbob** [comment]
I'll file an issue on glslang's repo. Definitely hear you on the nit pick bit. Last I checked, about a week ago, the reflection information was still minimal. I have a couple tickets on the glslang repo for more reflection information: https://github.com/KhronosGroup/glslang/issues/156 and https://github.com/KhronosGroup/glslang/issues/154. If I knew anything about parsing and ASTs, I'd jump in. :)

Anyway, I'll file another issue asking to see if the various modifiers for layout, like std140, can be exposed as well.

**Comment by kbiElude** [comment]
Works fine now!
