### ISSUE TITLE
Cinder Vulkan back-end (NormalMapping test app): vk::draw() leaks buffer memory

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1349]
The following code block leaks buffer memory, which ultimately leads to process crash on our driver:

![image](https://cloud.githubusercontent.com/assets/9154207/13392349/211f6e7e-deda-11e5-89bd-5fc17b0c7af2.png)

_vertexBuffer_ is never released.

**Comment by chaoticbob** [comment]
Sorry, my fault. Turned off clearing of transient objects during refactor. Back on now: https://github.com/cinder/Cinder/commit/65f10999bd753010720e271fd424b4912718ce83.

**Comment by oscarbg** [comment]
KbiElude "our driver" means Intel Windows Vulkan driver, which isn't released yet?

**Comment by kbiElude** [comment]
Nope, I'm from AMD.

**Comment by DominikWitczakAMD** [comment]
This problem continues to reproduce. I'm seeing huge memory leaks originating from the app, until the following vk::draw() invocation in NormalMappingApp::draw() is commented out:

![image](https://cloud.githubusercontent.com/assets/17761066/13702203/26e54138-e78d-11e5-9c73-8d980f24ceb8.png)

**Comment by chaoticbob** [comment]
Will check this again.

**Comment by chaoticbob** [comment]
Okay, found the problem The vk::draw functions were not flagging allocations to be transient. They've been updated to do so.

**Comment by chaoticbob** [comment]
This should be fixed now.
