### ISSUE TITLE
Cinder Vulkan back-end (FishTornado test app): Presenter's fragment shader uses invalid output variable location

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1350]
In FishTornado/assets/main.frag, we have:

![image](https://cloud.githubusercontent.com/assets/9154207/13400062/568d1ba2-df06-11e5-945c-f070d6b983ed.png)

In the spec, we can find the following language for VkSubpassDescription:

![image](https://cloud.githubusercontent.com/assets/9154207/13400113/8c6ec68a-df06-11e5-9a47-cf94e853002d.png)

Now, the application never sets VkSubpassDescription::colorAttachmentCount to anything else than 0 or 1. I've also verified with RenderDoc, that it's the latter case for the final pass. As a result, the fragment shader should never specify 1 as the output variable's location there. Instead, 0 should be used.

**Comment by chaoticbob** [comment]
Adjusted here: https://github.com/cinder/Cinder/commit/df046f45e96c37fbb497fdab7e00a30bdeff0cb8. Need to find a better way to communicate the output location to the renderpass and keep it in line with the frag shader.

**Comment by kbiElude** [comment]
It baffles me how this worked on other vendor's drivers but.. :)

**Comment by chaoticbob** [comment]
I was going to say the same thing. :) Maybe it's reductionist: if only one attachment and one output location - just make it work.

**Comment by kbiElude** [comment]
Woudn't that be at odds with Vulkan philosophy where "just make it work" = a big fat no? *cough cough* ;)
