### ISSUE TITLE
Cannot Link OSC & TUIO Examples on Mac OSX (Leopard & Lion) in Xcode 4.2

### ISSUE THREAD

**Issue by Justinmaurer** [cinder/Cinder#136]
Mac OS Version: 	10.6.8 (Lepoard) 32 Bit and 10.7.3 (Lion) 32 Bit
XCode Version:	4.2 Build 4C199

Steps performed to replicate bug:
1.	Cloned master branch
2. 	Copied 1.48 Boost files to cinder directory
3. 	ran xcode/fullbuild.sh (everything built successfully)
4.	ran OSC and TUIO samples and receive the following error:

ld: bad codegen, pointer diff in __ZN5boost15throw_exceptionINS_21thread_resource_errorEEEvRKT_ to global weak symbol __ZN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_21thread_resource_errorEEEED1Ev for architecture i386
Command /Developer/usr/bin/clang++ failed with exit code 1

*Note:
- OSC Samples ran succesffully on XCode 3.3 on Mac OS 10.6.8
- This Linker error has been confirmed on multiple machines

**Comment by andrewfb** [comment]
Fixed
