### ISSUE TITLE
Cinder Vulkan back-end (FishTornado test app): Fast-clear cannot be requested for images in PRESENT_SRC_KHR layout

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1364]
When Presenter initializes, it submits the following VkRenderPassCreateInfo descriptor to the driver:

![image](https://cloud.githubusercontent.com/assets/9154207/13527838/6bb8eb46-e212-11e5-8811-ea01ad28d0a1.png)

Only one subpass is defined for the renderpass:

![image](https://cloud.githubusercontent.com/assets/9154207/13527892/d23d8804-e212-11e5-8e71-0a7b57eaeb76.png)

The problem is that PRESENT_SRC_KHR layout can **only** be used for presentation purposes. In specific, it **must not** be cleared at renderpass start time.

**Comment by chaoticbob** [comment]
Changed the LOAD_OP for the presentation attachment to LOAD: https://github.com/cinder/Cinder/commit/c7a136b707154aaffc0a540ab3d9c07011e168c7

**Comment by kbiElude** [comment]
Fix confirmed, closing.
