### ISSUE TITLE
Cinder Vulkan back-end (FishTornado test app): Allocator attempts to use misaligned memory blocks for vkBindImageMemory() calls.

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1365]
Consider the following call stack:

![image](https://cloud.githubusercontent.com/assets/9154207/13528122/64ca2596-e214-11e5-9705-dff66fe91380.png)

The app is informed the block offset needs to be aligned on 256b boundary. However, for this allocation, Allocator::allocateObject() seems to attempt to re-use an already allocated memory region and does not appear to be too worried about the memory requirements it has earlier probed for:

![image](https://cloud.githubusercontent.com/assets/9154207/13528216/d0f60a8c-e214-11e5-9cfa-cca2de487264.png)

13512 % 256 != 0

This causes an app-side assertion failure to occur, as per screenshot below:

![image](https://cloud.githubusercontent.com/assets/9154207/13528250/0415ac38-e215-11e5-9509-e749b83d05fc.png)

**Comment by chaoticbob** [comment]
This should be fixed now. Wrote a test for it and have it just run through a load of allocations for both image and buffers.

**Comment by kbiElude** [comment]
Fix confirmed, closing.
