### ISSUE TITLE
Cinder Vulkan back-end (Cube test app): Image::blit() assumes srcImage and dstImage have been defined with corresponding usage bits

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1366]
In order to transfer any image to VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL layout, the image must be initialized for VK_IMAGE_USAGE_TRANSFER_SRC_BIT usage. In similar vain, for VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL layout to be supported by an image, the image must have had VK_IMAGE_USAGE_TRANSFER_DST_BIT usage flag set at creation time.

Image::blit() fires image memory barriers that transfer the source & destination images to these two layouts, even though the framework does not appear to take the requirements described above into consideration:

![image](https://cloud.githubusercontent.com/assets/9154207/13528786/91b20872-e218-11e5-9fc7-30b854ae552c.png)

![image](https://cloud.githubusercontent.com/assets/9154207/13528801/a902834e-e218-11e5-82e9-30ab1abd951d.png)

![image](https://cloud.githubusercontent.com/assets/9154207/13528817/c2c72a96-e218-11e5-80f5-743a41372d97.png)

**Comment by chaoticbob** [comment]
Made some fixes to address this: https://github.com/cinder/Cinder/commit/04a98954f15416a4a997115af6135cdbaf505a23.

Also added asserts for the time being to make sure the flags are present.

**Comment by kbiElude** [comment]
Looks like this issue has been fixed :-) Closing.
