### ISSUE TITLE
Cinder Vulkan back-end (FishTornado test app): App declares sampler2DRect uniforms in the flocking shaders

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1373]
sampler2DRect uniforms are declared in the following shaders:

* assets/flocking/position.frag
* assets/flocking/velocity.frag

Instead, sampler2D uniform types should be used.

**Comment by chaoticbob** [comment]
Done! https://github.com/cinder/Cinder/commit/1d75b964a00e867849b60ea57f2e90be06c97f95
