### ISSUE TITLE
Cinder Vulkan back-end (FishTornado test app): Buffer::createBufferAndAllocate() may alloc from non-coherent memory heap but the app never calls vkFlushMappedMemoryRanges()

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1374]
As per the following spec language:

```
In order to enable applications to work with non-coherent memory allocations, two entry points are
provided. To flush host write caches, an application must use vkFlushMappedMemoryRanges, 
while vkInvalidateMappedMemoryRanges allows invalidating host input caches so that device writes 
become visible to the host. vkFlushMappedMemoryRanges must be called after the host writes to 
non-coherent memory have completed and before command buffers that will read or write any of 
those memory locations are submitted to a queue. Similarly, vkInvalidateMappedMemoryRanges 
must be called after command buffers that execute and flush (via memory barriers) the device 
writes have completed, and before the host will read or write any of those locations.
```

Buffer::createBufferAndAllocate() is implemented as below:

![image](https://cloud.githubusercontent.com/assets/9154207/13641714/cf8defee-e619-11e5-8c91-2e0524093273.png)

The allocator may therefore return memory regions carved out from a non-coherent memory heap. The application should either include the VK_MEMORY_PROPERTY_HOST_COHERENT_BIT bit, or make sure the mapped memory ranges are flushed before having the GPU access them.

**Comment by chaoticbob** [comment]
There is now a test for VK_MEMORY_PROPERTY_HOST_COHERENT for buffers and flushes if the flag isn't set. 
https://github.com/cinder/Cinder/commit/4e38d334559c0b36ea7d585657a693d572df0c5a
https://github.com/cinder/Cinder/blob/vulkan/src/cinder/vk/UniformBuffer.cpp#L327-L336
