### ISSUE TITLE
Cinder Vulkan back-end (FishTornado test app): App does not issue a buffer memory barrier after a host write op is performed.

### ISSUE THREAD

**Issue by kbiElude** [cinder/Cinder#1375]
After uniform bufer contents are updated in UniformBuffer::bufferPending(), the application should issue a buffer memory barrier, in order to ensure subsequent operations can correctly access updated data.

**Comment by chaoticbob** [comment]
Done for uniform buffers: https://github.com/cinder/Cinder/commit/19dcde4bbffb946f1fd03c5f1590c0a4fb11e6df.

TBD for other buffer types.

**Comment by chaoticbob** [comment]
Completed.
