### ISSUE TITLE
Cinder Vulkan back-end (NormalMapping test app): Color attachment is not cleared which leads to visual artifacts

### ISSUE THREAD

**Issue by DominikWitczakAMD** [cinder/Cinder#1380]
The app uses one of the two renderpasses, configured as per picture below, to render the mesh:

![image](https://cloud.githubusercontent.com/assets/17761066/13702120/9d99edb6-e78c-11e5-843e-4d7bdad8f32f.png)

This causes disturbing artifacts to show up, since previous frame contents is re-used in subsequent frames.

Recommendation is for the app to fast-clear the attachment by setting loadOp to VK_ATTACHMENT_LOAD_OP_CLEAR, or by recording a vkCmdClearColorImage() OR a vkCmdClearAttachments() call to the command buffer before the mesh is rendered.

**Comment by chaoticbob** [comment]
Added vkCmdClearAttachments when there's single sample. Multi-sample is cleared on load. https://github.com/cinder/Cinder/commit/56a9e19fa233a8a9efc72c8561fe68a1753b4cfd

**Comment by DominikWitczakAMD** [comment]
Works for me :)
