### ISSUE TITLE
Cinder Vulkan back-end (explicit/Cube app): Framework assumes more than one 1 universal queue is available

### ISSUE THREAD

**Issue by DominikWitczakAMD** [cinder/Cinder#1386]
CubeApp.cpp::RotatingCubeApp::setup() does the following:

![image](https://cloud.githubusercontent.com/assets/17761066/13773436/7ed52ff2-ea99-11e5-8713-7d3bc742de83.png)

![image](https://cloud.githubusercontent.com/assets/17761066/13773457/9b5f31b8-ea99-11e5-98ae-6543131522bf.png)

Vulkan spec only guarantees a single universal command queue will be exposed by the driver, so this code is invalid. In general, the engine should not make any assumptions regarding available queue families, and instead dispatch work chunks to hardware-reported command queues, making sure they are correctly synchronized.

**Comment by DominikWitczakAMD** [comment]
Oh, could this actually be a duplicate of https://github.com/cinder/Cinder/issues/1340 ..?

**Comment by chaoticbob** [comment]
It is. I'm going to close it and address the other one.
