### ISSUE TITLE
Cinder Vulkan back-end (FishTornado test app): Invalid renderpass configuration used for the GPUFlocker calculations

### ISSUE THREAD

**Issue by DominikWitczakAMD** [cinder/Cinder#1387]
The following VkRenderPassCreateInfo structure is passed via a vkCreateRenderPass() call in order to set up the renderpass, later used to update fish flock data:

![image](https://cloud.githubusercontent.com/assets/17761066/13814980/032361d0-eb89-11e5-9350-9a0f7ff26af3.png)

pAttachmentDescriptor is an array of the following items:

![image](https://cloud.githubusercontent.com/assets/17761066/13815022/2f3f78ee-eb89-11e5-9ad3-3db999740876.png)

Subpasses are described as below:

* Subpass 0:

![image](https://cloud.githubusercontent.com/assets/17761066/13815063/67e6b554-eb89-11e5-88c4-b5f571576676.png)

* Subpass 1:

![image](https://cloud.githubusercontent.com/assets/17761066/13815339/7d10b73a-eb8a-11e5-9ea6-b02fee1dbb9a.png)

As usual, I marked the interesting bits in red :) Let's see:

* Subpass layout for the only color attachment the subpass 0 renders to is set to SHADER_READ_ONLY_OPTIMAL. That makes little sense, as that attachment is supposed to act as a color attachment, so you want that layout to be set to COLOR_ATTACHMENT_OPTIMAL.
* Same situation in the subpass that follows.
* Last but not least, the second subpass samples from the texture the first subpass renders to. As per the following spec language:

```
The contents of an attachment within the render area become undefined at the start of a subpass S if all of the following conditions are true:

* The attachment is used as a color, depth/stencil, or resolve attachment in any subpass in the render pass.
* There is a subpass S1 that uses or preserves the attachment, and a subpass dependency from S1 to S.
* The attachment is not used or preserved in subpass S.
```

..the contents you've just rendered in the first subpass goes down the drain the moment the second subpass kicks off, since that attachment is not enlisted as an attachment worth preserving.

Finally, there's one subpass dependency defined for the renderpass:

![image](https://cloud.githubusercontent.com/assets/17761066/13815595/84ffa996-eb8b-11e5-8c7b-947423d7a9c3.png)

The ALL_GRAPHICS source stage mask can be reduced to COLOR_ATTACHMENT_OUTPUT, since the intent here is to ensure all color attachment writes can be accessed by the textureLod() instructions in the fragment shader which will be invoked in the subpass that follows.

**Comment by chaoticbob** [comment]
Changes have been made to address this.
