### ISSUE TITLE
Cinder Vulkan back-end (ShadowMapping) - The attachment is not cleared before rendering

### ISSUE THREAD

**Issue by flymj** [cinder/Cinder#1388]
It is application's responsibility to clear the attachment before rendering the frame.

I have modify the  ShadowMappingApp::generateCommandBuffer to add
    vk::context()->clearAttachments(true,true);
after 
    vk::context()->getPresenter()->beginRender( cmdBuf, vk::context() )

Could you take a look and apply the fix?

**Comment by chaoticbob** [comment]
Definite. Can you say what hardware you're running on?

**Comment by davidmaoamd** [comment]
Sorry. I just changed to my account with company suffix. 
I am using AMD's card, R7 360,  on Linux.

**Comment by chaoticbob** [comment]
No problem. Are you building _vulkan/ShadowMapping or _vulkan_explicit/ShadowMapping?

**Comment by davidmaoamd** [comment]
The ShadowMapping from _vulkan_explicit.

Best Regards,
David

**Comment by chaoticbob** [comment]
Are you up to date with the latest changes? 

There already appears to be a call to clearAttachments:
https://github.com/cinder/Cinder/blob/vulkan/samples/_vulkan_explicit/ShadowMapping/src/ShadowMappingApp.cpp#L352-L355

**Comment by davidmaoamd** [comment]
It is really weird.
I clone the repo yesterday and did not find that line in vulkan branch.
I have just pull/rebase the code again, and, yes, the issue has been fixed already.

Anyway, really thanks for your quick response.

Best Regards,
David

**Comment by chaoticbob** [comment]
No problem. Keep the issues coming. :)
