### ISSUE TITLE
ConcurrentCircularBuffer and shared pointers.

### ISSUE THREAD

**Issue by paulhoux** [cinder/Cinder#1397]
Hi,

I just discovered a problem with ```ConcurrentCircularBuffer``` when used with shared pointers, e.g. a ```gl::Texture2dRef```. When popping a value from the buffer, only the index counter (```mNumUnused```) is decremented but the value is still in the buffer and it is never actually popped. This can cause all kinds of problems, in my case a huge memory leak.

This might be the solution:
```
//! Attempts to pop an item from the back of the buffer, but does not wait for an availability. Returns success as true or false.
bool tryPopBack( value_type* pItem ) {
	std::lock_guard<std::mutex> lock( mMutex );
	if( ! is_not_empty_impl() )
		return false;
	*pItem = mContainer[--mNumUnread];
	mContainer.pop_back(); // <-- Added an actual call to pop_back() here.
	mNotFullCond.notify_one();
	return true;
}
```

**Comment by richardeakin** [comment]
I think the idea of the container is that it doesn't grow dynamically (not so useful in the case of smart or raw pointers), but instead just keeps overwriting data that is marked as 'free'. I think what you want is a thread-safe queue, don't you? Slightly different to a ring buffer.

**Comment by paulhoux** [comment]
Yeah, I guess you're right. Although I do believe that this behavior of not popping elements is very dangerous and unexpected.

**Comment by richardeakin** [comment]
Yea I agree that a concurrent queue is the way to go and its what I've used in the past. Its tempting to implement it just by wrapping a std::list<T> or something similar with a mutex and conditions just as ConcurrentCircularBuffer was done, but I ultimately I don't think this is enough. What we really need IMO is something like a dispatch queue that has a thread pool and possibly even priorities (similar to [libdispatch](https://en.wikipedia.org/wiki/Grand_Central_Dispatch)). Although that will take a significant engineering effort and we thought to wait to see what C++17 will bring us in terms of multithreading support, so I would think that creating a custom concurrent queue in the meantime would be a good stop gap solution as it doesn't require much work.

**Comment by paulhoux** [comment]
Yeah, I've got a few implementations lying around based on this excellent article:
https://www.justsoftwaresolutions.co.uk/threading/implementing-a-thread-safe-queue-using-condition-variables.html

I can use those.
