### ISSUE TITLE
Writing JSON file on linux segfaults 

### ISSUE THREAD

**Issue by lucasvickers** [cinder/Cinder#1400]
I'm running cinder out of the current ```android_linux``` branch.  
Best I can tell, in Json.cpp on [lines 701/702](https://github.com/cinder/Cinder/blob/android_linux/src/cinder/Json.cpp#L701-L702) ```OStreamRef os``` is ```null```.

```
OStreamRef os = target->getStream();
os->writeData( jsonString.c_str(), jsonString.length() );
```

I'm unable to investigate deeper at the moment.  I am on Debian Jessie 64bit and compiling into an OGL target.

Reference project below
```
#include "cinder/app/App.h"
#include "cinder/app/RendererGl.h"
#include "cinder/gl/gl.h"
#include "cinder/Json.h"

using namespace ci;
using namespace ci::app;

class BasicApp : public App {
  public:

    void keyDown( KeyEvent event ) override;

    void draw() override;
};

void prepareSettings( BasicApp::Settings* settings )
{
#if defined( CINDER_ANDROID )
    settings->setMultiTouchEnabled( false );
#endif
}

void BasicApp::keyDown( KeyEvent event )
{
    JsonTree config;
    config.addChild( JsonTree( "test", 1 ) );
    config.write( "/tmp/out.json" );
}

void BasicApp::draw()
{
    gl::clear( Color::gray( 0.1f ) );
}

// This line tells Cinder to actually create and run the application.
CINDER_APP( BasicApp, RendererGl, prepareSettings )
```

**Comment by PetrosKataras** [comment]
There are a some open PR's on the android_linux branch that address "smaller" things like this which can be really annoying when not working as expected :) 

This specific one is addressed by #1371 .

**Comment by chaoticbob** [comment]
I merged it. Let me know if it blows up.

**Comment by lucasvickers** [comment]
This specific issue is resolved.
