### ISSUE TITLE
CI_LOG_* cannot display function name in linux

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#1402]
Tested in Fedora 23 with GCC 5.3.1, log macros print `(unknown function)` instead of the function name.

**Comment by chaoticbob** [comment]
Is this in Debug and Release?

**Comment by gaborpapp** [comment]
Debug

**Comment by chaoticbob** [comment]
Looks like GCC was left out in the cold on Linux. Added the definition here: https://github.com/cinder/Cinder/commit/e82812e743d0f849b0078033b6ec95dbcf2eae3b

Log output should look like this now:
```
haing> Debug/ogl/Cube 
Rendering with OpenGL Core Profile 3.2
|info   | virtual void RotatingCubeApp::setup()[31] Loaded texture
|info   | virtual void RotatingCubeApp::setup()[43] Loaded shader
|info   | virtual void RotatingCubeApp::setup()[51] Creaeted batch
```

**Comment by gaborpapp** [comment]
Thanks. It works.
