### ISSUE TITLE
OSC

### ISSUE THREAD

**Issue by brucelane** [cinder/Cinder#1405]
hi,
I just pulled the latest files today, now I get 8 errors on Osc.cpp: 
Error	236	error C2664: 'std::atomic_bool::atomic_bool(const std::atomic_bool &)' : cannot convert argument 1 from 'bool' to 'const std::atomic_bool &'	C:\cpp\Cinder\blocks\OSC\src\Osc.cpp	line 1006 (same for lines: 1012 1018 1396 1482 1488 1494 1500).
I'm using visual studio 2013.
Thank you
Bruce

**Comment by ryanbartley** [comment]
Are you using a sample?

**Comment by brucelane** [comment]
no I use OSC in my app : 
https://github.com/videodromm/videodromm-controller-cinder
which is using my Cinder block:
https://github.com/videodromm/Cinder-Videodromm
which itself uses OSC functions in https://github.com/videodromm/Cinder-Videodromm/blob/master/src/VDRouter.cpp

**Comment by brucelane** [comment]
I just tryed to compile the samples in the OSC block, I got the same errors

**Comment by brucelane** [comment]
It compiles by replacing "false" by "ATOMIC_VAR_INIT(false)"

**Comment by brucelane** [comment]
And even better, what you suggested in Osc.h: 
- lines 620 and 836 std::atomic<bool> mIsConnected;
- line 882 std::atomic<bool> mIsShuttingDown;

**Comment by ryanbartley** [comment]
What's even better?

**Comment by brucelane** [comment]
to replace by std::atomic<bool>

**Comment by brucelane** [comment]
to replace `std::atomic_bool` in Osc.h by `std::atomic<bool>`

**Comment by ryanbartley** [comment]
That worked?

**Comment by brucelane** [comment]
yes it compiled without errors

**Comment by ryanbartley** [comment]
Great. I'll push a fix and PR it in a little bit.

**Comment by brucelane** [comment]
thank you Ryan!

**Comment by ryanbartley** [comment]
No problem.
