### ISSUE TITLE
Resources.h lacking in FboMultipleRenderTargets

### ISSUE THREAD

**Issue by brucelane** [cinder/Cinder#1408]
hi,
samples/_opengl/FboMultipleRenderTargets include folder is lacking, with Resources.h in it

**Comment by brucelane** [comment]
copying it from FboBasic solves the issue

**Comment by richardeakin** [comment]
Thanks for reporting, looks like the app switched to using assets during our last cleanup so Resources.h wasn't needed anymore, I just removed it from the project file.

**Comment by brucelane** [comment]
thank you for updating Richard!
