### ISSUE TITLE
LNK1104 cannot open file 'cinder-v140_d.lib' Visual Studio Enterprise 2015

### ISSUE THREAD

**Issue by YuyQuan** [cinder/Cinder#1409]
Fresh samples and skeleton project(s) outputs [title] error.
Pointed library directory right to the lib but continues neglect that it exists.

**Comment by richardeakin** [comment]
Did you build cinder lib with the v140 toolset? Also depends on whether you are building for x64 or x86.

**Comment by YuyQuan** [comment]
The problem must of came from me not grabbing the repository recursively
`git clone --recursive https://github.com/cinder/Cinder.git`
Seemed to have fixed it when I tried fresh a second time. Sorry for the inconvenience!

Oh, and both x86 and x64 work, too.
