### ISSUE TITLE
The syntax of vk_layer_settings.txt is updated.

### ISSUE THREAD

**Issue by vinjn** [cinder/Cinder#1414]
New syntax -> https://github.com/LunarG/VulkanTools/blob/master/layersvt/vk_layer_settings.txt

**Comment by chaoticbob** [comment]
Do you know which version of the SDK this started with?

**Comment by vinjn** [comment]
Since sdk-1.0.5

**Comment by chaoticbob** [comment]
Samples have been updated now.
