### ISSUE TITLE
glfw: key chars always come through upper case

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1441]
Currently keys will always come through as upper case on linux, since the the key callback ([here](b2.com/mill-c-table/s172898?a=501&campaignid=154997229&adgroupid=14729752869&targetid=pla-103151431749&adpos=1o2&creative=55709491509&device=c&matchtype=&network=g&gclid=Cj0KEQiA2b20BRDj4buduIG-y9EBEiQAhgMGFbWfbLByWfqKwkoRmF2m6PmXx34zftmxs3a9MtcMziMaAhGF8P8HAQ) reports the upper case ASCII code even when you type the lower case version. I'm not sure if this is something that has been brought up with the GLFW team.

Hai and I briefly discussed a workaround that would involve detecting if shift is down and if it isn't, then convert the ASCII code and char to the lowercase counterpart. However, I think this would mean we'd be doing the conversion when we shouldn't if caps lock is on. Open to suggestions here.

**Comment by richardeakin** [comment]
I just briefly tried using `glfwSetCharCallback` to see if the characters come through correctly there, and it appears they do. We'd have to add a unicode table lookup but that doesn't seem too bad (or are the first 128 unicode characters the same as ASCII?).

One complication is that it appears to fire after the first `GlfwCallbacks::onKeyboard` callback (the one for app's `keyDown()`), so it would probably require some extra book keeping to sync the two methods, unless there is some other way to get the unicode character.

**Comment by andrewfb** [comment]
Just a quick note to say that indeed the first 128 Unicode code points map 1:1 to ASCII.

**Comment by ryanbartley** [comment]
Where did you guys net out on this? Keep key touches between up and down callbacks? The reason I ask is I'll have some time to night to work this out and want to help resolve this issue.

**Comment by richardeakin** [comment]
This issue is solved with PR #1656 for ASCII chars only. I opened #1661 for 0.9.2 to support unicode.
