### ISSUE TITLE
Visual Studio 2013 crashes as soon as the solution is opened.

### ISSUE THREAD

**Issue by ventusjk** [cinder/Cinder#1459]
I'm not sure if this is a right place to ask or not.

Please excuse me if I'm on the wrong spot.

==================================================================

So, I have recently started to use Cinder since one of my uni assignment requires us to use Cinder Library.

It was okay while I only had Visual Studio 2013 installed on my PC. However, since I installed Visual Studio 2015 as well for Unreal Engine 4.10, Visual Studio 2013 started to crash out instantly when I open solutions.

Side-by-side installation of two versions, 2013 and 2015, worked fine while I did not open any cinder projects (solutions).

Is there any advises that I could get?

Thank you.

**P.S:** I re-installed my OS for like 3 times to test it out.
1. Install VS 2013 -> Run Cinder Project on VS 2013 -> Install VS 2015 -> Run Cinder Project on VS 2013
2. Install VS 2013 -> Install VS 2015 -> Run Cinder Project on VS 2013
3. Install VS 2015 -> Install VS 2013 -> Run Cinder Project on VS 2013

None of them actually worked for me...

**Comment by richardeakin** [comment]
You're seeing Visual Studio itself crash? There's something up with your setup then.. it shouldn't ever crash.

**Comment by chaoticbob** [comment]
What version of Windows are you running?

**Comment by sansumbrella** [comment]
I recently did a clean install of Windows 10 and Visual Studio 2015. Cinder worked out of the box there, so I'm not sure what the issue could be. Could be worth updating your version of Windows if it's not the latest.

**Comment by chaoticbob** [comment]
There is a known issue that when you open a vc2013 project with vc2015 and hit the "Upgrade", it will break the build. This issue isn't consistent and seems to happen on some installs and not others.

**Comment by ventusjk** [comment]
Hi guys,

First of all thank you for all your responses and sorry for late reply.

I have done another clean installation of my OS and in fact installing vs 2013 after vs 2015 actually solved the problem.

So, let me just answer question by question.

@richardeakin
Yes, the visual studio 2013 seems to be crashing itself as soon as I start the solution. Would that be a problem with two different version types? Cause I'm actually using Visual Studio 2013 Ultimate and Visual Studio 2015 Professional. I just installed both of them with default options + visual c++ enabled.

@chaoticbob
I am running windows 10

@sansumbrella
I can't be sure, but I am guessing that it is the problem with vs 2015 professional cause I tried to compile both debug and release with vs 2015 professional and it actually failed :(

**Comment by paulhoux** [comment]
Hi,

I am not sure if Cinder currently supports flawless compilation under toolset v140 (VS2015), but I am certain that toolset v120 (VS2013) always works. Installing VS2013 on your system allows you to also use toolset v120 under VS2015. If you don't upgrade Cinder's project, it should compile. I am using the "Comunnity" version of Visual Studio, so your mileage may differ.

-Paul
