### ISSUE TITLE
Cube in _vulkan_explicit crashed for devices which supports only one graphics queue

### ISSUE THREAD

**Issue by pifuAMD** [cinder/Cinder#1462]
1. Tested using AMD GPU bonaire, this device  supports only one graphics queue, queried using vkGetPhysicalDeviceQueueFamilyProperties.
2. Cube didn't do any check and call vk::Context::createFromExisting() directly.
3. Then in Context::initialize(), mDevice->acquireQueueDescriptor() would fail and mGraphicsQueue remains NULL pointer.
4. Then "const uint32_t graphicsQueueFamilyIndex = mGraphicsQueue->getQueueFamilyIndex();' crashed the app
5. Call stack:
_Program received signal SIGSEGV, Segmentation fault.
0x0000000000b80922 in cinder::vk::Queue::getQueueFamilyIndex (this=0x0) at /shared/tool/vulkan/cinder/Cinder/include/cinder/vk/Queue.h:68
68              uint32_t                getQueueFamilyIndex() const { return mQueueFamilyIndex; }
(gdb) bt
#0  0x0000000000b80922 in cinder::vk::Queue::getQueueFamilyIndex (this=0x0) at /shared/tool/vulkan/cinder/Cinder/include/cinder/vk/Queue.h:68
#1  0x0000000000b7ae03 in cinder::vk::Context::initialize (this=0x22debd0, existingContext=0x2198a80, queueTypes=1) at /shared/tool/vulkan/cinder/Cinder/src/cinder/vk/Context.cpp:184
#2  0x0000000000b7a14e in cinder::vk::Context::Context (this=0x22debd0, existingContext=0x2198a80, queueTypes=1) at /shared/tool/vulkan/cinder/Cinder/src/cinder/vk/Context.cpp:97
#3  0x0000000000b7a82a in cinder::vk::Context::createFromExisting (existingContext=0x2198a80, queueTypes=1) at /shared/tool/vulkan/cinder/Cinder/src/cinder/vk/Context.cpp:116
#4  0x0000000000a59de0 in RotatingCubeApp::setup (this=0x144f0b0) at /shared/tool/vulkan/cinder/Cinder/samples/_vulkan_explicit/Cube/src/CubeApp.cpp:152
#5  0x0000000000a6e723 in cinder::app::AppBase::privateSetup__ (this=0x144f0b0) at /shared/tool/vulkan/cinder/Cinder/src/cinder/app/AppBase.cpp:211
#6  0x0000000000cda7d2 in cinder::app::AppImplLinux::run (this=0x144dca0) at /shared/tool/vulkan/cinder/Cinder/src/cinder/app/linux/AppImplLinuxGlfw.cpp:289
#7  0x0000000000a6d25f in cinder::app::AppLinux::launch (this=0x144f0b0) at /shared/tool/vulkan/cinder/Cinder/src/cinder/app/linux/AppLinux.cpp:48
#8  0x0000000000a6e429 in cinder::app::AppBase::executeLaunch (this=0x144f0b0) at /shared/tool/vulkan/cinder/Cinder/src/cinder/app/AppBase.cpp:187
#9  0x0000000000a5fe69 in cinder::app::AppLinux::main<RotatingCubeApp>(std::shared_ptr<cinder::app::Renderer> const&, char const*, int, char* const*, std::function<void (cinder::app::AppBase::Settings*)> const&) (defaultRenderer=std::shared_ptr (count 3, weak 0) 0x144db00, title=0xf893f5 "RotatingCubeApp", argc=1, argv=0x7fffffffe408, settingsFn=...)
    at /shared/tool/vulkan/cinder/Cinder/include/cinder/app/linux/AppLinux.h:85
#10 0x0000000000a5af5f in main (argc=1, argv=0x7fffffffe408) at /shared/tool/vulkan/cinder/Cinder/samples/_vulkan_explicit/Cube/src/CubeApp.cpp:301_

6. It's valid to expose only one graphics queue (Vulkan spec chapter 4.1: If an implementation exposes any queue family that supports graphics operations, at least one queue family of at least one physical device exposed by the implementation must support both graphics and compute operations.)

**Comment by chaoticbob** [comment]
This demo is explicitly coded to show the use of multiple queues. There is a note in the source code that states that this demo will not work on hardware that do not support more than one queue.
