### ISSUE TITLE
Does not build on OSX 10.7 (Lion) Xcode 4.2.1

### ISSUE THREAD

**Issue by reklis** [cinder/Cinder#147]
Patch here:

https://gist.github.com/1817849

Basically just a couple of flag specifications to force it to use 10.6 llvm+gcc instead of defaults which would be 10.7 and clang.

Also in the patch is an edit to fullbuild.sh to make it a little prettier

**Comment by andrewfb** [comment]
Belated thanks; cleaning up old issues
