### ISSUE TITLE
Fish Tornado flocking pattern issue

### ISSUE THREAD

**Issue by ppuspu** [cinder/Cinder#1479]
On Windows system **Cinder Vulkan Fish Tornado** sample the flocking pattern is not at all getting formed. 

Fishes are not moving ahead and keep waving at fixed position forming a cuboid pattern.
Image [https://pbs.twimg.com/media/Ckwff5PUYAARd85.jpg](url)

Which shader variable could be the culprit ?

**Comment by chaoticbob** [comment]
I don't think that any shader variable is necessarily the culprit. Since the sample has been working, it's possible that some changes to the recent drivers could be affecting it. What hardware and driver version are you using?

**Comment by ppuspu** [comment]
>some changes to the recent drivers could be affecting it
Yes, that could be the issue. But to save the investigation time I am trying to find the potential shader variable that is not getting communicated properly form the CPU to GPU or something and a cube of fishes is getting rendered.
Putting other way how can we deliberately hack the flocking pattern to form a cube as seen ?

**Comment by chaoticbob** [comment]
You can change the source of the shader that controls the simulation to form whatever pattern you wish. Just keep in mind that the simulation will probably be broken once you do this.
