### ISSUE TITLE
Cinder / CMake / iOS / Cross-Compilation

### ISSUE THREAD

**Issue by lucmichalski** [cinder/Cinder#1491]
Hi guys,

hope you are doing all well !

I was wondering if there is any projects related to Cinder allowing to compile Cinder librairies and app with CMake.

The bigger goal would be to use:
- https://github.com/ruslo/hunter
- https://github.com/ruslo/polly
- https://github.com/hunter-packages

It would allow to make easier the cross-compilation of projects (Linux, Mac, Windows, iOS, Android, Raspberry Pi).

Cheers,
Luc Michalski

**Comment by kitschpatrol** [comment]
Hi, have you taken a look at the android_linux fork? Lots of work towards CMake integration is happening there: https://github.com/Cinder/cinder/tree/android_linux

See also the RFC on the forum here:
http://discourse.libcinder.org/t/rfc-cross-platform-cmake-support/102

**Comment by richardeakin** [comment]
Please feel free to give feedback on our approach with cmake on the RFC forum post that @kitschpatrol linked to. We're not planning iOS support at current as it would take quite a bit of work to manage the deployment to device process, however we'd be open to contributions towards this.

**Comment by FelikZ** [comment]
Hunter user here. Would be nice to have it packaged through it.
