### ISSUE TITLE
split string, strange behaviour when separator is a string

### ISSUE THREAD

**Issue by dimitre** [cinder/Cinder#1495]
I'm trying to use a string as a separator, but it seems to be behaving as an array of chars
and it is actually splitting even if the second string isn't contained in the first.
Let me know if I'm missing something
Thank you!

```c++
vector<string> spacers = split( "primeira", "spacer" );
for (auto & s : spacers) {
	cout << s << endl;
}
```
result:
```


im
i


```

**Comment by gaborpapp** [comment]
This is normal behaviour, since each character in the second string is a separator.

**Comment by dimitre** [comment]
ok I understand it is the same behavior as boost::is_any_of. 
Is there any way of using a string as delimiter? thanks

**Comment by gaborpapp** [comment]
Please use the cinder forum, [http://discourse.libcinder.org/](http://discourse.libcinder.org/) for questions instead.

As far as I know there is no built-in method to do this, but you can do it yourself with `find` and `substr` as explained [here](http://stackoverflow.com/questions/14265581/parse-split-a-string-in-c-using-string-delimiter-standard-c).

**Comment by dimitre** [comment]
ok thanks
