### ISSUE TITLE
What is the future of libcinder?

### ISSUE THREAD

**Issue by daixtrose** [cinder/Cinder#1520]
Looking at the contribution timeline it seems libcinder has passed ist zenit already. Is libcinder a dying project or is this just due to ist maturity level?

**Comment by ilzxc** [comment]
https://github.com/Cinder/cinder/tree/android_linux
https://github.com/cinder/Cinder/tree/vulkan

**Comment by daixtrose** [comment]
These links do not reduce my concerns raised [here](https://github.com/cinder/Cinder/graphs/contributors?from=2010-04-18&to=2016-07-25&type=c)

**Comment by andrewfb** [comment]
I can assure you that Cinder is very actively developed, and that a project of its nature will always have variability in the commit count. Dev occurs in individuals' forks and is not reflected until it's merged later; features of any real scale take at least months to develop. Also, I'd politely discourage you from posting questions of a general or conversational nature in any project's formal issues list in the future. It pollutes the developers' mechanism for tracking actual bugs and features. In the case of Cinder, http://discourse.libcinder.org/ is the appropriate place for conversation. I'm closing this issue in the meantime.
