### ISSUE TITLE
"cmake ..; make; make test" does not run unit tests

### ISSUE THREAD

**Issue by dankegel** [cinder/Cinder#1548]
As long as Cinder is going to have a cmake buildsystem, it may as well support building and
running the catch.hpp unit tests in the usual way.

Patch coming...

**Comment by dankegel** [comment]
Here's a start at making 'make test' work as expected:
https://github.com/cinder/Cinder/pull/1550

**Comment by richardeakin** [comment]
Sweet, sounds good, will be looking at this soon.

**Comment by dankegel** [comment]
I'd love to hear whether it works on your platform(s).

**Comment by dankegel** [comment]
"make check" totally runs tests now, thanks!
