### ISSUE TITLE
Unit test issues on Linux

### ISSUE THREAD

**Issue by lucasvickers** [cinder/Cinder#1551]
Working out of current android_linux branch

Audio unit tests are missing `#include <string>`, leading to:
```
RingBuffer.h:119:4: error: ‘memcpy’ is not a member of ‘std’
```

SystemUnit test fails:
```
1: /home/lucas/ctest/test/unit/src/SystemTest.cpp:10: FAILED:
1: due to unexpected exception with message:
1:   Not implemented
```

**Comment by dankegel** [comment]
Does the "Not implemented" happen when you run under a debugger or valgrind?

If running under gdb or valgrind makes it pass, I've seen this, and vaguely suspect c++ abi clashes.

**Comment by lucasvickers** [comment]
I'm just running `make check`.

**Comment by lucasvickers** [comment]
excerpt:

Rand float tests... then
```
1: Time for 100,000,000 randFloats: 103.719
1: System information:
1: 
1: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1: TestMain is a Catch v1.2.1 host application.
1: Run with -? for options
1: 
1: -------------------------------------------------------------------------------
1: System
1: -------------------------------------------------------------------------------
1: /home/lucas/ctest/test/unit/src/SystemTest.cpp:10
1: ...............................................................................
1: 
1: /home/lucas/ctest/test/unit/src/SystemTest.cpp:10: FAILED:
1: due to unexpected exception with message:
1:   Not implemented
1: 
1: ===============================================================================
1: test cases:      6 |      5 passed | 1 failed
1: assertions: 180020 | 180019 passed | 1 failed
1: 
1/1 Test #1: TestMain .........................***Failed  106.48 sec
```

**Comment by dankegel** [comment]
Right, well, try
   gdb Debug/TestMain
   run
and see if it gets past that.  If so, time to swing an ABI chicken over our heads.

**Comment by lucasvickers** [comment]
Get the chickens ready!  Same results from gdb and valgrind.  I'm trying this on Debian Jessie, will check on Ubuntu Xenial when I have a moment.

**Comment by dankegel** [comment]
My problems were on Xenial.

(So gdb and valgrind didn't get you past the problem?  That's good, less magic involved then.)

**Comment by dankegel** [comment]
Hah.  The "not implemented" is expected, I think.  See https://github.com/cinder/Cinder/blob/android_linux/src/cinder/System.cpp#L711

Let's call this one fixed, and open a new one for each individual problem... I've got one already.

**Comment by dankegel** [comment]
Give this a try: https://github.com/cinder/Cinder/pull/1556
After that, only the fft roundtrip test fails here.

**Comment by richardeakin** [comment]
Fft roundtrip issue is at #1263. Haven't had time to look into it yet..

**Comment by richardeakin** [comment]
Going to close this as there are now either issues or pull requests open for remaining problems.
