### ISSUE TITLE
vc2015_winrt build broken

### ISSUE THREAD

**Issue by dafx** [cinder/Cinder#1562]
vc2015_winrt build has been broken for a while. It is caused by TextureFormatParsers.cpp at line 283 and 289.

**Comment by richardeakin** [comment]
I believe that was fixed by https://github.com/cinder/Cinder/commit/3d5512a00a9c1211c1c761642415e2175a6fe8c8, can you verify that, @andrewfb do we still need to get that commit into master branch?

**Comment by andrewfb** [comment]
Sorry about that - I cherry-picked this into _master_.
