### ISSUE TITLE
Linux font with accents

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#1580]
Font rendering does not seem to work with non-ASCII characters in linux.

[test gist](https://gist.github.com/gaborpapp/591775c3b8b7ee1e63fe59923ad0be1f)
[test font](http://fontzone.net/download/digital-sans-ef-medium)

output in osx:
![accents-osx](https://cloud.githubusercontent.com/assets/203532/18623277/913782f4-7e3b-11e6-8872-8a01a941c3b2.png)

output in linux:

![accents-linux](https://cloud.githubusercontent.com/assets/203532/18623311/ef574766-7e3b-11e6-952b-22d253a36b07.png)

**Comment by chaoticbob** [comment]
This looks like it's not able to find the glyph. I can't recall the details of drawstring on Linux atm...but have you tried escaping the accented characters in octal?

**Comment by gaborpapp** [comment]
Thanks for the suggestion. I tried \u0170 and \u0151 instead of the ű and ő, but got the same result.

**Comment by richardeakin** [comment]
What if you try octal or UTF-8, as @andrewfb discusses [here](http://discourse.libcinder.org/t/how-to-correctly-use-unicode-characters-codes/38)?

**Comment by gaborpapp** [comment]
I tried Andrew's example and it works with \x, \u and copying the • into the source file. But unfortunately the results are still wrong with \u171, 0xC5 0xB1, and ű.

**Comment by gaborpapp** [comment]
I checked the font in Font Book on OS X and in Fontmatrix in Linux and the font indeed does not contain these glyphs. What is strange that Cinder draws them in OS X in spite of this for some reason. Sorry for the noise. It does not seem to be a Cinder issue.

**Comment by ryanbartley** [comment]
Most likely osx is creating those glyphs from fallback information, something like what fontconfig does.

**Comment by gaborpapp** [comment]
Thanks for the explanation.

**Comment by chaoticbob** [comment]
@gaborpapp On macOS and Windows, the text components rely on the native font rasterizer. One of the features that these rasterizers have is the ability to do glyph substitution for missing glyphs with whatever font it determines is the closest. I didn't look at the image on my computer until now, but the O with the double accent is shaped differently than the O with the single accent. On Linux we do a fairly straight forward glyph rasterizer with the single font that's loaded at the time. If the glyph is missing, it renders the stroked block. There's probably away to ask FontConfig to assist us with the right information to do substitution. But historically, this has required some user end font.conf editing.

**Comment by gaborpapp** [comment]
Indeed, the accents look different. Thanks for this. Probably the easiest workaround is to add the missing glyphs to the font by hand.
