### ISSUE TITLE
Building OSC related Apps on Linux fails

### ISSUE THREAD

**Issue by patrickFuerst** [cinder/Cinder#1589]
Not sure since when this is happening but when using a fresh clone of the android_linux branch and trying to compile OSC or TUIO samples,  they fail and the linker can't find a reference to an OSC related function. 

Using cmake and OSX this works. 

To reproduce this, use the latest android_linux branch and try to build an OSC sample. 

Building SimpleSender I get: 

> [ 25%] Building CXX object CMakeFiles/OSC.dir/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/src/cinder/osc/Osc.cpp.o
[ 50%] Linking CXX static library libOSC.a
[ 50%] Built target OSC
[ 75%] Building CXX object CMakeFiles/OSC-SimpleSender.dir/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/samples/SimpleSender/src/SimpleSenderApp.cpp.o
[100%] Linking CXX executable Debug/OSC-SimpleSender
CMakeFiles/OSC-SimpleSender.dir/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/samples/SimpleSender/src/SimpleSenderApp.cpp.o: In function `SimpleSenderApp::SimpleSenderApp()':
/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/samples/SimpleSender/src/SimpleSenderApp.cpp:38: undefined reference to `cinder::osc::SenderUdp::SenderUdp(unsigned short, std::string const&, unsigned short, asio::ip::udp const&, asio::io_service&)'
CMakeFiles/OSC-SimpleSender.dir/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/samples/SimpleSender/src/SimpleSenderApp.cpp.o: In function `SimpleSenderApp::mouseMove(cinder::app::MouseEvent)':
/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/samples/SimpleSender/src/SimpleSenderApp.cpp:53: undefined reference to `cinder::osc::Message::Message(std::string const&)'
CMakeFiles/OSC-SimpleSender.dir/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/samples/SimpleSender/src/SimpleSenderApp.cpp.o: In function `SimpleSenderApp::mouseDown(cinder::app::MouseEvent)':
/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/samples/SimpleSender/src/SimpleSenderApp.cpp:62: undefined reference to `cinder::osc::Message::Message(std::string const&)'
CMakeFiles/OSC-SimpleSender.dir/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/samples/SimpleSender/src/SimpleSenderApp.cpp.o: In function `SimpleSenderApp::mouseUp(cinder::app::MouseEvent)':
/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/samples/SimpleSender/src/SimpleSenderApp.cpp:76: undefined reference to `cinder::osc::Message::Message(std::string const&)'
libOSC.a(Osc.cpp.o): In function `cinder::osc::Message::ExcIndexOutOfBounds::ExcIndexOutOfBounds(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)':
/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/src/cinder/osc/Osc.h:352: undefined reference to `cinder::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libOSC.a(Osc.cpp.o): In function `cinder::osc::Message::ExcNonConvertible::ExcNonConvertible(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cinder::osc::ArgType, cinder::osc::ArgType)':
/home/patrick/DEV/Cindertest/Cinder/blocks/OSC/src/cinder/osc/Osc.h:362: undefined reference to `cinder::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/OSC-SimpleSender.dir/build.make:117: recipe for target 'Debug/OSC-SimpleSender' failed
make[2]: *** [Debug/OSC-SimpleSender] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/OSC-SimpleSender.dir/all' failed
make[1]: *** [CMakeFiles/OSC-SimpleSender.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ryanbartley** [comment]
I think the problem is that the block needs to privately link to cinder for that definition. Try adding this to the OSCConfig.cmake
```
if( NOT TARGET cinder )
	include( "${CINDER_PATH}/proj/cmake/configure.cmake" )
	find_package( cinder REQUIRED PATHS
		"${CINDER_PATH}/${CINDER_LIB_DIRECTORY}"
		"$ENV{CINDER_PATH}/${CINDER_LIB_DIRECTORY}" )
endif()
target_link_libraries( OSC  PRIVATE cinder )
```
after the include functions.

**Comment by patrickFuerst** [comment]
Hey Ryan, 

thanks for the quick response. 
This solved the problem. I also changed it for TUIO block and fixed a small typo error in TuioListener example. See PR #1592
