### ISSUE TITLE
Format speicifier error

### ISSUE THREAD

**Issue by MikeGitb** [cinder/Cinder#1599]
When building the master branch of cinder with VS2015 U3 for x64 you get a ton of warnings, mostly about possibly loss of data. I haven't had time to sift through all of them, but one particular message that cought my eyes is this:

> 1>..\src\videoInput\videoInput.cpp(367): warning C4477: 'printf' : format string '%s' requires an argument of type 'char *', but variadic argument 1 has type 'WCHAR *'
1>  ..\src\videoInput\videoInput.cpp(367): note: consider using '%ls' in the format string
1>  ..\src\videoInput\videoInput.cpp(367): note: consider using '%lls' in the format string
1>  ..\src\videoInput\videoInput.cpp(367): note: consider using '%Ls' in the format string
1>  ..\src\videoInput\videoInput.cpp(367): note: consider using '%ws' in the format string

relating to the following piece of code

	WCHAR buffer[255];

        //....

	if(verbose)printf("SETUP: removing filter %S...\n", buffer);
	hr = pGraph->RemoveFilter(pFilter);
	if (FAILED(hr)) { if(verbose)printf("SETUP: pGraph->RemoveFilter() failed. \n"); return; }
	if(verbose)printf("SETUP: filter removed %s  \n",buffer); //<- warning here

I'm not familiar with the particularities of printf format specifiers in combination with wide strings, so I'm not sure what the best speciefer to put there is (capital `%S` seems to work too 3 lines above) or I would have offered a PR, but it seems like something that someone with a little experience could fix in a few seconds.

**Comment by richardeakin** [comment]
I think PRs around cleaning up some warnings would be most welcome if you find the time.

**Comment by MikeGitb** [comment]
@richardeakin: I'll see if I find any warnings, I can fix confidentially. Is there some CI and/or testsuite I can test my patches against? I don't have VS2013 or XCode.

**Comment by richardeakin** [comment]
Thanks! We have started moving to unit tests (you can find the suite [here](https://github.com/cinder/Cinder/tree/master/test/unit)) but they aren't extensive. Up until now we've been testing with existing samples, or something in the test folder (sometimes a bit messy..).

**Comment by MikeGitb** [comment]
As I'm new to this library (and Github in general): Those fixes will most likely span multipe different and otherwise unrelated files. Is it prefered to offer such refactorings as multiple small PRs (e.g. one per module and/or error type) or rather as one big one (with multiple commits)?

**Comment by richardeakin** [comment]
Your PR was good! I think keeping things focused is good but we are also all working people, making a PR for every little thing can be time consuming. Most importantly, keeping the commits separated, as you did, so for example a bugfix is separate than formatting or refactoring, makes it easier to interpret and get merged.

**Comment by MikeGitb** [comment]
OK, I'll try to keep the signal-to-noise-ratio low ;)

**Comment by richardeakin** [comment]
Great - btw what I meant by that was that grouping that stuff into a single PR makes sense sometimes from a time perspective, we definitely appreciate code cleanup and refactoring, not just bug fixes and features.
