### ISSUE TITLE
Android BasicApp build fails on OS X

### ISSUE THREAD

**Issue by eighteight** [cinder/Cinder#1601]
Error:(23, 0) Could not find method android() for arguments [build_a4up170molm66fbhtep6zmawl$_run_closure2@ac0a8d7] on root project 'BasicApp' of type org.gradle.api.Project.
<a href="openFile:/Users/eight/repos/Cinder-Android/samples/BasicApp/androidstudio/BasicApp/build.gradle">Open File</a>

All information about setup is displayed [here](http://discourse.libcinder.org/t/getting-started-with-android-linux-branch-basicapp-does-not-build-on-osx-10-12/312).

**Comment by richardeakin** [comment]
Wondering, have you tried with the change sin PR #1594? This brings the android cmake stuff in alignment with the other platforms and will get merged soon, would be great to hear what your experiences are with it.

**Comment by eighteight** [comment]
I pulled this PR #1594 and got the same error:
```
Executing tasks: [clean]

Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/eight/repos/Cinder-Android/samples/BasicApp/androidstudio/BasicApp/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating root project 'BasicApp'.
> Could not find method android() for arguments [build_a4up170molm66fbhtep6zmawl$_run_closure2@5738adf0] on root project 'BasicApp' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.514 secs
```

**Comment by eighteight** [comment]
Closing, since it works after the latest pull
