### ISSUE TITLE
Review / clean up android related code in cross-platform files

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1602]
Now that android (in android_linux branch) is nearing merge time and its scope is much more refined, its a good time to review files like AppBase.cpp and see if things such as [this](https://github.com/cinder/Cinder/blob/6bff9759d81126d80a2992199a6f6945ccdf5740/src/cinder/app/AppBase.cpp#L30-L59) are necessary.

I also think we can avoid the double `AppBase::Settings` constructors ([here](https://github.com/cinder/Cinder/blob/6bff9759d81126d80a2992199a6f6945ccdf5740/src/cinder/app/AppBase.cpp#L97-L107)) for android, possibly by moving that to `AppAndroid::Settings`.

**Comment by ufidstudios-ch** [comment]
What's the status of this branch? Is there a newer fork or has this been merged, or has it fallen behind?

**Comment by ufidstudios-ch** [comment]
Generally, replacing GNU is favor of clang is pretty much the case across the board at this stage.

**Comment by richardeakin** [comment]
Thanks for asking! Sorry, this issue is really outdated and if there are any android specific refactorings that should take place, I think we should open new issues.
