### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by MikeGitb** [cinder/Cinder#1603]
What is cinder's overall policy regarding (internal) thread-safety?

Usually, I try to follow the guideline, that constant member functions and free functions should not introduce any dataraces. That is probably not possible with anything using opengl API (I've never used it, so this is just a guess), but even the rand utility functions like `cinder::randFloat()` can not be used in multiple threads at the same time, because they use the same random number generator object internally. I find that behavior somwhat suprising, but I can't tell, if this is a bug or by design.

**Comment by richardeakin** [comment]
I think it is not a question we could answer in a general case. To take your example with `Rand`, you could create and use an instance of Rand in your thread, but using the global Rand instance might cause you problems. This isn't usually how it is used however, and we wouldn't want to make people pay for the extra cause of thread synchronization when they won't typically need it. You could also easily create a thread-safe rand generator with what's there (basically a wrapper around Rand with a mutex). On the other had, many of the things in cinder::gl and cinder::audio have to do with multiple threads, so there are well-known policies around those things.

I'm going to close this as it isn't an issue per se, please feel free to start a discussion on the [forum](http://discourse.libcinder.org/) where I'm sure something like this could get much more attention.
