### ISSUE TITLE
Add continuous integration 

### ISSUE THREAD

**Issue by MikeGitb** [cinder/Cinder#1611]
As the title says: Please consider adding support for CI. For open source projects this is usually free and a basic configuration is set up in just a few minutes (at least when you already know how to build from the command line).

Especially for code that is supposed to compile and work on multiple different platforms and compiler versions, I think it is very helpful if the developer has a simple way to check that a change that works well on the local machine doesn't break the program on a different platform.

Of course there are limits on how far you can automate testing of a GUI framework on a console based infrastructure, but you get at least some feedback.

**Comment by richardeakin** [comment]
Thanks for opening this. We've been actively looking into CI using both travis for POSIX and appveyor for Windows.  The POSIX part depends on work done in the android_linux branch, which will soon end up in master / 0.9.1 release.

It would however be nice if we could find one solution that worked across all platforms, but unfortunately I don't think there is one that will also provide us machines (even if virtual) to run the builds on.  Still, open to suggestions.

**Comment by MikeGitb** [comment]
I also don't believe there is a free CI service that supports both POSIX and Windows and I haven't checked about android, but setting up Travis and appveyor for the master branch's Mac and non-winrt windows version took me only a couple of minutes each so I think the overhead is acceptable (I didn't try unit tests thought).

**Comment by richardeakin** [comment]
- [X] Travis-CI for Linux and Mac
- [ ] AppVeyor for Windows.

**Comment by richardeakin** [comment]
AppVeyor added with https://github.com/cinder/Cinder/pull/1791, currently in dev_0.9.2 branch and will be merged into master after 0.9.1 release is out.
