### ISSUE TITLE
OS X CMake build files do not link against boost

### ISSUE THREAD

**Issue by vtron** [cinder/Cinder#1631]
Generating a Cinder library project using CMake on OS X fails to add the boost libraries to the linker flags. This happens using make, ninja and Xcode projects.

Everything seems to build fine otherwise, and linking these static libs manually to individual projects results in a running application, so the issue just seems to be with getting those linking flags in there.

**Comment by chaoticbob** [comment]
Can you add what version of XCode you're using?

**Comment by ryanbartley** [comment]
Hey guys, I just tested this out and I'm not seeing the same problem. Here's the steps of my test...

- cloned a fresh repo
- checked out android_linux
- submodule init update etc.
- cmake built cinder using... cmake ..(in root/build dir) 
- built BasicApp with cmake and xcode and both worked no problem

I'm not sure the way to reproduce the problem you found above @vtron.

**Comment by vtron** [comment]
Building against Xcode 8 on OS X Sierra.

Built Cinder as Xcode project with CMake

Open up Xcode project, Boost libraries are not included.

**Comment by vtron** [comment]
Actually I am seeing it in there now under "Other Librarian Flags" in the Cinder target after regenerating the Xcode project. 

Removed project linking and project runs now.

I am using Ryan's fork of Cinder.

Not sure what changed but it seems to be in order now, closing ticket!

**Comment by ryanbartley** [comment]
Just a note, my fork is up to date with android_linux branch.
