### ISSUE TITLE
Update boost

### ISSUE THREAD

**Issue by MikeGitb** [cinder/Cinder#1642]
Because newer is always better... ;)

In al seriousness: Aside from new functionality a new Boost version might provide this would also solve another issue: When compiling with VS2015 U3 I get a ton of messages from boost headers, because they don't recognize the compiler (_"Unknown compiler version - please run the configure tests and report the results"_). The repository Cinder-Boost already provides boost 1.60 so it should be relatively easy to migrate. I don't know about 1.62.

**Comment by ryanbartley** [comment]
I assume you're speaking about the current `master` branch version of Boost. If you need the functionality of Boost 1.60, you should probably switch to the `android_linux` branch of Cinder, which will become master very soon, as the current `master` is set to be released(frozen) within the next week(s). If you want to get rid of that specific warning, I've used [this](http://stackoverflow.com/questions/30760889/unknown-compiler-version-while-compiling-boost-with-msvc-14-0-vs-2015) method in the past.

**Comment by MikeGitb** [comment]
Thanks, I wasn't aware of the upcoming release. Personally I'm using the boost version provided by vcpkg, which seems to work fine with cinder. So this isn't a problem for me, but as I'm currently hunting for warnings anyway and an update seemed like a clean and simple solution, I wanted to mention it.
