### ISSUE TITLE
CameraPersp::mLensShift is uninitialized

### ISSUE THREAD

**Issue by cdwfs** [cinder/Cinder#1662]
None of the CameraPersp constructors initialize the mLensShift member. This can lead to mysterious NaNs in the camera projection matrix.  I'd provide a pull request with a fix, but I'm not sure what safe defaults would be; zero?

**Comment by paulhoux** [comment]
Hi, 

yeah, zeroes would be right, as it would default to no lens shift.

**Comment by cdwfs** [comment]
Ah, you're right. Our local GLM build has implicit vector initialization disabled. Our problem, not yours; sorry! Please disregard.

**Comment by paulhoux** [comment]
Hey @cdwfs , as a matter of fact I am going to reopen this issue because I think this is an interesting debate. I can see Cinder using uninitialized GLM classes in the future as an optimization and we would bump into this issue again. 

Can I ask you to create a PR for this nevertheless? Feel free to add more class members to the initializer list of their constructor if you run into them.

**Comment by richardeakin** [comment]
I responded to that pull request, but is it really an optimization to leave a couple floating point values uninitialized? Please profile beforehand.

As an argument against, the amount of bugs that would be introduced from GLM_FORCE_NO_CTOR_INIT would be huge. It would also mean all matrix types are uninitialized and no longer default to the identity matrix.

**Comment by paulhoux** [comment]
@richardeakin  : see my response to the PR.

**Comment by cdwfs** [comment]
Full disclosure: I'm actually not even using all of Cinder; I just pulled the Camera class out for use in a quick prototype project. I lost an hour or so chasing the bug that was ultimately due to the uninitialized lens shift, and figured it might be worth upstreaming (or at least mentioning). I don't personally feel that the impact on performance or readability is significant either way, but it's not my project. Nor am I particularly interested in participating in a style review for a trivial three-line change. I'm going to withdraw the PR; y'all'nz can sort out amongst yourselves whether you want to make the change or not.

**Comment by paulhoux** [comment]
Fair enough, @cdwfs , it's probably not worth all the fuzz.
