### ISSUE TITLE
CMake Unit Tests attempt to run out of wrong directory

### ISSUE THREAD

**Issue by lucasvickers** [cinder/Cinder#1672]
I am noticing this on OSX and Ubuntu Trusty.
Working out of current ```android_linux``` branch.

The following command runs successfully
```cmake .. -DCINDER_VERBOSE:BOOL=1 -DCMAKE_BUILD_TYPE=Debug -DCINDER_BUILD_TESTS=1 && make -j8```

However, ```make check``` outputs:

**OS X:**
```Unable to find executable: /Cinder/build/Debug/UnitTests.app/Contents/MacOS/UnitTests```
The binary is located in:
```/Cinder/build/Debug/UnitTests/UnitTests.app/Contents/MacOS/UnitTests```

**Trusty:**
```Unable to find executable: /home/lucas/Cinder/build/Debug/UnitTests```
The binary is located in:
```/home/lucas/Cinder/build/Debug/UnitTests/UnitTests```

**Comment by richardeakin** [comment]
Fixed with #1677
