### ISSUE TITLE
optimizations in cinder renderer

### ISSUE THREAD

**Issue by tiagmoraismorgado** [cinder/Cinder#1692]
**Greetings**
I would like to point you all out to **_some interesting possible cinder optimizations_**:
- A) **optimizing cinder to take advantage of Vulkan API** (currently already in progress);
- B) creating bindings of **openframeworks renderer to Khronos SYCL**;
- C) **optimizing cinder to take advantage of algorithms present in rendering engines such as: id tech 2, 3, 4 and 5; unity, unreal engine, and cry engine;**
**_Looking forward, kind regards_**
tiago morais morgado

**Comment by ryanbartley** [comment]
We appreciate the enthusiasm. However, discussions of this nature are best left to the forums...[here](http://discourse.libcinder.org/).

**Comment by richardeakin** [comment]
Yes I also think these would make great discussions on the forum. Concerning vulkan, check out the [vulkan branch](https://github.com/cinder/Cinder/tree/vulkan
) or take a look at [this wiki page](https://github.com/cinder/Cinder/wiki/Cinder-Vulkan). Going to close this issue for now, thanks for the participation.
