### ISSUE TITLE
Incomplete Type error in Utilities, WriteString

### ISSUE THREAD

**Issue by calxdesign** [cinder/Cinder#1694]
https://github.com/cinder/Cinder/blob/f2671877306e2cc1094c2831dfeeb1e7b13b3bb0/src/cinder/Utilities.cpp#L104

Prevents compilation of Master branch

**Comment by MikeGitb** [comment]
Just submitted a patch for it: https://github.com/cinder/Cinder/pull/1693

**Comment by richardeakin** [comment]
#1693, thanks for the report and fix.
