### ISSUE TITLE
Raspberry Pi build not working since commit 8190cc4

### ISSUE THREAD

**Issue by thyrrestrup** [cinder/Cinder#1718]
The addition of GLFW to `PlatformLinux.h/cpp` removes support for Raspberry Pi.

**Comment by richardeakin** [comment]
Related forum post and explanation: http://discourse.libcinder.org/t/errors-building-cinder-on-raspberry-pi-3/193/8

**Comment by thyrrestrup** [comment]
Hi
The issue is with the recent addition of display support for linux desktop.

**Comment by PetrosKataras** [comment]
This should be fixed by #1759 .

**Comment by richardeakin** [comment]
OK, closing, please reopen if more issues come up.
