### ISSUE TITLE
Unable to build Vulkan samples exe

### ISSUE THREAD

**Issue by pandurangkatkar** [cinder/Cinder#1719]
Hi Guys,
Sorry may be it is not a issue , but as i am very new to it, so i found this as relevent place for my doubt.

I tried to build cinder but it do not build .exe , instead it builds lib file named as cinder-v120.lib
but nothing is built in samples folder.

What am i doing wrong ,Please Help me in building samples. :)
Please let me know if any other information needed.

Thanks in Advance,
Pandurang

**Comment by gaborpapp** [comment]
Open and build the project files in the samples directory. Use the cinder forum for questions like this at http://discourse.libcinder.org/

**Comment by richardeakin** [comment]
And look for the [samples/_vulkan](https://github.com/cinder/Cinder/tree/vulkan/samples/_vulkan) folder.

**Comment by pandurangkatkar** [comment]
Thanks All...
