### ISSUE TITLE
SVG: Apply X/Y values of the viewbox to all the vertexes

### ISSUE THREAD

**Issue by rsodre** [cinder/Cinder#172]
The X / Y values of the viewbox is an offset that should be applied to every vertex read from the file.

To test it, edit the artboard on AI, change the X / Y to something else and the parse the file.
See that the whole drawing will be shifted.

I will not try to solve it, because there's so many ways to do it.

Apply it to the mTransform?

Add to every vertex? I prefer this because if I query the objects, the actual vertexes will have the right values.

**Comment by andrewfb** [comment]
I believe this is working properly in master.
