### ISSUE TITLE
64 Bit release version of vulkan Samples are not launching..

### ISSUE THREAD

**Issue by pandurangkatkar** [cinder/Cinder#1727]
I have notice x64 bit release vulkan samples are not launching on some Intel and AMD Processor (May be low End) But on same system Vulkan Sample Debug version will launch without any issue , There is no issue with 32 bit Release and Debug Version Both will launch without any issue 

Is this expected ?

In short 64 bit release version of vulkan sample are not launching on some system 

Note : I have installed all dependency like vc redist version 2005 to 2015

**Comment by pandurangkatkar** [comment]
Please someone Have look into this issue...  Please let me know if need any information regarding this.

**Comment by vinjn** [comment]
What errors do you meet?

**Comment by pandurangkatkar** [comment]
Sample is crashing on  launch 
![cinder](https://user-images.githubusercontent.com/17390527/31988929-5912abb2-b98e-11e7-8abd-f638c7f96627.JPG)
Attached Screenshot and Event Log

**Comment by pandurangkatkar** [comment]
[

](url)
