### ISSUE TITLE
android_linux branch no longer upstream but still in documentation

### ISSUE THREAD

**Issue by Cynlic** [cinder/Cinder#1749]
Howdy all, 

I'm attempting to build Cinder on Ubuntu 16.04, and it seems that attempting to clone the`android_linux` branch, which is still mentioned in the wiki, results in an error: `fatal: Remote branch android_linux not found in upstream origin`

Using the regular git instructions builds fine, so the wiki seems out of date now, but I didn't want to edit it in case my understanding of how the linux build works was incomplete.

**Comment by drewish** [comment]
I believe that was merged to master. Can you provide a link to the documentation you're referring to?

**Comment by Cynlic** [comment]
As of yet there is no 16.04 page in the wiki, so I used the instructions here:
https://github.com/cinder/Cinder/wiki/Cinder-for-Linux-%7C-Ubuntu-15.X-on-x86_64 
https://github.com/cinder/Cinder/wiki/Cinder-for-Linux-%7C-Ubuntu-14.04

I'm fairly certain that the `android_linux` branch is referenced in all of the Ubuntu wiki docs though.

**Comment by PetrosKataras** [comment]
The work of the `android_linux` branch has been merged into `master`. I updated the respective wiki pages to reflect that. 

The instructions for 15.X are still valid for Ubuntu 16.04 without any changes.
