### ISSUE TITLE
key press bug on Linux?

### ISSUE THREAD

**Issue by blm81** [cinder/Cinder#1752]
I'm developing a Cinder app on Ubuntu 16.04.  I'm using a fork of Cinder that is currently at commit 28c96e00b5013378591a00422ff5daa3d7f0543c which is prior to the merge of the android_linux branch.  I'm noticing that for a very quick key press (on a qwerty keyboard) I get one keyDown and one keyUp event, as expected.  However, when I hold down the key for a second or more, then release it, I get a second keyDown and keyUp event (total of 2 each for keyDown/Up for one press).  Has this issue ever been reported before?  I noticed it working with the CinderImGui block.

**Comment by gaborpapp** [comment]
I think this is normal behavior and called key repeat. If you don't like this, you can disable it, but it's not related to Cinder, more like an OS thing.

**Comment by blakelymcconnell** [comment]
I don't think key repeat is the issue.  If it were, I would expect to see the keyDown handler fired repeatedly while the key is down.  Instead, it is fired, one extra time, after the key is released (followed by another keyUp).  I'm interested to know if anyone can repro this issue.
