### ISSUE TITLE
Making GLFW optional for macOS and Windows

### ISSUE THREAD

**Issue by IntellectualKitty** [cinder/Cinder#1775]
This is a comment from @richardeakin on commit [5872d92](https://github.com/cinder/Cinder/commit/5872d92b6989a968aff6dc384b98e5552182b8ab):

> We've discussed making it optional to use GLFW on Windows and Mac, while still also providing native implementations. It'd likely be a cmake option. AFAIK no one is currently working on this, though, and it would require a bit of macro refactoring but not insurmountable. You can open a new issue to discuss this.

GLFW is currently being used to provide platform support on Linux, but since GLFW includes builtin joystick handling it would be nice to be able to use GLFW on macOS and Windows as well.

**Comment by vinjn** [comment]
+1
