### ISSUE TITLE
Cmake asset folders on windows 

### ISSUE THREAD

**Issue by m1keall1son** [cinder/Cinder#1776]
symlink creation fails on windows, so without explicitly copying the files via CINDER_COPY_ASSETS, assets wont be found.

symlinks should be created on windows as: 

`cmd.exe /c mklink /D ${link} ${target}`

but it requires the building terminal be run as Administrator since symlink creation is protected by defuault.  

alternatively it could use `runas.exe`

`runas.exe /user:administrator /savecred "cmd.exe /c mklink /D ${link} ${target}"`

which will pause the project generation and prompt the user for a password, but I've not been able to get this to work even with the correct password...sigh...

cmake should put out a warning when the symlink fails on windows and if the error is because of privileges, then put out another warning to re-run the cmake command as Administrator

**Comment by richardeakin** [comment]
Fixed with #1780.
