### ISSUE TITLE
cmake ignores LIBCRT and LIBCPRT in release 

### ISSUE THREAD

**Issue by m1keall1son** [cinder/Cinder#1778]
Comparing the provided sample projects to a cmake generated project in visual studio 2015, i see that the LIBCRT.lib and LIBCPRT.lib are specifically ignored in the generated version, causing the Release build to fail to link to the runtime library and all hell to break loose.

```cmake
#platform_msw.cmake
# Static library flags
    set( CINDER_STATIC_LIBS_FLAGS_DEBUG     "/NODEFAULTLIB:LIBCMT /NODEFAULTLIB:LIBCPMT" )
    set( CINDER_STATIC_LIBS_FLAGS_RELEASE   "/NODEFAULTLIB:LIBCMT /NODEFAULTLIB:LIBCPMT" )
```

removing these ignores from the release properties restore balance to the universe.

**Comment by m1keall1son** [comment]
Also it appears here:

```cmake
#cinderMakeApp.cmake
# Ignore Specific Default Libraries
	if( MSVC )
		set_target_properties( ${ARG_APP_NAME} PROPERTIES LINK_FLAGS "/NODEFAULTLIB:LIBCMT /NODEFAULTLIB:LIBCPMT" )
	endif()
```

**Comment by richardeakin** [comment]
Fixed in dev_0.9.2 branch, see comment in #1779 for details.
