### ISSUE TITLE
Update cairo on windows for v140

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#1784]
We've moved from v120 to v140 with #1770 and #1783, as such we'll need to rebuild cairo binaries for v140.

**Comment by MikeGitb** [comment]
Can you clarify? Does this issue still apply? I don't see cairo binaries anywhere in the repository.

**Comment by richardeakin** [comment]
Fixed in https://github.com/cinder/Cinder/commit/1acbc52b09442d8f9de194b942e7e0e328bb9a30
