### ISSUE TITLE
Nonexisting libraries cmake file

### ISSUE THREAD

**Issue by MikeGitb** [cinder/Cinder#1789]
Not sure if this is on your radar already, but the `platform_msw.cmake` file of the  dev_0.9.2 branch refers to non-existing library files:

- There is a globbing expression that tires to detect the boost libraries that have been removed by  #1786
- The file also adds a dependency to zlib.lib which is od, because the file doe not exist and my understanding was that cinder is integrating zlib by directly adding the source files in zlib-1.2.8

**Comment by richardeakin** [comment]
Thanks for catching this, fixed in cb579894e71a23145658d3b4605d40c352d06972.

Anyone who's interested, please see #1801 for remaining cmake + VS issues.
