### ISSUE TITLE
BONE_INDEX and BONE_WEIGHT are missing in TriMesh

### ISSUE THREAD

**Issue by IntellectualKitty** [cinder/Cinder#1797]
Can I take from their preliminary implementation in `uint32_t TriMesh::toMask( geom::Attrib attrib )` and `geom::Attrib TriMesh::fromMask( uint32_t attrib )` as well as the comment on line number 1233 (`// TODO: bone index and weight`) of TriMesh.cpp that support is planned for BONE_INDEX and BONE_WEIGHT?

While it is possible to work this by using `VboMesh` (and its `VboMeshSource` counterpart) instead, it's not as desirable since `VboMesh` doesn't directly inherit from `geom::Source`.

**Comment by andrewfb** [comment]
Yes - it's definitely planned - mostly delayed until we have a more thorough Assimp / FBX / glTF integration to properly exercise it. The larger questions around a hypothetical `ci::Skeleton` are more philosophical and difficult to answer, but `TriMesh` support for skinning should be possible.

**Comment by IntellectualKitty** [comment]
@andrewfb do you also plan to support the CUSTOM_* attributes as well?  I'd like to use them to bake in multiple, non-overlapping local light sources so that I don't have to used deferred shading.
