### ISSUE TITLE
linux segmentation fault

### ISSUE THREAD

**Issue by colinbouvry** [cinder/Cinder#1799]
Hello,
I try to launch cinder examples but with all examples I have
Segmentation fault (core dumped)

glxinfo | grep OpenGL :

> OpenGL vendor string: NVIDIA Corporation
> OpenGL renderer string: GeForce GTX 960M/PCIe/SSE2
> OpenGL core profile version string: 4.5.0 NVIDIA 375.39
> OpenGL core profile shading language version string: 4.50 NVIDIA
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: 4.5.0 NVIDIA 375.39
> OpenGL shading language version string: 4.50 NVIDIA
> OpenGL context flags: (none)
> OpenGL profile mask: (none)
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 375.39
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
> OpenGL ES profile extensions:

I followed tuto !
I tested with clamp and gcc
I tested with cmake-3.7.2 and older.

I am under elementary loki OS with ubuntu 16.04 !
I tried only in ogl mode.

**Comment by andrewfb** [comment]
Hi - are you able to capture a backtrace with gdb?

**Comment by PetrosKataras** [comment]
This is most probably due to different versions of boost includes ( system installed and Cinder provided one ) being mixed up somehow. Try to see if the steps described in [this forum thread](http://discourse.libcinder.org/t/linker-errors-mongodb-cxx-driver-on-linux/504/9) solve the issue for you.

**Comment by colinbouvry** [comment]
Whahoo !
It works perfect !
I'm exiting to use libcinder under linux.

I just recompile cinder like this :
`cmake .. -DCINDER_BOOST_USE_SYSTEM=1`

Thanks Petros

:+1:
