### ISSUE TITLE
Anim<T>::operator const T& is a potential performance hazard

### ISSUE THREAD

**Issue by lithium-snepo** [cinder/Cinder#1806]
I just ran into an issue where not using the call operator on an `Anim<T>` brought my application to a complete halt (Literally the difference between starting to lag at 5000 particles before and 100,000 particles after the fix) The Pertinent information is:

```cpp
struct Particle
{
    vec3        Position;
    Anim<float> Size;
}

void App::update ( )
{
    auto m = _positionData->mapAttrib4f( geom::POSITION );
    
    for ( auto& p : _particles )
    {
        *m++ = vec4 ( f.Position, f.Size );
        // *m++ = vec4 ( f.Position, f.Size() );
        // --------------------------------^ Performance problems, be gone!
    }
    
    m.unmap();
}
```

I suppose this could just as easily be considered poor programming on my side by not correctly managing the copy semantics / lifetimes of my objects, but i feel like it's a very simple mistake to make in what is fairly idiomatic usage of `Anim<T>`, similar to the whole `glm::length(vec)` vs `vec.length()` issue when glm was first introduced.

**Comment by andrewfb** [comment]
Does this make sense to you? I haven't dug into it yet, but I believe `operator()` and the cast operator are roughly equivalent, or am I missing something? Is it the same behavior in both Debug and Release?

**Comment by lithium-snepo** [comment]
<img width="955" alt="image" src="https://cloud.githubusercontent.com/assets/959050/24686630/7da4e1e2-19f8-11e7-89d1-cefe204603eb.png">
I only profiled in release, but i suspect that would be the best case. If you say that those two are roughly the same, I wonder if this is more to do with the `vec4` constructor? As you can see it's triggering a copy of the `Anim` so a heap of time is spent in its destructor. If that's the case i guess it's outside the scope of cinder.

**Comment by andrewfb** [comment]
Well, it's definitely a bit mysterious to me. [operator() code](https://github.com/cinder/Cinder/blob/master/include/cinder/Tween.h#L337) versus the [cast operator code](https://github.com/cinder/Cinder/blob/master/include/cinder/Tween.h#L340). Seem similar, but clearly _something_ is different. Perhaps the compiler is not inlining one of them?

**Comment by lithium-snepo** [comment]
Just changed the way i constructed the `vec4`, allowing the cast operator to be invoked and this doesn't have the same performance problems, So i guess that the `vec4` constructor is taking a copy of the a `Anim` before attempting to convert it.

```cpp
vec4 v = vec4 ( f.Position, 0 );
v.w = f.Size;
*m++ = v;
```

Sorry to waste your time.

**Comment by andrewfb** [comment]
Well, interesting problem - never seen that before, and not sure I would have suspected the culprit. Will mark this closed though.
