### ISSUE TITLE
VS2015 cannot open file 'cinder.lib'

### ISSUE THREAD

**Issue by arashout** [cinder/Cinder#1820]
Hey I tried following the instructions in the documentation but I can't get the sample programs to run, keep getting:

1>LINK : fatal error LNK1104: cannot open file 'cinder.lib'

One thing to note is that I'm using the v140 build tools instead of the v120.

**Comment by MikeGitb** [comment]
Not sure if I can help you (not one of the maintainers here) but it is usually helpfull, if you can provide a Step-by-Step description of what you did and what Version you are using/how you obtained cinder (git / Download)?

**Comment by andrewfb** [comment]
You'll need to build Cinder `proj\vc2015\cinder.sln` with the same toolset you're building the samples with. Note that if you're not on github _master_ branch then you that will be at `proj\vc2013\cinder.sln`.

**Comment by arashout** [comment]
Hey sorry MikeGitb this is honestly my first time creating an issue. I'll be more specific next time.
I am building the cinder.sln as we speak.

**Comment by arashout** [comment]
Hey Andrewfb, I didn't realize I had to build cinder.sln before running the samples! Problem solved thank you very much
