### ISSUE TITLE
LNK1104 cannot open file 'cinder.lib' on Visual Studio 2017 Community

### ISSUE THREAD

**Issue by KarmicDemon** [cinder/Cinder#1836]
Samples and Tinderbox output title error on build. 
Also grabbed the repository recursively as specified in https://github.com/cinder/Cinder/issues/1409 .

**Comment by simongeilfus** [comment]
Did you build cinder for the same platform and target as the sample you're trying to run? Where is `cinder.lib` located (Ex. `cinder\lib\msw\x86\Debug\v140\cinder.lib`) ?

**Comment by KarmicDemon** [comment]
Ahhhh turns out that was the solution! Thank you.
