### ISSUE TITLE
Issues with Raspberry Pi

### ISSUE THREAD

**Issue by m039** [cinder/Cinder#1844]
I tried Cinder on Raspberry Pi 3 and I've found several bugs or issues which I want to report:

* There is no way to switch to fullscreen mode.
* Height value of TextureFont::measureString is incorrect.
* ~~Sound is very quiet if FilePlayerNode is used.~~

I would also like to ask to add a note about pulseaudio to the [wiki](https://www.libcinder.org/docs/guides/linux-notes/rpi3.html), otherwise it is hard to figure out why audio is not working.

**Comment by richardeakin** [comment]
Concerning `FilePlayerNode`, you're saying the volume is different as to when you use `BufferPlayerNode`? Because the only different between the two is that one is streaming from file, while the other loads the audio into an in-memory buffer. They should sound the same volume before any gain is applied.

**Comment by m039** [comment]
Yes, I also tried BufferPlayerNode and the visible difference with FilePlayerNode was a volume. I could clearly hear BufferPlayerNode, but FilePlayerNode is too quiet. 

After your remark I had a thought that it could be a problem with a sdcard's speed, I'll test it later.

**Comment by m039** [comment]
Sorry, it was my mistake, the volume is the same for both `BufferPlayerNode` and `FilePlayerNode`. I guess the problem with a sound is not related to Cinder.

**Comment by richardeakin** [comment]
I've opened new tickets for these issues, thanks for reporting. I think we can close this and track progress on the individual issues.
