### ISSUE TITLE
FileWatcher.cpp does not compile on Visual Studio 2015

### ISSUE THREAD

**Issue by felixfaire** [cinder/Cinder#1875]
The latest version of Visual Studio 2015 seems to be having issues with the use of std::chrono in FileWatcher.cpp. See post on the forum below.

http://discourse.libcinder.org/t/cinder-master-build-fails-on-windows-due-to-std-chrono-duration-in-filewatcher-cpp/789

**Comment by MikeGitb** [comment]
Can you tell which line in filewatcher.cpp triggers this error?

**Comment by felixfaire** [comment]
I could not see the file line in visual studio (no idea why). It only showed the error in the std file which isnt helpful at all. Im not an advanced VS user though (usually use xcode), so if there is something i'm missing let me know.

**Comment by MikeGitb** [comment]
@felixfaire: You can see the original line in the textual compiler output. Switch to the `output` tab on the bottom. Unfortunately the output can be hard to read sometimes (especially with templates).

I cant reproduce with my VS2017 system, but my guess would be line 402 : `this_thread::sleep_for( chrono::duration<double>( mThreadUpdateInterval ) );` in which case this would be a compiler/standard library deficiency. which version of MSVC are you using exactly?

**Comment by felixfaire** [comment]
Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1

Heres the relevant console output:
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(769): error C2679: binary '+=': no operator found which takes a right-hand operand of type 'const std::chrono::duration<double,std::ratio<1,1>>' (or there is no acceptable conversion) (compiling source file ..\..\src\cinder\FileWatcher.cpp)
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(166): note: could be 'std::chrono::duration<__int64,std::nano> &std::chrono::duration<__int64,std::nano>::operator +=(const std::chrono::duration<__int64,std::nano> &)' (compiling source file ..\..\src\cinder\FileWatcher.cpp)
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(769): note: while trying to match the argument list '(std::chrono::nanoseconds, const std::chrono::duration<double,std::ratio<1,1>>)' (compiling source file ..\..\src\cinder\FileWatcher.cpp)
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thread(152): note: see reference to function template instantiation 'xtime std::_To_xtime<double,std::ratio<1,1>>(const std::chrono::duration<double,std::ratio<1,1>> &)' being compiled (compiling source file ..\..\src\cinder\FileWatcher.cpp)
1>  ..\..\src\cinder\FileWatcher.cpp(402): note: see reference to function template instantiation 'void std::this_thread::sleep_for<double,std::ratio<1,1>>(const std::chrono::duration<double,std::ratio<1,1>> &)' being compiled

Looks like you might be right, though i'm not sure how to fix it.

**Comment by felixfaire** [comment]
Ah, looks like there are some pending VS updates. Hopefully they will fix the issue

**Comment by felixfaire** [comment]
Yup looks like it was a bug in a slightly older version of VS. Apologies

**Comment by MikeGitb** [comment]
No worries - happy to help.
