### ISSUE TITLE
Build instructions out of date

### ISSUE THREAD

**Issue by wdlindmeier** [cinder/Cinder#1884]
The macOS build instructions here no longer work:
https://libcinder.org/docs/guides/git/index.html

There's no longer a fullbuild script and the xcode/cinder.xcodeproj file doesn't open because it's missing a file.

<img width="532" alt="screen shot 2017-08-04 at 3 23 11 pm" src="https://user-images.githubusercontent.com/132988/28989229-df7311a2-7928-11e7-8101-e53c5517406f.png">

**Comment by richardeakin** [comment]
It's now at `proj/xcode/fullbuild.sh`, all project configuration files have been moved into `proj/` folder to tidy up. Docs indeed need to be updated.

**Comment by wdlindmeier** [comment]
Good to know! Glad there's still iOS build support.

**Comment by wdlindmeier** [comment]
To add a little more context, I think the old xcode folder was left in place when I updated the repo with the new proj/xcode path. Not sure why this wasn't moved/deleted locally, but I can see it's not in the repo.
