### ISSUE TITLE
.exr causes ImageIoException on Linux but not Mac

### ISSUE THREAD

**Issue by kylemcdonald** [cinder/Cinder#1900]
I am loading an .exr via `loadImage(loadResource("xyzMap.exr"))`. Here's the file [xyzMap.exr.zip](https://github.com/cinder/Cinder/files/1318862/xyzMap.exr.zip)

On Mac it loads fine, one Linux I get `cinder::ImageIoException` with `unknown image type`.

I compiled the tinyexr test app and tried running `./test_tinyexr xyzMap.exr` and it does not emit any errors, which makes me think this is a bug with Cinder.

I'm using Cinder 0.9.1 on Mac, and the Github ff4781385028d40510d89ca2e4e824b51bb3fb7a on Linux. My Mac is Sierra 10.12.6 and Xcode 8.3.2 on a mid-2014 MacBook Pro. Linux is Debian 9 (Stretch) with clang 3.8.1-24 on an x86_64 architecture.

```c++
#include "cinder/app/App.h"
#include "cinder/app/RendererGl.h"
#include "cinder/gl/gl.h"

using namespace ci;
using namespace ci::app;

class BasicApp : public App {
public:
    void setup() override;
};

void BasicApp::setup() {
    auto img = loadImage(loadResource("xyzMap.exr"));
}

CINDER_APP( BasicApp, RendererGl, prepareSettings )
```

**Comment by gaborpapp** [comment]
Does it help if you call this before loading the image?
```ImageSourceFileTinyExr::registerSelf();```

**Comment by kylemcdonald** [comment]
That fixes it! I added `#include "cinder/ImageFileTinyExr.h"` to the `BasicApp.cpp` and `cinder::ImageSourceFileTinyExr::registerSelf();` before calling `loadImage`.

It feels like a bug in Cinder that this isn't the same across platforms, but if this is just user error please let me know and close the issue :)

I also started looking into whether it was something about the version of tinyexr, which has changed in the last two years since it was added to Cinder. But the API has changed a bit and I didn't get very far in updating it to the latest code.

**Comment by richardeakin** [comment]
Ah yep, looks like we forgot to register for .exr types, should work by default with #1902. I didn't run the code locally so I'll wait for the unit tests to build / pass before merging.

We should try to keep our copy of tinyexr as up to date as possible, but yea if there are API changes it might take a closer examination than just popping in the new version. Looks like there are some fixes around security issues, though, so seems worthwhile.
