### ISSUE TITLE
asio/detail/atomic_count.hpp missing

### ISSUE THREAD

**Issue by kino-dome** [cinder/Cinder#1922]
Hi, I'm trying to build the [TcpServer](https://github.com/BanTheRewind/Cinder-Asio/tree/master/samples/TcpServer) example from the Cinder-Asio block and it errors about not finding "asio/detail/atomic_count.hpp". I checked and it's not in Cinder's version of Asio. Is there a fix for this? Or something from the block is behind the current master branch that causes this.

Thanks a lot!

EDIT: I should say that I'm on Visual Studio 2015. I also checked and the missing atomic_count trails go back to Cinder's boost itself.

**Comment by kino-dome** [comment]
I'm very sorry for the false alarm. I don't why but I didn't have the atomic_count.hpp in asio/detail. I placed it and now the project is building fine.

**Comment by simongeilfus** [comment]
In my experience this is Visual Studio Intellisense / Preprocessor freaking out. 

Here's a screenshot of what it looks like for the project I'm currently working on:   
![image](https://user-images.githubusercontent.com/241098/32187025-1f021bd4-bd7a-11e7-83b3-01a92439d211.png)

As you can see VS reports 3 errors while at the same time reporting that the project was built properly. I would say that you can safely ignore this - and you shouldn't need to add `atomic_count.hpp`.  

My bet is that this is related to some include order that makes `boost/config.hpp` signals a false flag to Intellisense.

**Comment by kino-dome** [comment]
I'm also getting the exact same errors but didn't report since I saw the app is running fine (and wanted to be sure this time before I make a wrong report). Thanks Simon for the assurance that these are simply Intellisense freakouts.
