### ISSUE TITLE
Surface's Channel returns true for isPlanar() 

### ISSUE THREAD

**Issue by kino-dome** [cinder/Cinder#1949]
Hi! I'm in the process of adding some missing functions to the ip namespace. While studying the source I found that for functions like [flipVertical()](https://github.com/cinder/Cinder/blob/6d78f8e88f5d407eb02a5feb4c6a1352596b98fc/src/cinder/ip/Flip.cpp#L155), isPlanar() is called to determine how to process the channel. In Channel.h [it](https://github.com/cinder/Cinder/blob/6d78f8e88f5d407eb02a5feb4c6a1352596b98fc/include/cinder/Channel.h#L101) mentions that isPlanar is false when a Channel is part of an Surface. 
This all sounds right but this code returns true for isPlanar():
```C
mSurface = loadImage(loadAsset("test.jpg"));
mSurfChannel = mSurface.getChannelGreen();
console()<<mSurfChannel.isPlanar()<<endl;
```
Am I missing something or is something wrong here?

Thanks!

**Comment by andrewfb** [comment]
If you step through that code with a debugger I imagine you'll see the assignment of `mSurfChannel` is invoking the copy constructor. This creates a new `Channel` the contents of which are cloned from `mSurface`'s green channel. Note that `getChannelGreen()` returns a reference. If you instead did something like this:
```
...
Channel8u &channel = mSurface.getChannelGreen();
console() << channel.isPlanar();
```
you should see a 0 / false.

**Comment by kino-dome** [comment]
Thanks for the fast reply Andrew and sorry for the bother :)
