### ISSUE TITLE
gl::Texture3d only supports GL_RGB and no alpha

### ISSUE THREAD

**Issue by kino-dome** [cinder/Cinder#1955]
For a project's final optimizations I chose to go with Texture Arrays. Following the project in the test folder, I made my `gl::Texture3dRef` objects only to find out that Alpha is not working. After digging in the source I realized that the two different constructors Texture3d has, both are hardcoded to GL_RGB in this line:
`TextureBase::initParams( format, GL_RGB, GL_UNSIGNED_BYTE );`

Is there a reason for this? Does `GL_TEXTURE_2D_ARRAY` support alpha? If yes can I just change these lines in the src code and rebuild Cinder to make it work? The thing is that I have to deliver the project in 2 days and can't really afford any hiccups.

Cheers and Thanks again for Cinder!

**Comment by kino-dome** [comment]
Just changed the mentioned enum to `GL_RGBA` and rebuilt Cinder. Everything is working properly now and the alpha problem is gone. Judging by the code I thinking since there's no constructor that accepts an ImageSource, there's no way for the constructor to deduct this automatically, so maybe an extra argument in the constructor can help to specify whether alpha is needed or not.

**Comment by kino-dome** [comment]
I can of course make a PR but since problems like these concern the architecture and the "way" of Cinder, I reckon it's best if the core team chime in about this matter.

**Comment by simongeilfus** [comment]
I have a PR pending for this; I'm traveling today but will look into it asap.

**Comment by kino-dome** [comment]
Sounds great Simon, thanks!
