### ISSUE TITLE
[Filesystem MSVC] Update namespace

### ISSUE THREAD

**Issue by MikeGitb** [cinder/Cinder#1959]
As far as I can tell, Visual studio 2017 has removed the std::tr2::sys namespace when compiling in c++17 mode and you get a warning about it in c++14 mode. The recommended way to use the filesystem library is currently to use the `std::experimental::filesystem` namespace (they haven't yet ported it into the std namespace). 
My guess (haven't tested it) is that this namespace is also available in MSVC2015: https://msdn.microsoft.com/de-de/library/hh874694.aspx

I can provide a PR to update this.

**Comment by richardeakin** [comment]
Are you thinking to add in an additional compiler check to cinder/Filesystem.h? I'd say go for it, seems inevitable.

**Comment by MikeGitb** [comment]
No, I'd just replace namespace std::tr1::sys with std:: experimental::filesystem. That should work for VS2015 and 2017. Sometime in the future, one should add a check that enables std::filesystem, but IIRC, there is currently no compiler providing it (afaik gcc8 will)
