### ISSUE TITLE
CamerUI bug, Camera becomes nan

### ISSUE THREAD

**Issue by Ahbee** [cinder/Cinder#1965]
in CameraUI.cpp line 223

`vec3 mU = normalize( cross( mInitialCam.getWorldUp(), mW ) )`

if `mW` is in the same direction as` mInitialCam.getWorldUp()` the camera nans out.

what is the best way to get around this? if the user picks top orientation my camera becomes invalid

**Comment by richardeakin** [comment]
Just seeing this now, but `mU` is coming from `normalize( mInitialCam.getViewDirection() )`, so isn't the only way that is possible is if the inital cam has the same world up vector as view direction? I think that is avoidable on the user end.

**Comment by Ahbee** [comment]
how is that avoidable on the user end? if I i want my scene to have a top down view you say `cam.setViewDirection({0,0,-1})`

**Comment by paulhoux** [comment]
True, but then you also need to specify what is considered to be "up", like this:
```
cam.setViewDirection( { 0, -1, 0 } );
cam.setWorldUp( { 0, 0, -1 } );
```
or in one go:
```
cam.lookAt( vec3( 0, 0, 10 ), vec3( 0, 0, 0 ), vec3( 0, 0, -1 ) );
```
