### ISSUE TITLE
Cmake support for OSC block

### ISSUE THREAD

**Issue by jurcello** [cinder/Cinder#1967]
I tried to use the OSC block with cmake and I got an error which could be fixed by adding the following line to OSC cmake file:

`target_include_directories( OSC PUBLIC "${OSC_SOURCE_PATH}//cinder/osc" )`

Is this ok, or did I do something wrong?

**Comment by brucelane** [comment]
I think the osc path has changed, to cinder/osc/src/osc or something...

**Comment by jurcello** [comment]
That could be the case. So if the following line (7):
`target_include_directories( OSC PUBLIC "${OSC_SOURCE_PATH}" )`
would be replaced by:
`target_include_directories( OSC PUBLIC "${OSC_SOURCE_PATH}/cinder/osc" )`
that would solve the issue right?

I can create a pull request if that's ok.

**Comment by richardeakin** [comment]
Hey, sorry for the late reply - I believe the include path is correctly set by _OSCConfig.cmake_. Could it be that you were trying to do something like:

```
#include "Osc.h"
```

instead of:

```
#include "cinder/osc/Osc.h"
```

? The latter one should work.
