### ISSUE TITLE
Shape2d::iterate() does not visit all points

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#1988]
Assuming `Shape2d::iterate()` should visit all points in all contours, but I'm seeing this:

<img width="482" alt="screen shot 2018-03-17 at 11 36 59 am" src="https://user-images.githubusercontent.com/203532/37554400-0e238c2e-29d8-11e8-82db-c97d28bf62b5.png">

purple circles are points of the path, while the red hollow circles are the result of iteration.

Getting all points:
```c++
for ( auto &c : shape.getContours() )
{
   for ( auto &pt : c.getPoints() )
   {
       gl::drawSolidCircle( pt, 3.0f );
   }
}
```

Using `iterate()`:
```c++
class PathVisitor
{
  public:
    bool operator()( Path2d::SegmentType type,
            const vec2 *points, const vec2 *previousPoint )
    {
        gl::drawStrokedCircle( *points, 5.0f );
        return true;
    }
};

...

PathVisitor pv;
shape.iterate< PathVisitor >( pv );
```

**Comment by andrewfb** [comment]
Hey - in your example usage, `points` is a pointer to some number of `vec2`s which is dependent on the `SegmentType`. So if it's `QUADTO`, the full segment is [`previousPoint`, `points[0]`, `points[1]`]; `points[0]` is the tangent in that example.

**Comment by gaborpapp** [comment]
Thanks Andrew!
