### ISSUE TITLE
Linking current debug build broken on macOS 10.13.16

### ISSUE THREAD

**Issue by ehoefig** [cinder/Cinder#2018]
When using the current libcinder version on macOS, the linker complains:

> Undefined symbols for architecture x86_64:
>   "_z_error", referenced from:
>       _inflate_codes in libcinder.a(libcinder.a-x86_64-master.o)
>   "_z_verbose", referenced from:
>       _inflateInit2_ in libcinder.a(libcinder.a-x86_64-master.o)
>       _inflate in libcinder.a(libcinder.a-x86_64-master.o)
>       _inflateEnd in libcinder.a(libcinder.a-x86_64-master.o)
>       _inflateReset in libcinder.a(libcinder.a-x86_64-master.o)
>       _inflate_blocks_reset in libcinder.a(libcinder.a-x86_64-master.o)
>       _inflate_codes_free in libcinder.a(libcinder.a-x86_64-master.o)
>       _inflate_blocks_new in libcinder.a(libcinder.a-x86_64-master.o)
>       ...
> ld: symbol(s) not found for architecture x86_64

This happens with Xcode 9.4.1 on macOS 10.13.16 using a fresh build of libcinder from the GitHub master branch. It does not happen with a release configuration.

**Solution**
When building the debug version of libcinder, debug information for the _zlib_ library needs to be enabled. This can be done by adding the option **ZLIB_DEBUG=1** under the _Apple LLVM 9.0 - Preprocessing / Preprocessor Macros / Debug_ section (see picture).

<img width="867" alt="screenshot" src="https://user-images.githubusercontent.com/1863729/42961723-ef2a7d5e-8b8f-11e8-9d46-06ee02379e49.png">

**Comment by gaborpapp** [comment]
I've just run into this. The solution above has fixed it. Thanks!

**Comment by mmaylin** [comment]
Fixed my issue, thank you.
OSX 10.13.6 (17G65)
XCode 9.4.1 (9F2000)

**Comment by andrewfb** [comment]
Thanks for this report + fix - should be addressed by  2bc0a74

**Comment by Rob-McKay** [comment]
The same fix needs to be applied to not just the `cinder` build setting but the `cinder_iphone` and the `cinder_iphone_sim`build settings.
