### ISSUE TITLE
Is Cinder still under development/maintenance?

### ISSUE THREAD

**Issue by xarthurx** [cinder/Cinder#2035]
Just a silly question, since I just newly found this wonderful library.

However, it seems that it is no longer under development now. The 0.9.1 is released 17 months ago and there's no sign when 0.9.2 will be released.

The concerns me if I should spend time in this library or just switch to OpenFrameworks.

Thanks.

**Comment by andrewfb** [comment]
Hi - I can definitely confirm Cinder is under active development. I can't speak for all Cinder devs but as for myself, I'm working on rolling in new features for multi-GPU and multithreaded windowing to support multi-screen projects. I would recommend tracking the `master` branch as we are doing less frequent dot releases lately if you're in need of the latest features. I'd also suggest posting general discussion like this to the Discourse forums instead: https://discourse.libcinder.org/
