### ISSUE TITLE
linux build issues w/ Arch Linux

### ISSUE THREAD

**Issue by einsweniger** [cinder/Cinder#2062]
I've wanted to build Cinder, but I encountered trouble.
Both gcc 8.2.1 and clang 7.0.0 fail as [documented in this gist](https://gist.github.com/einsweniger/fb68597ee45ae746c7762f9d090b4848)

I could not figure out what the problem is exactly, but I at least wanted to report it.
I've tried the current head (642dbbd08) and the v0.9.1 release

**Comment by gaborpapp** [comment]
What is your platform? I have just built the latest Cinder with gcc 8.2.1 on Fedora 29 without any problems.

**Comment by einsweniger** [comment]
I'm on Arch

**Comment by einsweniger** [comment]
I've got it "working" by removing the offending re-declarations from `_int_glx_type.h{,pp}` and `_int_glx_exts.h` in `include/glload/`.
since the primary declaration is in `/usr/include/GL/glx.h`, I suspect that my version of mesa (which this file belongs to) differs from yours.
@gaborpapp can you check your mesa version? mine is 18.2.5-1

**Comment by einsweniger** [comment]
I just compared the mesa packages from fedora and arch, both are identical, so it must be something else that is not properly set during the build. beats me.

**Comment by einsweniger** [comment]
I don't quite get what the problem is, I'll stop looking into it any longer. I suspect user error, but I cannot say for sure. I'll just close this. Thank you!
