### ISSUE TITLE
Parameters interface kills performance: 0 FPS

### ISSUE THREAD

**Issue by hyperknot** [cinder/Cinder#207]
Short version:
This: http://pastebin.com/bCiMS1yV should work at full speed, not at 0 FPS. If you comment either the:
- parameters draw
- parameters.addtext
- color change
- push-pull matrix
The bug is not present.

Also, if you start with parameters dialogue hidden, the bug is not present.

In detail here:
http://forum.libcinder.org/#Topic/23286000001340245

**Comment by andrewfb** [comment]
Fixed in more recent versions
