### ISSUE TITLE
Samples failing on MSVC 2017

### ISSUE THREAD

**Issue by silentnox** [cinder/Cinder#2071]
Cinder compiles with no errors, but some sample projects failing on uncaught exeptions when using Visual Studio 2017.
For example CubeMappingApp failing on this line
`		FileWatcher::instance().watch(teapotShaders, [this, teapotShaders](const WatchEvent &event) {
`
with exception cinder::FileWatcherException

**Comment by neverhood311** [comment]
I'm having the same issue. I upgraded the sample to VS2017 (toolset v141). I manually found `cinder.lib` but it's in a `v140` folder so the linker didn't find it.

Would it be better to download the v140 toolset and not upgrade the sample project? Or should I try to rebuild the Cinder library from scratch?

**Comment by MikeGitb** [comment]
FYI: Cinder doesn't support VS2017 any more. I don't remember if that it's also true for the last released version.

**Comment by vinjn** [comment]
We should close this issue.

**Comment by neverhood311** [comment]
@MikeGitb Actually, I downloaded the latest packaged release for Windows (from here: (https://libcinder.org/download)[https://libcinder.org/download]) and it came with VS2015 solutions. Why are the solutions for those releases so old?

**Comment by andrewfb** [comment]
We skipped 2017 in favor of 2019, so if using the latest compiler is key for you I'd recommend you work against the github `master` branch. For users working on long-running projects, we avoid increasing the minimum toolset requirements except at the start of a new release cycle. The packages on the site reflect that last dot release, which indeed do support vc2015. Will close this for now.
