### ISSUE TITLE
Scene center does not match window center

### ISSUE THREAD

**Issue by dgellow** [cinder/Cinder#2081]
Hi there,

Sorry for the unhelpful title. I'm experimenting with Cinder on macOS and face some unexpected and strange coordinates issues I don't really understand.

That's visible even with the simple "hello world" examples from the documentation, or with samples provided with the library. As you can see in the following screenshots, the center of the scene doesn't seem to match the center of the actual window. Any explanation for that behaviour?

I'm using cinder v0.9.1, freshly installed via brew, on the latest macOS version.

## Simple centered circle
From https://libcinder.org/docs/guides/opengl/part1.html#convenience_functions

<img width="961" alt="screenshot 2019-02-13 at 22 07 16" src="https://user-images.githubusercontent.com/2451004/52744742-cc195180-2fdd-11e9-8015-42653874eba1.png">

## Transformations 
From https://libcinder.org/docs/guides/opengl/part1.html#transformations

<img width="962" alt="screenshot 2019-02-13 at 22 08 05" src="https://user-images.githubusercontent.com/2451004/52744787-e5ba9900-2fdd-11e9-8c16-bbe64929c86b.png">

## CubeMapping sample
Mentioned in https://libcinder.org/docs/guides/mac-setup/index.html

<img width="654" alt="screenshot 2019-02-13 at 22 14 58" src="https://user-images.githubusercontent.com/2451004/52744829-fcf98680-2fdd-11e9-945e-f857b17b7691.png">

**Comment by gaborpapp** [comment]
Does the `toPixels` function help?
https://libcinder.org/docs/classcinder_1_1app_1_1_window.html

**Comment by dgellow** [comment]
Newbie question: how should I use it? Should I call this function with the center coordinate as parameter?

So the simple circle example would be:
```
void BasicApp::draw()
{
	gl::clear();
	gl::drawSolidCircle( toPixels(getWindowCenter()), 200 );
}
```

?

I don't have access to my laptop with Cinder installed right now, but I can try this evening.

**Comment by gaborpapp** [comment]
Yes. Probably the source of the issue is that high density display is enabled by default. Take a look at this thread in the old forum: https://forum.libcinder.org/topic/rfc-retina-high-density-display-support
If you have any further questions and it's not about reporting a bug with Cinder, I would suggest that you use the forum instead at https://discourse.libcinder.org/

**Comment by dgellow** [comment]
Hi @gaborpapp. Thank you for taking the time to respond, I tried using `toPixels` and don't see any difference. The thread from the old forum also mentions `enableHighDensityDisplay`, which doesn't seem to exist anymore (I cannot find it in [the reference](https://libcinder.org/docs/reference/index.html)).

> If you have any further questions and it's not about reporting a bug with Cinder, I would suggest that you use the forum instead at https://discourse.libcinder.org/

Thank you for sharing the forum link, I didn't know about it. Though in this case it's not clear to me that the issue is with my use of the library and not an actual bug. But I'm fine with moving the discussion to the forum if you don't think an issue is the good place for this. Feel free to close the ticket if that's the case.

**Comment by gaborpapp** [comment]
check out this forum post about a similar issue: https://discourse.libcinder.org/t/window-issue-on-osx-mojave/1326

**Comment by dgellow** [comment]
Oh, I see!

Enabling the high density display fixed the coordinate system.
```
CINDER_APP( BasicApp, RendererGl,
           []( BasicApp::Settings *settings )
           {
               settings->setHighDensityDisplayEnabled( true );
           } )
```

Thank you a lot for your time 🙏 .

<img width="742" alt="screenshot 2019-02-14 at 23 57 48" src="https://user-images.githubusercontent.com/2451004/52823200-5e8c2480-30b4-11e9-9c03-53de3a0dfcdb.png">
