### ISSUE TITLE
LNK1104 cannot open file 'cinder-v141_d.lib' VS 2017 

### ISSUE THREAD

**Issue by duongtoro00** [cinder/Cinder#2086]
I have clone the source code: https://github.com/neuroprod/NPBOT
modified and run it on VS 2017. Although I built solution Cinder version 0.8.6 and get the file 'cinder-v141_d.lib'. But when put it in the path Additional Dependencies of Properties->Linker->Input
The error is LNK1104 cannot open file 'cinder-v141_d.lib' VS 2017.
Help me, please! Thankyou so much!

**Comment by richardeakin** [comment]
Hi,

Cinder is configured to build using v140 toolset (ships with VS 2015). You can still use VS 2017, but you need to install the toolset for 2015 alongside, or modify cinder.vcxproj to build v141 and rebuild.

Also, 0.8.6 is really, really, really old. You should at least be using v0.9.1, and ideally working from master branch.
