### ISSUE TITLE
compile failed linux

### ISSUE THREAD

**Issue by rdtor** [cinder/Cinder#2088]
In file included from /home/s***/Cinder/include/glload/glx_all.h:6,
                 from /home/s***/Cinder/src/glload/glx_load.c:4:
/home/s***/Cinder/include/glload/_int_glx_type.h:96:3: error: conflicting types for ‘GLXHyperpipeNetworkSGIX’
 } GLXHyperpipeNetworkSGIX;
   ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/cinder.dir/build.make:3147: CMakeFiles/cinder.dir/src/glload/glx_load.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/s***/Cinder/include/glload/glx_all.hpp:6,
                 from /home/s***/Cinder/src/glload/glx_load_cpp.cpp:4:
/home/shank/Cinder/include/glload/_int_glx_type.hpp:96:3: error: conflicting declaration ‘typedef struct GLXHyperpipeNetworkSGIX GLXHyperpipeNetworkSGIX’
 } GLXHyperpipeNetworkSGIX;
   ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/cinder.dir/build.make:3160: CMakeFiles/cinder.dir/src/glload/glx_load_cpp.cpp.o] Error 1
make[2]: Leaving directory '/home/s***/Cinder/build'
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/cinder.dir/all] Error 2
make[1]: Leaving directory '/home/s***/Cinder/build'
make: *** [Makefile:87: all] Error 2

**Comment by gaborpapp** [comment]
try #2070

**Comment by rdtor** [comment]
i Was just looking at that post but i dont seem to understand whats going around i tried to use this https://github.com/whg/Cinder/commit/4a7756aeab15a2e89f38ed313fb87cc37dab087e do i need to change the top 10 lines in int_glx_type.h inside the glload folder?

**Comment by gaborpapp** [comment]
also modify `include/glload/_int_glx_type.hpp`

or you can fetch the pull request in a new branch with git and build that:
```
git fetch origin pull/2070/head:pr2070
```

**Comment by rdtor** [comment]
modifying the _int_glx_type.hpp indeed completed the build process. I am trying to run make install but it doesnt work. what do i need to do after cmake?

**Comment by gaborpapp** [comment]
I don't think there's a make install.
If you'd like to try the library go to the samples folder and build the samples.
for example:
```
cd BasicApp
mkdir build; cd build; cmake ../proj/cmake; make
```
check `proj/cmake/CMakeLists.txt` for example on how to use the lib without installing it.

**Comment by rdtor** [comment]
the terminal throws me this
[100%] Linking CXX executable Debug/BasicApp/BasicApp
/usr/bin/ld: /home/s***/Cinder/lib/linux/x86_64//libboost_system.a(error_code.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /home/s***/Cinder/lib/linux/x86_64//libboost_filesystem.a(operations.o): relocation R_X86_64_32 against symbol `_ZN5boost10filesystem16filesystem_errorD1Ev' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: /home/s***/Cinder/lib/linux/x86_64//libboost_filesystem.a(path.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/BasicApp.dir/build.make:106: Debug/BasicApp/BasicApp] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/BasicApp.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by PetrosKataras** [comment]
This is probably because`boost` is already installed in your system and it clashes with the version that ships with Cinder.

Either merge #2007 or try the suggestions included in the links within the same PR.

**Comment by rdtor** [comment]
Ok i am gonna head over there, thank you
