### ISSUE TITLE
error compiling in netbeans 8.2.

### ISSUE THREAD

**Issue by rdtor** [cinder/Cinder#2089]
Hello I am trying to compile a sample project in netbeans, I included the header files of include folder on the compiler directory and tried  linking the lib folder but there seems to no content in the lib folder and the compler is throwing me all functions error. 

/usr/bin/ld: build/Debug/GNU-Linux/main.o: in function `TriangulationApp::setup()':
/home/s***/NetBeansProjects/CppApplication_2/main.cpp:39: undefined reference to `cinder::params::InterfaceGl::InterfaceGl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, glm::tvec2<int, (glm::precision)0> const&, cinder::ColorAT<float> const&)'
/usr/bin/ld: /home/shank/NetBeansProjects/CppApplication_2/main.cpp:43: undefined reference to `cinder::params::InterfaceGl::addButton(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/s***/NetBeansProjects/CppApplication_2/main.cpp:44: undefined reference to `cinder::params::InterfaceGl::addButton(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/s***/NetBeansProjects/CppApplication_2/main.cpp:52: undefined reference to `cinder::Font::getNames[abi:cxx11](bool)'
/usr/bin/ld: /home/s***/NetBeansProjects/CppApplication_2/main.cpp:53: undefined reference to `cinder::Font::Font(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float)'
/usr/bin/ld: /home/s***/NetBeansProjects/CppApplication_2/main.cpp:54: undefined reference to `cinder::Font::getGlyphChar(char) const'
/usr/bin/ld: /home/s***/NetBeansProjects/CppApplication_2/main.cpp:54: undefined reference to `cinder::Font::getGlyphShape(unsigned int) const'
/usr/bin/ld: build/Debug/GNU-Linux/main.o: in function `TriangulationApp::recalcMesh()':
/home/shank/NetBeansProjects/CppApplication_2/main.cpp:62: undefined reference to `cinder::Triangulator::Triangulator(cinder::Shape2d const&, float)'
/usr/bin/ld: /home/s***/NetBeansProjects/CppApplication_2/main.cpp:62: undefined reference to `cinder::Triangulator::calcMesh(cinder::Triangulator::Winding)'
/usr/bin/ld: /home/s***/NetBeansProjects/CppApplication_2/main.cpp:64: undefined reference to `cinder::gl::VboMesh::create(cinder::geom::Source const&)'
/usr/bin/ld: build/Debug/GNU-Linux/main.o: in function `TriangulationApp::setRandomFont()':
/home/s***/NetBeansProjects/CppApplication_2/main.cpp:71: undefined reference to `cinder::Font::Font(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float)'
/usr/bin/ld: build/Debug/GNU-Linux/main.o: in function `TriangulationApp::setRandomGlyph()':
/home/s***/NetBeansProjects/CppApplication_2/main.cpp:77: undefined reference to `cinder::Font::getNumGlyphs() const'

**Comment by PetrosKataras** [comment]
There is no official Cinder support for NetBeans so I would not really consider this an actual issue and maybe a forum thread would be more appropriate. 

In any case, as you have discovered, Cinder supports CMake so maybe you could try something like what is described in this [SO](https://stackoverflow.com/questions/6608569/can-cmake-and-netbeans-play-nice) thread.

**Comment by rdtor** [comment]
pardon me for posting this here. I am trying to make Cinder work under a developping environment

**Comment by PetrosKataras** [comment]
no worries of course :) don't have experience with NetBeans personally but someone in the forum might have and also it seems that the integration with CMake works nicely so this is what I would give first a try. Good luck!
