### ISSUE TITLE
Build failed cinder example motion basic in linux.

### ISSUE THREAD

**Issue by rdtor** [cinder/Cinder#2097]
/home/s***/Programs/Cinder-linux-boost-use-system-install/samples/MotionBasic/src/MotionBasicApp.cpp:5:10: fatal error: cinder/MotionManager.h: No such file or directory
 #include "cinder/MotionManager.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/MotionBasic.dir/build.make:63: CMakeFiles/MotionBasic.dir/home/shank/Programs/Cinder-linux-boost-use-system-install/samples/MotionBasic/src/MotionBasicApp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/MotionBasic.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by gaborpapp** [comment]
This sample requires the MotionManager block which is for Android and iOS only as far as I know.

**Comment by rdtor** [comment]
oh thanks
