### ISSUE TITLE
Question: How to create a new CinderApp in Linux?

### ISSUE THREAD

**Issue by fei4xu** [cinder/Cinder#2098]
Hi,

I know in the tools folder, there are TinderBox-Mac and TinderBox-Win and I can use them to create project for Win (MS VC).

How do I create a Linux project then? to be more specific, how to create a cmake based CinderApp in Linux?

I see a linux folder
>linux
├── rpi2
│   └── crosscompile
│       └── crosstool_build_config
├── scripts
│   ├── tk1-install-deps
│   └── trusty-install-deps.sh
└── sublime
    └── cinder.sublime-project

Which script should I and how to run it? (I'm not a linux script expert)

**Comment by gaborpapp** [comment]
I suggest that you use the forum for this kind of questions. https://discourse.libcinder.org/
Check out the samples and the documentation/wiki about Linux. To make a new project in Linux copy the `proj/cmake` folder into your new project. It's quite straightforward to modify it.

**Comment by richardeakin** [comment]
Also check out the guides [here](https://libcinder.org/docs/guides/index.html), especially [Cinder + CMake](https://libcinder.org/docs/guides/cmake/cmake.html), and [Cinder on Linux](https://libcinder.org/docs/guides/linux-notes/index.html)
