### ISSUE TITLE
Question : How to apply the library to MFC drawing or Qt widget project?

### ISSUE THREAD

**Issue by libaineu2004** [cinder/Cinder#2102]
### How to apply the library to MFC drawing or Qt widget project?
I want to apply the Cinder library to MFC and Qt projects and draw graphics on their interface.
Can you include related examples in the samples folder?

**Comment by libaineu2004** [comment]
VC++ MFC Project
Qt Creator Project

**Comment by richardeakin** [comment]
I think this is outside of the scope of what this project can explain to you, although I'll say that libcinder is a pretty standard C++ library, so it should be possible to integrate into these other frameworks you're mentioning with a bit of effort.
