### ISSUE TITLE
cmake error about boost on Ubuntu

### ISSUE THREAD

**Issue by fei4xu** [cinder/Cinder#2107]
Hi,

I'm trying to build cinder in Ubuntu 16.
```sh
mkdir build
cd build
cmake ..
```
But I got this error:
>CMake Error at /usr/local/share/cmake-3.14/Modules/FindBoost.cmake:2147 (message):
  Unable to find the requested Boost libraries.

>  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  proj/cmake/platform_linux.cmake:202 (find_package)
  CMakeLists.txt:29 (include)

I checked the platform_linux.cmake, I see
```cmake
# Boost
find_package( Boost 1.54 REQUIRED COMPONENTS system filesystem )
list( APPEND CINDER_LIBS_DEPENDS ${Boost_LIBRARIES} )
list( APPEND CINDER_INCLUDE_SYSTEM_PRIVATE ${Boost_INCLUDE_DIRS} )
```
Then I checked the `platform_msw.cmake`, it does not find  package of boost.

Should I remove the `#Boost` section from `platform_linux.cmake`?

**Comment by fei4xu** [comment]
#2007

**Comment by fei4xu** [comment]
`libboost-filesystem-dev` should be installed as documented at https://libcinder.org/docs/branch/master/guides/linux-notes/ubuntu.html

**Comment by PetrosKataras** [comment]
Boost is still required but now its being pulled from system wide installation under Linux as you discovered with #2007 

Just install `libboost-filesystem-dev` along with the other Linux dependencies and you should be good to go.

**Comment by fei4xu** [comment]
But I afraid to say it's actually a not-so-good idea to use the system installed version of boost. 
I'm having `boost::filesystem::path` segment fault error when running the samples, the fault is at path's free() at this line:

https://github.com/cinder/Cinder/blob/35e555f1c631cc58a7f2bf3ea916ddbdf74ba477/src/cinder/app/Platform.cpp#L150
```c++
for( fs::path curPath = execPath; curPath.has_parent_path() || ( curPath == execPath ); curPath = curPath.parent_path(), ++parentCt ) {
		if( parentCt >= ASSET_SEARCH_DEPTH )
			break;

		const fs::path curAssetDir = curPath / fs::path( "assets" );
		if( fs::exists( curAssetDir ) && fs::is_directory( curAssetDir ) ) {
			addAssetDirectory( curAssetDir );
			break;
		}
	}
```
Someone on the internet says it's related to different cxx flag from binary boost to my code, I tried clang also, same fault.
Then I guess I need to figure out what cxx flags are used during my libboost compiling is used.

**Comment by PetrosKataras** [comment]
What kind of flags are you using? I ve have been using ( other people too ) this since 14.04 without issues.

**Comment by PetrosKataras** [comment]
Just to add also that what you are seeing is exactly the same with what was happening before #2007 was applied if you happened to have both system installed boost and the version that ships with Cinder - Did you by any chance did a recursive clone? i.e Do you have a `Cinder/include/boost` directory present? If yes you would need to delete this and do a fresh clean built. In any case this planned to be added to the README.

**Comment by fei4xu** [comment]
yes, deleting the `Cinder/include/boost` directory worked, thanks!
