### ISSUE TITLE
Build error when set (CMAKE_CXX_STANDARD 11)

### ISSUE THREAD

**Issue by fei4xu** [cinder/Cinder#2108]
Hi,

I have a project on Ubuntu 16 with c++ 11 which uses cinder in the subdirectory so in my toppest CMakelists.txt there is a line :
```cmake
set (CMAKE_CXX_STANDARD 11)
```
I found that if this line is there, cinder will not compile.
```
[build] /home/wave/cinder/include/cinder/linux/FreeTypeUtil.h:38:30: error: expected identifier before numeric constant
[build]  namespace cinder { namespace linux { namespace ftutil {
[build]                               ^
[build] compilation terminated due to -Wfatal-errors.
```
I guess in c++11, `linux` is defined to be a numeric constant?

On Ubuntu, I tried both clang 3.8 and gcc 7.4, same error.

**Comment by gaborpapp** [comment]
Do you need this flag to be set explicitly? I think Cinder already uses c++11 and c++14 on Linux when available. I can see in an empty project that the `-std=c++14` flag is added to it automatically if I compile it with `make VERBOSE=1`

**Comment by fei4xu** [comment]
It's not mandatory to set it explicitly, but it's very strange. During my test, `CMAKE_CXX_STANDARD 11` is related to the macro definition of linux, but I can't find any documentation to prove it.

**Comment by MikeGitb** [comment]
Try `set(CMAKE_CXX_EXTENSIONS OFF)`

IIRC The Problem is that `linux` is a macro that is defined by gcc if language extensions are enabled (which is the default and e.g. also the case if `-std=gnu++11` is specified instead of plain `std=c++11`.

**Comment by MikeGitb** [comment]
https://stackoverflow.com/questions/19210935/why-does-the-c-preprocessor-interpret-the-word-linux-as-the-constant-1/19214007#19214007
