### ISSUE TITLE
Mac OSX: secondary display fix

### ISSUE THREAD

**Issue by circutus** [cinder/Cinder#211]
To enable displaying a window or fullscreen to a secondary display on OSX, two minor changes are needed within the following file,

    /src/cinder/app/AppImplCocoaBasic.mm

(1) In the 'createWindow' method, replace

<pre>
win = [[CinderWindow alloc] initWithContentRect:winRect styleMask:styleMask backing:NSBackingStoreBuffered defer:NO screen:nil];
</pre>

with

<pre>
win = [[CinderWindow alloc] initWithContentRect:winRect styleMask:styleMask backing:NSBackingStoreBuffered defer:NO screen:mDisplay->getNsScreen()];
</pre>

(2) In the 'enterFullScreen' method, replace

<pre>
[cinderView enterFullScreenMode:[NSScreen mainScreen] withOptions:options];
</pre>

with

<pre>
[cinderView enterFullScreenMode:mDisplay->getNsScreen() withOptions:options];
</pre>

Here's a 'prepareSettings' block for testing these changes in a Cinder application,

<pre>
void KinectTableApp::prepareSettings( Settings* settings )
{
    if (ci::Display::getDisplays().size() > 1)
    {
        shared_ptr<Display> secondaryDisplay = ci::Display::getDisplays()[1];
        
        settings->enableSecondaryDisplayBlanking( false );
        settings->setDisplay( secondaryDisplay );
        settings->setFullScreen( true );
    }
}
</pre>

**Comment by andrewfb** [comment]
Closing out old issues; this should all be possible in recent versions.
