### ISSUE TITLE
Updating visual studio support

### ISSUE THREAD

**Issue by cbondurant** [cinder/Cinder#2128]
I am hoping to experiment with the cinder library in the near future, and I have noticed that while not formally supported, there are only minor changes that need to be made in order for cinder to function under Visual Studio 2019. 

Specifically the only component that seems to have issue is `cinder/Filesystem.h` where `cinder::fs` is defined as `std::experimental::filesystem`, which seems to be resolvable either by replacing `<filesystem>` with `<experimental/filesystem>` for support in c++14, which is the default target of VS19. This does also require suppressing a warning, (`#define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING`) as experimental is considered deprecated and will be phased out in favor of simply using `<filesystem>` when targeting c++17.

Unfortunately `<filesystem>` does not define `std::filesystem` for c++14, so if both 14 and 17 are to be supported, some kind of feature detection would need to be added.

Is there any chance that cinder might explicitly support targeting visual studio 19?

**Comment by peterobbin** [comment]
Hey @cbondurant  there are some discussions about Cinder upgrading to vs2019 in the Cinder forum.  Check: 

https://discourse.libcinder.org/t/vs2019-16-3-1-appears-to-remove-std-sys-in-platform-toolset-v142-breaking-cinder-0-9-1-and-how-to-solve-it/1571/5

https://discourse.libcinder.org/t/0-9-2-preparation/1543

**Comment by cbondurant** [comment]
@peterobbin Thank you for the response! 

It seems that development conversations are split between cinder's git and discourse pages. If I wanted to help contribute to the move to 0.9.2 what would be the best place to start getting involved and finding issues that new contributors could help with?

**Comment by peterobbin** [comment]
@cbondurant 
Directly responding to the 0.9.2 preparation post will be a good idea. People respond pretty fast on the forum(that's how I feel). Also check the milestones: https://github.com/cinder/Cinder/milestones . 

Just noticed, it looks like https://github.com/cinder/Cinder/pull/2113 provides a fix to the `std::experimental::filesystem` problem and waiting to be merged . 

Also helping things like https://github.com/cinder/Cinder/issues/2092 could help as well.

**Comment by cbondurant** [comment]
Thank you for the help!
