### ISSUE TITLE
OSC samples with visual studio 2019

### ISSUE THREAD

**Issue by brucelane** [cinder/Cinder#2148]
Hi, 
For instance the OSC SimpleReceiver doesn't compile (x64) with errors about fs or filesystem.
Maybe it has to do with asio

**Comment by kino-dome** [comment]
I think I had the same problem and solved it by forcing Visual Studio to use C++17 using the `/std` option. Check [this](https://www.quora.com/How-can-I-update-the-C-14-to-C-17-in-Visual-Studio) link on how to do it in the GUI.

**Comment by richardeakin** [comment]
Looks like the samples that are shipped in the blocks folder didn't get the update to 2019. I was able to get them working by re-projecting the project files to 2019 / v142 toolset and then setting the compiler language to C++17.

In the process of preparing a PR that will update all the samples in the blocks folder..
