### ISSUE TITLE
Multitude of "Ignoring XLib error" when using InterfaceGl on Linux

### ISSUE THREAD

**Issue by kino-dome** [cinder/Cinder#2160]
I've been experiencing this when using `params::InterfaceGl` on Linux. A flow of XLib errors like `Ignoring Xlib error: error code 3 request code 2` and `Ignoring Xlib error: error code 6 request code 95` fill up my console. Any one else experiencing the same issue?

**Comment by kino-dome** [comment]
Also when I have to instances of `InterfaceGlRef` and I only draw one of them, both are drawn! Which is kind of weird. Could it be that Antweak Bar is messed up in Cinder on Linux. I don't know maybe we should just not pay any attention since the Dear ImGui merge is around the corner. What do you think?

**Comment by gaborpapp** [comment]
check out these previous issues:

https://github.com/cinder/Cinder/issues/420
https://github.com/cinder/Cinder/issues/1865
https://github.com/cinder/Cinder/issues/2014

**Comment by richardeakin** [comment]
Should also note that `params::InterfaceGl` can be considered deprecated and obsolete, Dear Imgui is now shipped in cinder master branch and will be the go-to.

**Comment by kino-dome** [comment]
Thanks guys for the info and previous PR refs. It seems it's best to just forego this and move to Dear Imgui. I for one am happy about this change. Cheers!
