### ISSUE TITLE
Error when building master on OSX with cmake

### ISSUE THREAD

**Issue by MurrayT** [cinder/Cinder#2162]
When compiling on OSX with 
`cmake -DCMAKE_BUILD_TYPE=release && make -j4`

A fatal error is returned 
```
~/repos/Cinder/src/cinder/app/cocoa/AppImplMac.mm:886:29: fatal error: cannot initialize a parameter of type 'id<NSWindowDelegate> _Nullable' with an lvalue of type 'Class'
        [winImpl->mWin setDelegate:self];
                                   ^~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:234:49: note: passing
      argument to parameter 'delegate' here
@property (nullable, weak) id<NSWindowDelegate> delegate;
```

The error occurs inside the `instantiate` method for `WindowImplBasicCocoa`, It seems as though `self` is not set properly to a `WindowBasicImplCocoa`, which inherits from `NSWindowDelegate`, at this point so cannot be assigned to the delegate for the windowimplematation `winImpl`

Changing the delegate to be 
```
[winImpl->mWin setDelegate:winImpl];
```

Causes the error to disappear and cinder compiles and runs samples.

I'm not sure if this is the correct approach, this is the first time I have attempted to fix any Obj-C.

**Comment by miko007** [comment]
compiles just fine for me on macOS 10.15.5.

**Comment by MurrayT** [comment]
Can you tell me your build process? I nuked my local repo and still ended up with the same result.
I did
```
git clone --recursive git@github.com:cinder/Cinder.git
mkdir -p Cinder/build && cd  Cinder/build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j4
```

**Comment by miko007** [comment]
i use it in my own CMake project, so i rebuilt it standalone for reference. i followed your exact steps and it compiled and linked just fine. i am on macOS `10.15.5`.

Do you have XCode and the XCode dev tools installed?

**Comment by MurrayT** [comment]
I have those installed but that comment helped me to find the root of the problem.

I run trunk LLVM as my compiler toolchain so I can access a few more C++20 features in other projects this gives me my `cc` as `clang version 10.0.0`. Switching to the Apple toolchain `Apple clang version 11.0.3 (clang-1103.0.32.62) `resolved the problem and let me compile.

Perhaps this should be noted somewhere that it requires you to ensure that your toolchain uses the Apple provided compilers in order to compile. Another potential resolution would be to check if the user is using a non-standard toolchain and warn them/force them to change.

**Comment by andrewfb** [comment]
Apologies as I overlooked this when it was reported. Should be addressed by the above. Truthfully I'm not sure how it worked previously.
