### ISSUE TITLE
gst/gl/gstglconfig.h: No such file or directory

### ISSUE THREAD

**Issue by fpesari** [cinder/Cinder#2164]
Hello, 

when I try to compile Cinder I get this error:
```
Cinder-0.9.2/include/cinder/linux/GstPlayer.h:24:11: fatal error: gst/gl/gstglconfig.h: No such file or directory
```

I checked on my system (openSUSE) and indeed there is no `/usr/include/gst/gl/gstglconfig.h`, even if I have the correct libraries installed.

I did some searching and I think it's related to [this](https://bugzilla.gnome.org/show_bug.cgi?id=770523): that header file (and a few others) was moved to another directory outside of `/usr/include`. (I still cannot find them on my system, despite having installed all the development files for gstreamer, but that does not concern Cinder).

**Comment by gaborpapp** [comment]
I think I might have seen this on Fedora, but updating Cinder to the latest git solved the issue for me.

**Comment by PetrosKataras** [comment]
I m not familiar with openSUSE but seems that `libgstgl` is provided there by a separate package there and more specifically `libgstgl-1_0-0`? If this is true, can you double check that the dev version of this package is installed in your system?

Other than that the only thing that comes to mind is that the specific header file is installed in a directory that is not picked up by the cmake find module - can you check the following directory 
 `/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include` and see if it exists and if yes, if it contains the header at question?

**Comment by fpesari** [comment]
> I m not familiar with openSUSE but seems that `libgstgl` is provided there by a separate package and more specifically `libgstgl-1_0-0`? If this is true, can you double check that the dev version of this package is installed in your system?

I have it installed but it's just the shared library, no `devel` package!

> Other than that the only thing that comes to mind is that the specific header file is installed in a directory that is not picked up by the cmake find module - can you check the following directory
> `/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include` and see if it exists and if yes, if it contains the header at question?

I already checked when I found that mailing list post, it's not present on my system (even if I already have all the dependencies installed).

I think I figured out the problem - that header is included in the newer `gstreamer-plugins-base`, which is not distributed on Leap 15.1 but rather on Leap 15.2 and Tumbleweed.

The build is going ahead on Tumbleweed, I think I might close this issue right now (I hope it can be useful to Leap 15.1 users trying to build Cinder).
