### ISSUE TITLE
Vs 2019 build error

### ISSUE THREAD

**Issue by aboutqx** [cinder/Cinder#2191]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'filesystem': is not a member of 'std' (compiling source file D:\Github\Cinder\src\cinder\CinderAssert.cpp)	cinder	D:\Github\Cinder\include\cinder\Filesystem.h	31

**Comment by MikeGitb** [comment]
You have to compile with c++17.

**Comment by aboutqx** [comment]
Yes， it works， i just forgot to set all the projects using c++17.
