### ISSUE TITLE
Renaming Default Branch Suggestion

### ISSUE THREAD

**Issue by violetcraze** [cinder/Cinder#2210]
I'd like to suggest that Cinder changes the default branch name. `master` is an out dated term that could be offensive to some people. GitHub recently changed to using the term `main` but I've also seen `core` and `development`. Here's some more information from GitHub: https://github.com/github/renaming.

**Comment by andrewfb** [comment]
I'm aware of this deprecation and it's something we'll bear in mind for future repositories. For historical reasons, as well as in order to avoid breaking setup scripts and the like, we'll maintain the current convention.

**Comment by violetcraze** [comment]
Thanks for the consideration! I think GitHub is making tools that make it easier to switch and those should be available in the new year. But totally understand it can be more difficult to switch some projects.
