### ISSUE TITLE
WebGL Guide

### ISSUE THREAD

**Issue by felixguendling** [cinder/Cinder#2244]
I'm new to Cinder so maybe I've missed it. I have found guides for the following platforms: Windows, Linux, MacOS, Android, iOS (however, the [website](https://libcinder.org/learn) only lists Windows and Mac OS). In theory, it should be possible to render as WebGL too using Emscripten. Has this been done by anyone? Is it trivial so nobody cared to write a documentation or is it just not in the scope of this library? Since WebGL is so easily accessible, this would be a great addition to a library like Cinder, I would guess. I'm interested in any experiences / guides / howtos on how to render Cinder on a HTML5 canvas.

**Comment by felixguendling** [comment]
This seems to be the state-of-the-art:
https://github.com/chaoticbob/Cinder-Emscripten

**Comment by richardeakin** [comment]
Just to chime in, there have been a couple to a few solid attempts at adding Emscripten support, AFAIK this is the one furthest along: https://github.com/cinder/Cinder/pull/2172

It picked up with where @chaoticbob left off and added a lot more functionality from what I understand. Only reason it hasn't made it into an official branch or even master is that there are a few loose ends and hasn't been tested much by the core maintainers. Though if you do test that branch that @sortofsleepy has been working on, feedback on that PR is welcome.

**Comment by felixguendling** [comment]
Thank you! Somehow I missed this. I commented on the PR with my experience after a quick test.
