### ISSUE TITLE
CMake error (cannot find 'cinderTargets.cmake')

### ISSUE THREAD

**Issue by tree786** [cinder/Cinder#2250]
Hi

Trying to build on an arch based system, I have cloned + built the repo, added it to my project folder, and created the following CMakeLists file:
```
cmake_minimum_required( VERSION 3.1 FATAL_ERROR )
set( CMAKE_VERBOSE_MAKEFILE ON )

project( test )

get_filename_component( CINDER_PATH "${CMAKE_CURRENT_SOURCE_DIR}/Cinder" ABSOLUTE )
get_filename_component( APP_PATH "${CMAKE_CURRENT_SOURCE_DIR}/Cinder" ABSOLUTE )

include( "${CINDER_PATH}/proj/cmake/modules/cinderMakeApp.cmake" )

ci_make_app(
    APP_NAME    "test"
    CINDER_PATH ${CINDER_PATH}
    SOURCES     ${APP_PATH}./main.cpp
    INCLUDES    ${APP_PATH}./Cinder/include
)
```
However upon compiling, I get this error:
```
CMake Error at Cinder/lib/linux/x86_64/ogl/Debug/cinderConfig.cmake:2 (include):
  include could not find requested file:

    /home/../Desktop/Cinder/build/lib/linux/x86_64/ogl/Debug/cinderTargets.cmake
Call Stack (most recent call first):
  Cinder/proj/cmake/modules/cinderMakeApp.cmake:78 (find_package)
  CMakeLists.txt:11 (ci_make_app)

```
It's strange , because `cinderTargets.cmake` exists in the Debug folder. Have I missed something out?

**Comment by PetrosKataras** [comment]
Your APP_PATH points to Cinder's root dir while it should point at your project's root dir.

Check same of the samples for details or the docu for the Cinder's cmake configuration here https://www.libcinder.org/docs/guides/cmake/cmake.html

**Comment by tree786** [comment]
Thanks, yeah it seems i was linking to the wrong path. I have now mended it and works as expected.

**Comment by tree786** [comment]
I also seem to be having a very usual issue, when I move the Cinder folder out of my project folder and back again, it seems to break , and starts giving me a CMake error message. Have no idea what's going on, or whether someone else has experienced this
