### ISSUE TITLE
Possible bug in Quaternion slerpShortestUnenforced()

### ISSUE THREAD

**Issue by o0mkh0o** [cinder/Cinder#240]
File: Quaternion.h
Function: Quaternion<T> slerpShortestUnenforced( T t, const Quaternion<T> &end ) const
Line: 448 - 463

Original code:
```
Quaternion<T> d = *this - end;
T lengthD = math<T>::sqrt( this->dot( end ) ); // Typo here

```

Possible corrected version:
```
T lengthD = math<T>::sqrt( d.dot( d ) );
```

Still have to find out how to submit pull requests with issues - sorry for the inconvenience...
Cheers!

**Comment by andrewfb** [comment]
Apologies for the delay - we are using GLM these days for math.
