### ISSUE TITLE
setViewport coordinate bug

### ISSUE THREAD

**Issue by hyperknot** [cinder/Cinder#257]
glViewport's coordinate system is from the lower left corner. Cinder Area's is from the top left. Function should be fixed to the equivalent of:

glViewport( x, getWindowHeight() - ( h + y ), w, h );

but it needs screenHeight inside the function, what I don't know how to access that from this function, without explicitly asking for &screen as argument.

Also, it means that getViewport is buggy too.

**Comment by andrewfb** [comment]
This interface has since changed and requires specification in parallel with OpenGL - lower-left and width/height
