### ISSUE TITLE
On mouseWheel, MouseEvent::getPos is relative to screen instead of window.

### ISSUE THREAD

**Issue by atonparker** [cinder/Cinder#259]
When handling mouse wheel events, `MouseEvent::getPos` returns a coordinate relative to the screen, not the focused window.

__Windows 7 x64 with Cinder v0.84__

**Comment by bradrothenberg** [comment]
Has this issue been fixed?

**Comment by andrewfb** [comment]
This hasn't been looked at but we can revisit it with the upcoming app_refactor

**Comment by bradrothenberg** [comment]
Thanks Andrew!

**Comment by andrewfb** [comment]
This should be fixed by e4496dd on the app_refactor branch.

**Comment by atonparker** [comment]
Wow, blast from the past. Thanks Andrew!
