### ISSUE TITLE
HLS (m3u8) HTTP live streaming video

### ISSUE THREAD

**Issue by philworthy** [cinder/Cinder#275]
Hi.
Does anyone know how to get an m3u8 (HLS) HTTP live stream working in Cinder?
I've tried tweaking the QTimeAdvApp example, which uses a qtime::MovieLoader to load a movie from a URL but it just told me it was unable to load the movie.
From what I can tell QTKit supports m3u8 but there's not much out there in the way of help (I found this article, which is not promising: http://4pcbr.com/topic/a_story_about_hls_video_handling).

Any help much appreciated.
Thanks

**Comment by andrewfb** [comment]
Sorry - this is not something I think any of us has any experience with, and is not presently on the list of officially supported qtime features.
