### ISSUE TITLE
No default format in ImageSourceTexture(const Texture), makes compile fail in VS

### ISSUE THREAD

**Issue by AlanChatham** [cinder/Cinder#355]
At line 1094 in 0.8.5 distribution of Texture.cpp, there is no format set in the default case when it's setting the channel order here:

    default: setChannelOrder( ImageIo::RGBA ); setColorModel( ImageIo::CM_RGB ); setDataType( ImageIo::FLOAT32 ); break;

so if it can't find an internal format from the input, Visual Studio 2012 chokes, saying that format isn't defined. I ran into this trying to compile Robert Hodgin's Flocking example from his Eyeo2012 talk code.

I fixed it by changing line 1074 from 

    GLenum format;

to

    GLenum format = GL_RGBA;

and that seemed to fix it, but I don't really know how all this works, so if someone with some actual knowledge of OpenGL knows better, by all means, there's probably a better way.

**Comment by andrewfb** [comment]
Sorry for the record-setting delay. This has since been addressed.
