### ISSUE TITLE
Json.h comment needs to be changed

### ISSUE THREAD

**Issue by BanTheRewind** [cinder/Cinder#356]
Wrong comment...

//! Sets if JSON string is indented. Default \c true.
WriteOptions& createDocument( bool createDocument = true );

The comment should read:

Wraps JSON data in an anonymous object. Default \c true.

**Comment by paulhoux** [comment]
Is this still relevant or can we close it?

**Comment by richardeakin** [comment]
Looks corrected in current master branch, closing.
