### ISSUE TITLE
getMousePosInWindow()

### ISSUE THREAD

**Issue by hyperknot** [cinder/Cinder#369]
A natural piece of code which I use frequently but I always have to write separately is to get a mouse position in the current window. 

Today, the only way to get it is to use `getMousePos() - getWindowPos()`. 

Not really complicated but I was teaching my friend to Cinder and he was stuck for a few hours to figure out why getMousePos() was not working. I think it might be confusing for other beginners and it might be nice to implement it into something like `getMousePosInWindow()`. I don't know how to handle multiple windows properly, so I'm not submitting the code, just the idea.

**Comment by andrewfb** [comment]
I agree, basically in general getMousePos() is a sort of last-resort since it's not really compatible with the normal event loop - it's better to use mouseMove(). In light of that I think we'll leave the current API as it is.
