### ISSUE TITLE
isNotEmpty() and isNotFull() of ConcurrentCircularBuffer should be const

### ISSUE THREAD

**Issue by timmb** [cinder/Cinder#385]
ConcurrentCircularBuffer.h has two functions `isNotEmpty` and `isNotFull` which do not change the underlying data and return a bool about its state.

At the moment these functions are not marked const, which means I cannot query this state within a const function of my class.

I think this might be because they require non-const access to the mutex, however as the mutex can change state without the logical state of the object changing it is preferable to mark the mutex as `mutable` and allow read-only functions requiring a lock to be const. (See http://stackoverflow.com/questions/4127333/should-mutexes-be-mutable for example).

I can knock this up in a pull request unless there's an argument to keep it the way it is.

Tim

**Comment by andrewfb** [comment]
Thanks - this was revisited in #852
