### ISSUE TITLE
Audio FFT should perform a window filter.

### ISSUE THREAD

**Issue by deanm** [cinder/Cinder#39]
Generally when you FFT audio, in order to get acceptable results, you would perform some sort of window function on the raw sample data before performing the FFT.

Currently no window function is performed, which leads to artifacting and a bleed of the frequencies.  After manually performing a Hann window on the PCM buffer before running it through the FFT processor, I am getting much much better results.

I can't attach files to Github issues, but Andrew I'll send you two screen captures so you can visually see what I'm talking about.  You'll see that window the window, there is loads of artifacting, and you get really bad results in the high frequencies (in the bottom left window).  After applying a Hann window everything is clean as expected.  Sorry there is no sound, but this is on a frequency sweep mp3 (16Hz-20kHz-Exp-1f-10sec.mp3 from http://www.dr-lex.be/software/testsounds.html).

See the Apple vDSP Reference, vDSP_hann_window, which talks about how to create / apply a window across the data.

Cheers,
-- dean

**Comment by richardeakin** [comment]
Hey, apologies for the late reply. We rewrote the audio components for 0.8.6 release, it is much more powerful now.  The (revised) [Fft](https://github.com/cinder/Cinder/blob/master/include/cinder/audio/dsp/Fft.h) class doesn't provide windowing itself, it is expected that the user of the class will window the input waveform Buffer before performing the transform. This is what MonitorSpectralNode does, you can see its option to set the windowing function [here](https://github.com/cinder/Cinder/blob/master/include/cinder/audio/MonitorNode.h#L106) (default is Blackman).
