### ISSUE TITLE
TGA support broken on Windows

### ISSUE THREAD

**Issue by hyperknot** [cinder/Cinder#393]
Loading TGA image files seems to be broken on Windows.

    First-chance exception at 0x751CC41F in ImageFileBasic.exe: Microsoft C++ exception: cinder::ImageIoExceptionFailedLoad at memory location 0x0018E7C0.
    First-chance exception at 0x751CC41F in ImageFileBasic.exe: Microsoft C++ exception: cinder::ImageIoExceptionFailedLoad at memory location 0x0018E7C0.
    First-chance exception at 0x751CC41F in ImageFileBasic.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
    First-chance exception at 0x751CC41F in ImageFileBasic.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
    unable to load the texture file!

I tested it with the official ImageFileBasic sample and a Photoshop made TGA image in 16/24/32 bits.

Sample files:
[16-bit](http://storage.z-e-r-o.in/zsolt/2013/12/tga16.tga)
[24-bit](http://storage.z-e-r-o.in/zsolt/2013/12/tga24.tga)
[32-bit](http://storage.z-e-r-o.in/zsolt/2013/12/tga32.tga)

**Comment by andrewfb** [comment]
Hi - we only support the image file formats that WIC does on Windows, which unfortunately doesn't include TGA.

**Comment by richardeakin** [comment]
TGA is now supported on windows thanks to #1517 and stb image.
