### ISSUE TITLE
Xcode template for ScreenSaver is outdated

### ISSUE THREAD

**Issue by pizthewiz** [cinder/Cinder#410]
The template seems to use GC and I suspect needs a general settings update, perhaps similar to what i've done in my [avfoundation-capture](https://github.com/pizthewiz/Cinder/tree/avfoundation-capture) branch. I don't see an *xcodeproj* file for the template though, if it is floating around, I'd happily update it.

**Comment by andrewfb** [comment]
Thanks - should be fixed by 89e06e2
