### ISSUE TITLE
Add a gl::ScopedCulling object.

### ISSUE THREAD

**Issue by sansumbrella** [cinder/Cinder#506]
The object would handle setting the GL_CULL_FACE state as well as calling glCullFace() to specify which face to cull.

I'll probably tackle this, at least for a first pass, though I don't know if we have a stack for the currently set glCullFace since there isn't a gl:: method equivalent.

**Comment by paulhoux** [comment]
Hasn't this been addressed in 38918c57b67e9d0b100da4c77f9f95537d99a02a ?

**Comment by sansumbrella** [comment]
Yeah, my PR getting merged didn't trigger closing this one for some reason. Closing.
