### ISSUE TITLE
Minimum Xcode version needs updating

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#512]
At appears that as of 0.8.6 release, the Mac binaries are no longer compatible with Xcode versions in the 4.X range. See [this forum post](https://forum.libcinder.org/topic/several-crashes-cinder-0-8-6-mac-samples-audio#23286000002139061) for details, where the user ran into problems with Xcode 4.6, related to the std::function's used by audio::Param (they take 5 arguments, might be something changed in the ABI since then around variadic templates).

I see Xcode 4.4 listed both inthe [MacSetup.html guide](https://github.com/cinder/Cinder/blob/master/docs/welcome/MacSetup.html) and in the [main readme](https://github.com/cinder/Cinder/blob/master/README.md), not sure if it is anywhere else.

I'd recommend we bump it to 5.1 anyway, since Xcode 4.X was rubbish for C++ dev, and it is a free upgrade.

**Comment by andrewfb** [comment]
I've updated the README.md to reflect this. f9e35b7af05c2a102535f68fce1406839b0cc48d
