### ISSUE TITLE
glNext TransformFeedbackSmokeParticles sample renders black screen 

### ISSUE THREAD

**Issue by clinthidinger** [cinder/Cinder#533]
The TransformFeedbackSmokeParticles sample renders a black screen on windows 8.1 with an Nvidia 650m and VS 2013 (it works fine on osx).  A few other people have also reported the [issue](https://forum.libcinder.org/topic/gl-begin-next#23286000002138029) in the forums.  

The issue seems to be that gl_PointCoord is always zero in the fragment shader.  I was able to make it work by enabling GL_POINT_SPRITE, which is deprecated and undefined.  

I added:

#ifndef GL_POINT_SPRITE
	#define GL_POINT_SPRITE 0x8861
#endif

and in the draw call:

gl::ScopedState pointSpriteScope( GL_POINT_SPRITE, true ); 

GL_POINT_SPRITE  is supposed to have been removed and always be on.  This hack shouldn't be necessary.

**Comment by richardeakin** [comment]
Is this still relevant? Those samples have undergone many improvements in recent weeks.

**Comment by clinthidinger** [comment]
Not sure.  I would check for you, but I deleted the Windows 8.1 partition off my laptop a couple of months ago.

**Comment by richardeakin** [comment]
Closing as it seems to be fixed.
