### ISSUE TITLE
ImageIo::getLoadExtensions() not implemented on windows

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#539]
This method seems to only be implemented on Cocoa platforms.  The result is that currently when you fire up the ImageFileBasic sample, no images are 'supported', so the user can't select any images from the file manager (but really they are supported, it works if they file drop an image on the window).

I'm not sure what it takes with WIC to get the list of supported exentions. For windows audio file handling (media foundation), I had to create the list manually from windows documentation ([see here](https://github.com/cinder/Cinder/blob/master/src/cinder/audio/msw/FileMediaFoundation.cpp#L375-L399)). Same thing might be necessary for windows image handling.

**Comment by andrewfb** [comment]
Addressed by 90b4a524e5d831aa696aeb86bafb52b712d09ad3
