### ISSUE TITLE
MovieWriter ignores Texture flip flag

### ISSUE THREAD

**Issue by rsodre** [cinder/Cinder#59]
MovieWriter is ignoring the Texture flip flag. Independent of the flag, it always saves the unflipped Texture.

Sample code:
	mFbo = gl::Fbo( RENDER_WIDTH, RENDER_HEIGHT, format );
	mFbo.getTexture().setFlipped();
	...
	mMovieWriter.addFrame( theFrame, 1.0f/RENDER_FRAMERATE );

**Comment by andrewfb** [comment]
Just confirmed that the gl::Texture ImageSource is aware of topDown-ness
