### ISSUE TITLE
VBO with tangents corrupts OpenGL Active texture state

### ISSUE THREAD

**Issue by FrozenTarzan** [cinder/Cinder#607]
Hi all,

this is my first report, so I hope I give all information that is necessary :-)

It's about an extension for the VBO written by Paul Houx. Here is the cinder forum thread:
https://forum.libcinder.org/topic/mesh-tangent-buffer

And here is Paul's pull request thread here on github:
https://github.com/cinder/Cinder/pull/388

I'm actually using only the 4 source file (TriMesh.h + cpp and Vbo.h + cpp) from the branch and found an extremely strange bug where I got an access violation in a simply draw call (glDrawArrays) of a texture that was not related to anything in my project. glGetError returned invalid operation all the time, which is another strange bug because it usually should only return such an error once.

I found that in enableClientStates the active texture as well as the texture coord array state are set properly: 
```
void VboMesh::enableClientStates() const { 
  //... 
  for( size_t t = 0; t <= ATTR_MAX_TEXTURE_UNIT; ++t ) { 
    if( mObj->mLayout.hasTexCoords( t ) ) { 
      glClientActiveTexture( GL_TEXTURE0 + (GLenum)t ); 
      glEnableClientState( GL_TEXTURE_COORD_ARRAY ); 
    } 
  } 
  //... 
} 
```
In the method disableClientStates on the other hand there is the corresponding code missing (original code): 
```
void VboMesh::disableClientStates() const { 
  //... 
  for( size_t t = 0; t <= ATTR_MAX_TEXTURE_UNIT; ++t ) { 
    if( mObj->mLayout.hasTexCoords( t ) ) { 
      glClientActiveTexture( GL_TEXTURE0 + (GLenum)t ); 
    } 
  } 
  glDisableClientState( GL_TEXTURE_COORD_ARRAY ); 
  //... 
} 
```
To overcome this bug, I changed the code to the following: 
```
void VboMesh::disableClientStates() const { 
  //... 
  for( size_t t = 0; t <= ATTR_MAX_TEXTURE_UNIT; ++t ) { 
    if( mObj->mLayout.hasTexCoords( t ) ) { 
      glClientActiveTexture( GL_TEXTURE0 + (GLenum)t ); 
      glDisableClientState( GL_TEXTURE_COORD_ARRAY ); // 1. disable the client states 
    } 
  } 
  glClientActiveTexture( GL_TEXTURE7 ); // 2. set the active texture unit so that we can actually disable the client state for our tangents 
  glDisableClientState( GL_TEXTURE_COORD_ARRAY ); 
  glClientActiveTexture( GL_TEXTURE0 ); // 3. set back to active texture unit 0, the "default" one. at least Cinder seems to count on this everywhere else?! 
  //... 
} 
```
I hope this all makes sense. It took me sooo long to find a solution. Is it the right one? ;-)

**Comment by andrewfb** [comment]
Apologies for the delay on this. The latest Cinder GL API should implement all of this correctly.
