### ISSUE TITLE
Remove or deprecate CallbackMgr

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#612]
This was added before we incorporated signals and no longer necessary. It is in use by the OSC and TUIO blocks, so those need to be updated to use signals before it can be removed.

**Comment by richardeakin** [comment]
After looking into this in greater detail, we can't safely swap in ci::signals as CallbackMgr is being fired from a background thread in OscListener. That implementation will most likely get an overhaul, so it doesn't gain us much to muck with it now. CallbackMgr lives on.

**Comment by thyrrestrup** [comment]
Although the rest of Cinder has moved to the new signals implementation and maybe eventually also OscListener - it might be worth keeping callbackmgr for applications using threads as it is more light weight than including boost::signals2??

**Comment by thyrrestrup** [comment]
Out of curiosity is it safe to call the callbackmgr from a separate thread?

**Comment by richardeakin** [comment]
No, currently you'd have to wrap the calls with a mutex yourself. However, this is a bit easier to do with CallbackMgr, but currently it would leave a hole using ci::signals, because there you are handed back a `ci::signals::Connection`, and you disconnect from that.

As I've mentioned to a few elsewhere, I think signals, or even CallbackMgr, calling out from within a background processing thread makes it much easier for users to make mistakes. Ex., they connect a handler up that tries to draw an info label to their display, unwittingly causing graphics driver problems because they are still on the background thread.

I think the best solution is two-fold - offer a simple std::function (not a signal) that is documented as calling out from the processing thread, and use at your own risk. Then, also offer some sort of polling or dispatch mechanism, where the user safely gets the data on the main thread. The current solution is polling, though we've been looking into using `asio::io_service` as a dispatch.

**Comment by thyrrestrup** [comment]
It seams to me that it would be possible to remove the callback part of the OscListener as the basic use case is to ask the listener for new messages per the sample. Also the callback is not safe to use for updating variables accessed by the main thread..
