### ISSUE TITLE
setLabel returns a GL_INVALID_VALUE on VAO and TransformFeedbackObj

### ISSUE THREAD

**Issue by ryanbartley** [cinder/Cinder#638]
I'm using a NVidia quadro K5000 graphics card, driver version 9.18.13.4121, dated 11/25/2014. If you see it on your side, I'll send the info to Nvidia.

**Comment by richardeakin** [comment]
Is this still an issue or can it be closed?

**Comment by ryanbartley** [comment]
I believe it is but haven't used labeling in a while.

**Comment by richardeakin** [comment]
Ok, let us know here if you can reproduce and we'll reopen.

**Comment by akaStiX** [comment]
I had similar bug on Nvidia GPU with my own project and I managed to fix it by calling _glObjectLabel_ **after** binding VAO, not after creating it. It must be this is an issue due to a driver's internal optimization - i.e. it wires objects only, when they are bound the first time
