### ISSUE TITLE
Texture doesn't show up on Billboards (gl.h function drawBillboard( ... ))

### ISSUE THREAD

**Issue by PlumCantaloupe** [cinder/Cinder#64]
Not sure exactly what the problem is but it can be easily fixed by explicitly setting the normal facing towards the screen before draw. e.g.

glNormal3f( 0, 0, -1); //point normal towards screen
someTexture.bind(0);
gl::drawBillboard( ......
someTexture.unbind(0); 

A couple of use have ran into the issue and thus why I am submitting it; though perhaps we are using the function incorrectly?

**Comment by andrewfb** [comment]
This should be working these days.
