### ISSUE TITLE
update jsoncpp

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#643]
Comments in json can be very useful, and jsoncpp is one of the few json libraries that supports them (even though not part of the spec). It seems that there is a couple bugs in the version of jsoncpp we used, though I believe they are fixed in its master branch (see [this commit](https://github.com/open-source-parsers/jsoncpp/commit/fd06bfca792d327c9fc990bc1052c1bd0cbf7836)).

**Comment by richardeakin** [comment]
Update:  I updated to 0.7.0 (in [this branch](https://github.com/richardeakin/Cinder/tree/jsoncpp_upgrade_070)), but there was a remaining bug around comments. Awesomely, @cdunn2001 from the jsoncpp team has already fixed it, so I think a good plan is to update our copy against a new release with this fix.

If the new jsoncpp release requires visual studio 2013, the change will have to be made against glNext branch.

As an aside, I used jsconcpp's almagamate script ([recommended here](https://github.com/open-source-parsers/jsoncpp#using-jsoncpp-in-your-project)), which produces just one cpp. I think this is a good idea, since it will improve build times and ease maintainence a tad. If others disagree please let me know.

**Comment by andrewfb** [comment]
Just logging my agreement that we should parse comments by default.
