### ISSUE TITLE
Exception handling error - AssetLoadExc

### ISSUE THREAD

**Issue by thyrrestrup** [cinder/Cinder#648]
The following should output `non-existing-asset.txt` e.g. the relativePath in the console but nothing shows..

```c++
try {
	DataSourceRef asset = loadAsset( "non-existing-asset.txt" );
} catch ( ci::app::AssetLoadExc &exc ) {
	console() <<  exc.what() << endl;
}
```
This however produce the correct result.. 
```c++
try {
	DataSourceRef asset = loadAsset( "non-existing-asset.txt" );
} catch ( ci::app::AssetLoadExc &exc ) {
	console() <<  exc.cinder::Exception::what() << endl;
}
```
Xcode 6.1.1 - glNext branch

**Comment by richardeakin** [comment]
Thanks for reporting. I'm aware of this bug, [fixed it](https://github.com/richardeakin/Cinder/commit/8e74360fe800842b19e7e2761e6c179e83cffa94) in my app_refactor branch though I'll try to get it into master when I have a moment.
