### ISSUE TITLE
glNext TransformFeedbackSmokeParticles Windows problem

### ISSUE THREAD

**Issue by num3ric** [cinder/Cinder#651]
@ryanbartley The TransformFeedbackSmokeParticles sample stays all black on Windows.  This seems to be cause by point sprites/gl_PointCoord not functioning properly. (Rendering the particles as normal points works.)

http://forum.jogamp.org/gl-PointCoord-not-working-without-enabled-GL-POINT-SPRITE-is-it-a-bug-td4029611.html
https://www.opengl.org/discussion_boards/archive/index.php/t-182248.html

**Comment by richardeakin** [comment]
Is this a dupe of #533 (though very helpful links, thanks)?

**Comment by num3ric** [comment]
Yes, sorry, duplicate.
