### ISSUE TITLE
MayaCamUI Inverted Panning

### ISSUE THREAD

**Issue by bradrothenberg** [cinder/Cinder#653]
Hello, I am on the current master branch, & am pointing out that the MayaCam pan becomes inverted when you flip the scene upside down, so when moving the mouse right, the scene pan's left, & vice-versa.

thank you!

**Comment by num3ric** [comment]
While this behavior isn't new, I believe you are right: it is broken. I tried it in Maya and no inversion occurs regardless of the camera angle.

This must be the guilty line (in the glNext branch):
https://github.com/cinder/Cinder/blob/glNext/include/cinder/MayaCamUI.h#L74

I haven't found simple fix yet but there has to be one, with a bit of linear algebra...

**Comment by richardeakin** [comment]
Fixed with #658
