### ISSUE TITLE
glNext: draw texture srcArea -> dstRect not correct. 

### ISSUE THREAD

**Issue by dscheibel** [cinder/Cinder#656]
Code:
// faded bg image:
gl::color(0.2,0.2,0.2);
gl::draw( mTex2dRef_1 );
// full color overlaying subregion: 
gl::color(1,1,1);
int x1 = mousePos.x; 
int y1 = mousePos.y;
int x2 = x1 + 300;
int y2 = y1 + 300;
Area srcArea = Area( x1, y1, x2, y2 );
Rectf dstRect = Rectf( x1, y1, x2, y2 );
gl::draw( mTex2dRef_1, srcArea, dstRect );

Current Result (in glNext): 
y of the srcArea looks flipped.
![screen shot 2015-01-14 at 4 17 24 pm](https://cloud.githubusercontent.com/assets/279711/5747824/24606ec2-9c09-11e4-92e1-f485c79873fd.png)

Expected Result (in 0.8.6): 
![screen shot 2015-01-14 at 4 28 58 pm](https://cloud.githubusercontent.com/assets/279711/5748018/857c0a3a-9c0a-11e4-90d5-e1a6a23fa27d.png)

**Comment by num3ric** [comment]
You're right, if you don't use the `gl::Texture2d::Format().loadTopDown()` option on your texture, the result is incorrect.

**Comment by richardeakin** [comment]
Fixed with #670
