### ISSUE TITLE
CaptureImplAvFoundation created with 640x480 serves 1280x720 textures

### ISSUE THREAD

**Issue by pizthewiz** [cinder/Cinder#669]
More of a tracking issue than something pressing, I thought I'd mention a quick behavioral difference I just ran into.

Unlike the _QTKit_-based capture `CaptureImplQtKit` used in the master branch, when `CaptureImplAvFoundation` is created at a size of 640x480, it serves textures of a different size. This can be seen in the _CaptureBasic_ sample which creates a capture object at 640x480 and yet the textures out of the capture object are 1280x720 on my Late 2013 MacBook Pro.

Some further debugging is needed as `-[CaptureImplAvFoundation prepareStartCapture]` does check the size and sets the expected preset, see [CaptureImplAvFoundation.mm#L121-132](https://github.com/cinder/Cinder/blob/glNext/src/cinder/CaptureImplAvFoundation.mm#L121-132):
```Objective-C
- (bool)prepareStartCapture 
{
    NSError *error = nil;

    mSession = [[AVCaptureSession alloc] init];

	if( cinder::ivec2( mWidth, mHeight ) == cinder::ivec2( 640, 480 ) )
		mSession.sessionPreset = AVCaptureSessionPreset640x480;
	else if( cinder::ivec2( mWidth, mHeight ) == cinder::ivec2( 1280, 720 ) )
		mSession.sessionPreset = AVCaptureSessionPreset1280x720;
	else
		mSession.sessionPreset = AVCaptureSessionPresetMedium;
```

**Comment by pizthewiz** [comment]
Yep, in the old world, the pixel buffer dimensions were set manually based on what the capture object was created with, [CaptureImplQtKit.mm#L177-187](https://github.com/cinder/Cinder/blob/master/src/cinder/CaptureImplQtKit.mm#L177-187):
```Objective-C
NSDictionary *attributes = [NSDictionary dictionaryWithObjectsAndKeys:
    [NSNumber numberWithDouble:mWidth], (id)kCVPixelBufferWidthKey,
    [NSNumber numberWithDouble:mHeight], (id)kCVPixelBufferHeightKey,
    //10.4: k32ARGBPixelFormat
    //10.5: kCVPixelFormatType_32ARGB
    //[NSNumber numberWithUnsignedInt:pixelBufferFormat], (id)kCVPixelBufferPixelFormatTypeKey,
    [NSNumber numberWithUnsignedInt:kCVPixelFormatType_24RGB], (id)kCVPixelBufferPixelFormatTypeKey,
    nil
];
	
[mCaptureDecompressedOutput setPixelBufferAttributes: attributes];
```

There doesn't seem to be any analogue on the `CaptureImplAvFoundation`, just the session presets. Also strange that `CaptureImplQtKit` was using 24-bit RGB :wink:.

**Comment by andrewfb** [comment]
Thanks for logging this; so if I follow then the camera itself is refusing to do 640x480, even though that's the session preset we request?

**Comment by pizthewiz** [comment]
Exactly! It wasn't immediately obvious from the docs if this is expected or not, the preset might be more of a hint of usage intent than a hard setting?

**Comment by andrewfb** [comment]
Hmm yeah - not clear to me what the best course of action is here. If you're "paying" for the larger image anyway, then perhaps we should just return it at full size. It's maybe useful to consider what we should do if a user has requested an oddball size; say 641x480. Automatically resizing seems a little presumptuous, but at the same time, for many applications where the exact size is a requirement that may be preferred.

**Comment by andrewfb** [comment]
I'm going to close this as I think the AVF capture pipeline itself is somewhat limited in this regard.

**Comment by pizthewiz** [comment]
Strange, I just looked into this again, this time on OS X 10.11 dev seed 2 and the texture was at my requested size - so either something in Cinder changed along the way or El Capitan sorted it out, either way I'll take it :wink:
