### ISSUE TITLE
upgrade GLM to 0.9.6(+)

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#672]
Marking a note that we need to do this at some point, it [looks like](https://github.com/g-truc/glm/releases) 0.9.6.1 has been out for about a month.

Many additions were added since our version, 0.9.5, large ones that could possibly effect how we expose glm functions in the ci namespace (like, it tries to coexist with cmath functions).

**Comment by andrewfb** [comment]
Working on this in https://github.com/cinder/Cinder/tree/glNext_glm_upgrade

**Comment by richardeakin** [comment]
Fixed in glNext branch
