### ISSUE TITLE
Teapot spout has no inner mesh.

### ISSUE THREAD

**Issue by paulhoux** [cinder/Cinder#676]
When rendering using back-face culling, the inner spout is invisible. I think this is because of incorrect polygon winding. Will make a pull request shortly.

**Comment by paulhoux** [comment]
On further investigation, it looks like the spout has no inner mesh, so back face culling is not supported at all. Pity.

**Comment by andrewfb** [comment]
Going to close this as an active issue since the traditional GL teapot has no "insides".
