### ISSUE TITLE
getSaveFilePath ignores parameter path

### ISSUE THREAD

**Issue by lithander** [cinder/Cinder#68]
I call <b>loadImage(mSourceFileName);</b> to open an image and later want to save it again. By calling <b>getSaveFilePath(mSourceFileName)</b> I'd expect the SaveFileDialog to have the file the path refers preselected. This isn't the case, the FileName Editfield is empty, the selected Folder is my "personal files" directory even though that's not where the file was loaded from.

Quick Fix: Instead of or in addition to setting <b>lpstrInitialDir</b> member <b>lpstrFile</b> needs to contain the path. This works for me (Windows 7) but might not be the best way to do it...

**Comment by andrewfb** [comment]
This should be fixed as it's going to get on Win7, where behavior changed to essentially ignore the initialDir request: https://social.msdn.microsoft.com/Forums/windowsapps/en-US/7c6614ea-bef9-4421-9778-f8e42b95456a/openfilename-lpstrinitialdir-behavior-change-in-windows-7-how-to-avoid?forum=windowsuidevelopment
