### ISSUE TITLE
Solve ci::Color's relationship to GLM

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#681]
Where this stands, subclassing tvec3 types didn't buy us much, so treating the two as convertible to eachother is making more sense (similar to the relationship between mat4 and quat).

**Comment by richardeakin** [comment]
Other thing would be making some of the current Color(A) methods more congruent with GLM, such as length(), normalize(), or lerp (mix in glm / glsl).

**Comment by richardeakin** [comment]
Question: should we be able to pass vec3's as color to things like TriMesh? Like the following (which doesn't currently compile):

```cpp
trimesh.appendColorRgb( vec3( 1, 0, 0 ) );
```

**Comment by notlion** [comment]
Seems to me that most of the functionality in the Color(A) classes is covered by GLM `vec3`, `vec4`, `uvec3` and `uvec4` types.

The other functions like setting by color model, converting HSV to RGB, etc could be covered by free functions GLM style. It would simplify the API in a lot of places to have one vec type.

**Comment by notlion** [comment]
I suppose the question is: Are there any places where functions are overloaded on vec3/4 and Color(A)? This case seems like it would be pretty rare to me.

**Comment by richardeakin** [comment]
We've come to somewhat of an opinion around this, if not a decision. I agree with @notlion that having one vec type that functions as color, or anything else with 2, 3, or 4 dimensions. No matter what we do, we can't really coerce the Color class to be completely interoperable with vec3/4 (though we have tried to  do the best we can already, where one is implictly convertible in many situations to the other).  On the other hand, removing Color at the moment is quite invasive, it means many more breaking changes after we've gotten nearly everything in sync and ready for 0.9.0 release.

So the current opinion is to revisit this in a future release, and consider removing ColorT / ColorAT  classes. We'd then be creating colors from hex with functions, similar to how glm works.
