### ISSUE TITLE
WindowImplBasicCocoa has null mDisplay when 11 windows are made

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#693]
First reported on [forum here](https://forum.libcinder.org/topic/glnext-multi-window-app-framerate-drop#23286000002266019), reproduced with [this gist](https://gist.githubusercontent.com/simongeilfus/db9dee222d67cceed285/raw/a6a1741a878610e8543998ad7dcb16b28711535a/gistfile1.cpp).

Not sure what is going wrong, but I can see that the 11th and last `WindowImplBasicCocoa` has no mDisplay, which is causing an exc_bad_access from within `[WindowImplBasicCocoa windowMovedNotification:]`, where `mDisplay->getCgDirectDisplayId()` is called.

At a minimum we should try to fail more gracefully.

**Comment by andrewfb** [comment]
I believe this change cbf971d2e25e32c16c839bdd6dd054a1ea3914bb should at least work around this. Not much we can do - seems the call to screen: returns nil. In that scenario we preserve the old mDisplay and skip emitting a displayChanged() signal.

**Comment by richardeakin** [comment]
Strange, now I can't reproduce even when I rollback to before your fix. Though your fix seems likely to solve the problem, if/when it occurs.
