### ISSUE TITLE
Two windows causes 30fps on Mac

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#695]
First reported on forum [here](https://forum.libcinder.org/topic/glnext-multi-window-app-framerate-drop#23286000002266019), repro'd with this [gist](https://gist.githubusercontent.com/simongeilfus/db9dee222d67cceed285/raw/a6a1741a878610e8543998ad7dcb16b28711535a/gistfile1.cpp). Hit 'a' to create a second window.

Possibly only on OS X 10.10, older versions are reported to still work correctly.

**Comment by andrewfb** [comment]
Per the forum discussion I believe this is fixed.
