### ISSUE TITLE
winrt features

### ISSUE THREAD

**Issue by Ryuuke** [cinder/Cinder#702]
Hello,
I'm new to cinder, I just want to know if winRT version is actually fully supported in cinder, I noticed that it misses some features like ObjLoader and JSON support.

By the way, how can we load models in winRT?

Thanks :)

**Comment by andrewfb** [comment]
I would say WinRT support should currently be regarded as experimental. It's probably not ready yet to have a serious project based on it.

**Comment by andrewfb** [comment]
Have a look at the recent update to the glNext branch. The WinRT port is still very much a work in progress, but should allow usage of OpenGL ES 3 features both on the desktop and on x86 & x64 hardware. This includes OBJ loading, incidentally. Closing this for now.
