### ISSUE TITLE
The Rand class's nextVec3f and nextVec2f functions should be renamed.

### ISSUE THREAD

**Issue by paulhoux** [cinder/Cinder#705]

**Comment by richardeakin** [comment]
Yea we thought about renaming them to `nextVec2` / `nextVec3()` when first making the switch to GLM, but the vote at the time was that it was too much renaming. Also, that naming scheme wouldn't work well for double vecs, though I suppose that could hypothetically be called `nextVec2d()` recardless.

**Comment by andrewfb** [comment]
Addressed by 0688182
