### ISSUE TITLE
LoggerFile writing to file in non-existent folder should still work

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#717]
Can test by enabling [this line](https://github.com/cinder/Cinder/commit/dafff1475eaa0f1b0cefdde3808e41ac5929c862#diff-73bdc39eb7181f7144af0797e5338d5dR50) in DebugTest.

**Comment by lucasvickers** [comment]
What's your take, should we create the folder structure?

**Comment by richardeakin** [comment]
Yea I mean, I think it would be convenient and what the user expected, if they specify a folder/file combo and the folder doesn't exist, then we create the folder too. @andrewfb what do you think?

**Comment by andrewfb** [comment]
I agree - seems like this is what the user would want in basically every scenario.

**Comment by richardeakin** [comment]
Fixed in #737, thanks @lucasvickers
