### ISSUE TITLE
dispatchAsync not doing the right thing (WinRT)

### ISSUE THREAD

**Issue by thyrrestrup** [cinder/Cinder#720]
This is a copy paste from: https://forum.libcinder.org/topic/dispatchasync

It seams to me that the dispatchAsync is not doing as expected on WINRT.
The expected result is that the function is called on the main thread before the update loop as stated in the source.
The function is implemented using std::async with a temporary future.
The documentation on std::async(Notes) - states that a future with a temporary object lifetime will block until the function is executed. This means that it is in fact a synchronous operation executed on which ever thread it is called from.

Another thing to note is that when using std::async without a policy it is implementation dependent whether the operation is async or not which means even if the future is not temporary there is no way of knowing if the function is executed async or when the .get() function is called.

Now that the new signals implementation no longer support threads - does it make sense to make a thread safe callback manager of sorts?

**Comment by andrewfb** [comment]
Probably the most interesting approach to this would be to upgrade the WinRT port to make use of ASIO, which is how we implement dispatchAsync() on the other platforms. Since MS did the initial work of porting Cinder, ASIO has added WinRT support, so this might be a good motivating case for revisiting it.

**Comment by andrewfb** [comment]
If you have a good test case for this would you mind giving the latest glNext a look? We are now using ASIO on WinRT, though the much larger change is that existing GL code should work (through GL ES 3).

**Comment by andrewfb** [comment]
Just tested this; fixed in the glNext branch.
