### ISSUE TITLE
gl::drawSolidRect off by one Y pixel  (in glNext)?

### ISSUE THREAD

**Issue by hluisi** [cinder/Cinder#721]
Maybe it's me, but is the `gl::drawSolidRect` off by one Y pixel?

Example:

    gl::clear( Color( 1, 0, 0 ) ); 
	gl::color( Color( 0, 0, 0 ) );
	gl::drawSolidRect( getWindowBounds() );

H

**Comment by richardeakin** [comment]
What platform? What is the the dimensions that getWindowBounds() returns? `gl::drawSolidRect()` doesn't compute any maths, so perhaps somehow you are getting a slight rounding error?

Tried here with BasicApp on Mac OS X and the result looks right to me (all black, no red).

**Comment by hluisi** [comment]
Windows 8.1 (native opengl app). It could be my multi-display environment,  Here is a screenshot:
![solidrectissue](https://cloud.githubusercontent.com/assets/319161/6402282/4d208206-bdbb-11e4-8127-3354273667de.png)

**Comment by hluisi** [comment]
It's easier to see with green:
![solidrectissue2](https://cloud.githubusercontent.com/assets/319161/6402957/8b50ea5c-bdc0-11e4-822c-ae9a0940cec4.png)

**Comment by hluisi** [comment]
nm, the issue seems to be related to my current desktop theme. Damn strange, but after changing to the default theme the issue went away.  it doesn't seem to be a cinder issue at all, just a windows one.

**Comment by richardeakin** [comment]
Strange indeed. Thanks for reporting in any event, it's good to know about these things..
