### ISSUE TITLE
asset resource fs::path's versus directories

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#727]
Question: should the following work, i.e. return the 'default' assets directory?

```
fs::path baseAssetDir = app::getAssetPath( "" );
```

Right now that works because there is no check to see if the result is a directory or not ([impl here](https://github.com/cinder/Cinder/blob/app_refactor/src/cinder/app/Platform.cpp#L97-L101)), so it returns the base asset path (the one that was added by [Platform::findAndAddBaseAssetPath](https://github.com/cinder/Cinder/blob/app_refactor/src/cinder/app/Platform.cpp#L106-L122)). Perhaps we should do this a little more explicitly, and add a method called getAssetDirectories() to expose all of the paths?

Thinking about it, I could see how you would still want the following to work, i.e. return an fs::path to the assets/images folder:

```
fs::path imagesDir = app::getAssetPath( "images" );
```

Somewhat related, it seems like the virtual method [Platform::getResourcePath()](https://github.com/cinder/Cinder/blob/app_refactor/include/cinder/app/Platform.h#L70) should actually be called `getResourceDirectory()`.

related to #710.

**Comment by andrewfb** [comment]
I agree with all your points, and basically net out at getAssetPath("") is a hack but a handy one; however I don't have a strong feeling if someone else does. I do think getAssetDirectories() would be an appropriate addition regardless. And you're probably right; getResourceDirectory() is the right name, and is probably used infrequently enough that no one will notice if we fix it.
