### ISSUE TITLE
(app_refactor) DisplayMac error message at startup on dual gpu macbooks. 

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#728]
Root of problem [explained here](http://prod.lists.apple.com/archives/cocoa-dev/2014/Jun/msg00202.html).

The error message looks like:
```
|error  | static void cinder::DisplayMac::displayReconfiguredCallback(CGDirectDisplayID, CGDisplayChangeSummaryFlags, void *)[404] Unable to locate corresponding NSScreen for CGDirectDisplayID
```

In a nutshell, when the gpu changes then unexpected things happen with tying our ci Displays to correspinding CGDisplayId / NSScreens. In the end the correct display is in use when the app is running.. could just be an annoying error message we need to surpress, or there might be side effects.

Related to #710.

**Comment by andrewfb** [comment]
Fixed by ed74713bef411d3222d433e897b2899dd7642db5
