### ISSUE TITLE
operator== for Rectf/Rectd

### ISSUE THREAD

**Issue by 0ax1** [cinder/Cinder#730]
Why is there no == operator for Rectf/Rectd? I think it would be convenient to have one in Rect.h .
Is this intended because 4 comparisons x1,y1,x2,y2 are considered to be too expensive for an operator?

**Comment by num3ric** [comment]
Because you *generally* don't want to assess equality by comparing floats/doubles directly?
https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

Although, https://github.com/g-truc/glm/blob/0.9.6/glm/detail/type_vec3.inl#L554

**Comment by 0ax1** [comment]
Thanks for pointing to the article. That explains it.
