### ISSUE TITLE
Latest glNext checkout 69ec42c is broken on Mac

### ISSUE THREAD

**Issue by eighteight** [cinder/Cinder#741]
n file included from /Users/eight/repos/Cinder/src/cinder/app/cocoa/RendererImpl2dMacQuartz.mm:24:
In file included from ../include/cinder/app/cocoa/RendererImpl2dMacQuartz.h:24:
In file included from ../include/cinder/app/AppBase.h:30:
../include/cinder/app/Window.h:64:6: error: expected a type
                - (NSString *)getTitle;
                   ^
../include/cinder/app/Window.h:65:21: error: expected a type
                - (void)setTitle:(NSString *)title;
                                  ^
2 errors generated.

**Comment by richardeakin** [comment]
Hm, it builds for me, but I can buy that it is due to clang parsing the headers in a different order on your machine, for whatever reason. I just pushed a commit that hopefully addresses this (86c32cfb8db3916), can you check?

**Comment by eighteight** [comment]
It builds OK now. I think the same or very similar error percolated into this branch, but was fixed by Andrew.

Separately, I just noticed that armv7s is still being built for. I thought this arch was removed from glNext (https://forum.libcinder.org/topic/glnext-removing-armv7s). No harm, but it adds a sizable time to the build:

CompileC build/cinder.build/Release-iphoneos/cinder_iphone_sim.build/Objects-normal/armv7s/sweep.o /Users/vgusev/repos/Cinder/src/libtess2/sweep.c normal armv7s c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/eight/repos/Cinder/xcode

**Comment by richardeakin** [comment]
It looks like you're building cinder_iphone_sim target - looking at the project settings, that should be built only for simulator devices (32-bit arch) and you might have your device selected in the scheme tab.  Try building cinder_iphone target, that should only produce binaries for arm64 and armv7

**Comment by eighteight** [comment]
I simply run fullbuild.sh

--8

**Comment by pizthewiz** [comment]
Hmm, I ran:
```sh
% ./xcode/fullbuild.sh | grep armv7s
```
and didn't see anything `armv7s`.

**Comment by eighteight** [comment]
I think fullbuild.sh delegates everything to the xcode project;

$eight: xcode: more fullbuild.sh 
#!/bin/sh

CURRENT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
CINDER_XCODEPROJ="${CURRENT_DIR}/cinder.xcodeproj"

xcrun xcodebuild -project ${CINDER_XCODEPROJ} -alltargets -configuration Release $@
xcrun xcodebuild -project ${CINDER_XCODEPROJ} -alltargets -configuration Debug $@
