### ISSUE TITLE
geom::issues since the app_refactor merge

### ISSUE THREAD

**Issue by simongeilfus** [cinder/Cinder#743]
Hi,

I might be doing something wrong but I have some modelling code that use to work a few weeks ago and doesn't anymore since the app_refactor merge. I was first thinking that the issue was related to the Combine object, but while digging a bit more I'm suspecting the >> operator to be responsible for it. I'm not sure I can spot the problem or the commit responsible for the issue as there was quite a few in the last week but I did make a little test app that should allow to reproduce the error...

https://gist.github.com/simongeilfus/b12e30fdc38849260653

I hope I could help more but the whole Source and operator>> implementation still feel really obscure to me.

**Comment by andrewfb** [comment]
Just to confirm, are you seeing this with the very latset glNext? I made a commit very recently that was relevant to this, but I haven't read the gist closely yet to have a sense of what I should see. Here's what I get with the latest:

![image](https://cloud.githubusercontent.com/assets/227107/6642852/3ff1fd8e-c97e-11e4-8218-3e73fa18a91f.png)

**Comment by andrewfb** [comment]
OK - I reproduced this. Does the above commit fix it for you?

**Comment by simongeilfus** [comment]
Nice thanks a lot Andrew!
