### ISSUE TITLE
geom::Rect::getAttribDims( Attrib::COLOR ) always returns 4

### ISSUE THREAD

**Issue by BanTheRewind** [cinder/Cinder#753]
I have a few too many changes in my repo to PR this. 

    uint8_t Rect::getAttribDims( Attrib attr ) const
    {
    	switch( attr ) {
    		case Attrib::POSITION: return 2;
    		case Attrib::NORMAL: return 3;
    		case Attrib::TEX_COORD_0: return 2;
    		case Attrib::COLOR: return 4;
    		case Attrib::TANGENT: return 3;
    		default:
    			return 0;
    	}
    }

The Attrib::COLOR case should be:

    case Attrib::COLOR: return mHasColors ? 4 : 0;

geom::Rect does not have color by default. This causes texture coordinate data to show up in ciColor in the shader if no colors are specified.

**Comment by BanTheRewind** [comment]
Nevermind. I see what is happening. The default colors for Rect look like texcoord values. I would highly recommend changing these to straight up red, blue, green, yellow, or whatever.

**Comment by richardeakin** [comment]
somewhat related: #660

**Comment by BanTheRewind** [comment]
Right. I can take a stab at this tomorrow. I'm thinking this:

- Colors are off by default.
- The default colors do not look like texture coordinate values
- case Attrib::COLOR: return mHasColors ? 4 : 0;

**Comment by richardeakin** [comment]
That all makes sense to me, the colors you're proposing seem like good too, as Rect colors are basically just for debugging.

**Comment by BanTheRewind** [comment]
https://github.com/BanTheRewind/Cinder/commit/a09082d425edded69c444be85e363b8c7c58b9e5

**Comment by andrewfb** [comment]
OK - merged 06cdaf959afc1638d5a3dd9417c793864e82ff5b and then made Rich's suggested changes.
