### ISSUE TITLE
App not caling update() method

### ISSUE THREAD

**Issue by rsodre** [cinder/Cinder#76]
I have one big old App that do not call the update() method on the first loop.
I had to make a boolean to check if it is the first frame, and call update(0 from inside draw().
Today it happened again, one App was running fine and then suddenly started to crash on draw().
I found out that it was not calling the update() method as well.
I'm sure my update() is the virtual, I dod not touch the method signature..
I even put a breakpoint in privateUpdate__(), and it is not reached as well.
This app is smaller, and I can send for debugging if needed.
I'm on OSX 10.6.

**Comment by andrewfb** [comment]
These days there's a guard in place to prevent draw() from ever firing before the first call to update()
