### ISSUE TITLE
Remove remaining implicit shared_ptr<Obj>'s

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#763]
This is the time to do it, since it is breaking, and fairly easy in most cases. From a quick search, the remaining classes using the old implicit shared_ptr design are:

- [x] `ci::Serial`
- [x] `ci::Buffer`
- [x] `ci::Capture`
- ~~`ci::MovieWriter`~~ windows legacy only, Mac uses newer `qtime::AvfWriter` that follows create pattern
- ~~`ci::qtime::MovieGl`~~ only impl that uses it is quicktime legacy, newer AVF impl follows the create pattern
- [x] `ci::ip::AdaptiveThreshold`
- ~~`ci::Font`~~  text API will be entierly rewritten, and will be updated then.

__2015/4/21 update:__ decided to hold off on Font for this release, `Buffer` will move to value semantics similar to Surface.

**Comment by pizthewiz** [comment]
Awesome, I was wondering about `Buffer` and `Capture` just the other day.

**Comment by pizthewiz** [comment]
Would `ci::app::Event`, `ci::app::MouseEvent` and `ci::app::KeyEvent` also fit?

**Comment by richardeakin** [comment]
This work has begun in [glNext_remove_implicit_shared](glNext_remove_implicit_shared) branch, starting with `Serial`.

@pizthewiz not exactly sure what you mean, `app::Event`s are designed to be passed with value semantics and don't use shared pointers.

**Comment by pizthewiz** [comment]
Ahh my confusion, I thought the event types also had an implicit shared pointer internally.

**Comment by richardeakin** [comment]
`Buffer` work is in the branch [https://github.com/cinder/Cinder/tree/glNext_buffer_value_semantics](glNext_buffer_value_semantics). Windows and iOS-specific code still needs to be surveyed, I've gone through the usage on Mac and updated where I felt appropriate.
