### ISSUE TITLE
Serial getDevices(true) crash when repeatedly called

### ISSUE THREAD

**Issue by AphexHenry** [cinder/Cinder#765]
If you call Serial::getDevices(true); in the update method the application will crash after several minutes.
I happens both release and debug mode, wether there is a device connected or not. I am running it on OSX Yosemite.

The log is "libc++abi.dylib: terminating with uncaught exception of type cinder::SerialExcDeviceEnumerationFailed: std::exception" and it is detected as a SIGABRT issue.

Note, I opened this topic where you can find what seems to be the fix for this issue:
https://forum.libcinder.org/topic/serial-crash-when-repeatedly-call-getdevices-true

**Comment by andrewfb** [comment]
Thanks for this - should be fixed by aca43a85ead4840b6d381449ad37ff9aca347ebc
