### ISSUE TITLE
General weirdness in Area::getUL() after GLM update?

### ISSUE THREAD

**Issue by pizthewiz** [cinder/Cinder#775]
I am seeing some strange behavior with `Display::getSystemCoordinate` that seems to be related to the GLM innards. Say I have a `DisplayRef` that points to a secondary display, if I run this:
```C++
Area bounds = display->getBounds();
ivec2 point = ivec2(0);
ivec2 result = bounds.getUL() + point;

// should be equivalent to the above
ivec2 result2 = display->getSystemCoordinate(point);
```
the first technique works and the second fails:
```lldb
(lldb) po bounds
 (x1 = 1440, y1 = 0, x2 = 3360, y2 = 1080)
(lldb) po result
 {
   (x = 1440, r = 1440, s = 1440)
   (y = 0, g = 0, t = 0)
}
(lldb) po result2
 {
   (x = 1606414872, r = 1606414872, s = 1606414872)
   (y = 32767, g = 32767, t = 32767)
}
```

Stepping through the function body:
```c++
ivec2 Display::getSystemCoordinate( const ivec2 &displayRelativeCoordinate ) const
{
	return mArea.getUL() + displayRelativeCoordinate;
}
```
something strange seems to be occurring on `getUL()`:
```lldb
(lldb) p mArea
(cinder::Area) $0 = (x1 = 1440, y1 = 0, x2 = 3360, y2 = 1080)
(lldb) p mArea.getUL()
(glm::ivec2) $1 = {
   = (x = 3503880, r = 3503880, s = 3503880)
   = (y = 1, g = 1, t = 1)
}
(lldb) p mArea.x1
(int32_t) $2 = 1440
```

**Comment by andrewfb** [comment]
Is it possible you have a stale PCH or similar? I just pasted a slightly modified version of the code above into BasicApp and was seeing normal behavior...

**Comment by pizthewiz** [comment]
Sorry about that, you appear to be correct - I deep cleaned the project and rebuilt and now things seem just fine.
