### ISSUE TITLE
DeferredShading (basic) sample problems with Mac Intel Iris Pro card

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#787]
When forcing the mbo's integrated graphics card, I see the following:

![screen shot 2015-04-02 at 10 16 35 am](https://cloud.githubusercontent.com/assets/5132127/6965665/613f220c-d921-11e4-8d2f-c7cd5677a4c7.png)

And debug view:
![screen shot 2015-04-02 at 10 16 56 am](https://cloud.githubusercontent.com/assets/5132127/6965673/6cd3bd9e-d921-11e4-96f6-e7440ad27fa5.png)

Also reported in [this thread](https://forum.libcinder.org/topic/glnext-deferred-shading-samples#23286000002299087). @gaborpapp seems to be having problems with it on his dedicated NVidia GT 750M card, though I have that exact same model and it works for me. However one thing I did notice, was that if I forced the integrated card, and then force switch it to dedicated, things still look wrong. But if I fire up the sample with just dedicated (or using dynamic switching), it renders fine.

**Comment by richardeakin** [comment]
minor update: [this](https://github.com/cinder/Cinder/blob/glNext/samples/_opengl/DeferredShading/src/DeferredShadingApp.cpp#L306) call to `mGlslProgLBuffer->uniformBlock( 0, 0 )` is causing an `GL_INVALID_VALUE` error with the Intel Iris Pro only. I didn't see a std140 uniform block in lbuffer.frag so I thought to comment it out - the error goes away but the rendering is still off..

**Comment by BanTheRewind** [comment]
Started a branch for fixes here.
https://github.com/BanTheRewind/Cinder/tree/glNext_DeferredFixes

**Comment by BanTheRewind** [comment]
This PR addresses this issue.
https://github.com/cinder/Cinder/pull/803

**Comment by richardeakin** [comment]
Unfortunately I'm still seeing rendering problems, though it looks a little different:

![screen shot 2015-04-06 at 1 16 43 pm](https://cloud.githubusercontent.com/assets/5132127/7008311/4a96b394-dc5f-11e4-9e9c-9fbb30258a15.png)

![screen shot 2015-04-06 at 1 16 54 pm](https://cloud.githubusercontent.com/assets/5132127/7008316/52be905a-dc5f-11e4-8cbc-2221917bc014.png)

Let me know if there is anything I can do to help you debug, though I haven't had time to look at the example in detail..

**Comment by BanTheRewind** [comment]
Weird. Try setting the alpha to 1.0 at the end of the L-buffer shader. The problem I was seeing looks like what Gabor posted on the forum.

**Comment by BanTheRewind** [comment]
I think setting the output to a vec3 might be a better fix, actually.  One moment...

**Comment by BanTheRewind** [comment]
How do you switch between cards on the MBP. I could probably reproduce this if I could force the integrated card. The machine where I can test the issue is not mine, so I don't want to ruin it. ;)

**Comment by richardeakin** [comment]
I use [gfcCardStatus](https://gfx.io/) to force the integrated intel card to always be used.

**Comment by BanTheRewind** [comment]
Thanks!

**Comment by gaborpapp** [comment]
It works for me on the dedicated card now, but still looking funny on the integrated one.

**Comment by BanTheRewind** [comment]
Gotcha. I'll try switching on my co-worker's laptop later today.

**Comment by BanTheRewind** [comment]
SOLVED

The first assignment of oColor in lbuffer.frag should be =, not +=. At one point, oColor was initialized as vec4( 0 ). That line was apparently removed.

I'll have a commit with the shortly. I'm moving meshes and GLSL programs into batches. Soooo much cleaner.

**Comment by BanTheRewind** [comment]
Fixed here: https://github.com/BanTheRewind/Cinder/commit/f7aa925a651862eb53aa82b373b1ce13a2075ea6

**Comment by richardeakin** [comment]
Fixed in #803.
