### ISSUE TITLE
App::getAppPath() works slightly different on mac and windows 

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#788]
The following is some workaround code (from [here](https://github.com/BanTheRewind/Cinder-LeapMotion/blob/master/samples/TracerApp/src/TracerApp.cpp#L138-L143)):

```c++
void TracerApp::screenShot()
{
#if defined( CINDER_MSW )
	fs::path path = getAppPath();
#else
	fs::path path = getAppPath().parent_path();
#endif
	writeImage( path / fs::path( "frame" + toString( getElapsedFrames() ) + ".png" ), copyWindowSurface() );
}
```

The problem appears to be that on Mac, the path returned is to the one _inside_ the app bundle, and on windows it is next to the .exe.  Should we do the `parent_path()` internally so these function the same? It would be a breaking change, so probably best to do it sooner rather than later if we are going to.

Also, if the user does want to get a path to within the bundle, we could add cocoa-specific api:

```c++
#include "cinder/app/mac/PlatformCocoa.h"

auto bundlePath = app::PlatformCocoa::get()->getBundlePath();
```

[Related question](https://forum.libcinder.org/topic/glnext-deferred-shading-samples#23286000002304001) on forum.

**Comment by BanTheRewind** [comment]
The two platforms work differently. On OSX, the app lives inside the bundle. On Windows, you "bundle" things yourself. getAppPath works correctly with respect to its platform. I think having a bundle path method on OSX is the right solve, rather than changing getAppPath.

**Comment by richardeakin** [comment]
You could also phrase that as 'the executable lives inside the app bundle'. For clarification, I was suggesting that `PlatformCocoa::getBundlePath()` returns what `getAppPath()` currently does, but we'd change `getAppPath()` on Cocoa platforms to return the directory in which the .app bundle lived. Not saying this is the best thing to do, but worth a discussion.

**Comment by andrewfb** [comment]
To my mind, the main case for using getAppPath() is exactly the one that necessitates this workaround and consequently should probably be changed to match MSW. Other items which are app-relative like resources and assets already have mechanisms that sort out the differences. And for the average Mac user, an .app is the app, while getBundlePath() provides an appropriate advanced move for the unusual case where you need it.

**Comment by andrewfb** [comment]
In light of the example above, where a straightforward usage requires an #ifdef, I've gone ahead and made this change.
