### ISSUE TITLE
Make Signal::emit() const if possible.

### ISSUE THREAD

**Issue by sansumbrella** [cinder/Cinder#789]
Emitting a signal should probably be declared const, as the signal shouldn't change its own state when emitting. We can't avoid that a connected slot might change the signal, but I think it should make the guarantee for itself regardless.

Is there some other reason that Signal::emit() isn't already declared const?

**Comment by richardeakin** [comment]
Actually, emit() is able to modify itself and was one of the original author's initial primary requirements (see second bullet point on [this post](https://testbit.eu/cpp11-signal-system-performance/)).

**Comment by richardeakin** [comment]
Also take a look at [docs here](https://github.com/cinder/Cinder/blob/glNext/include/cinder/Signals.h#L410-L411).

Basically, this is why SignalLink maintains a custom ref counted linked list. Is there a different case you think would be unsafe?
