### ISSUE TITLE
mapping VboMesh positions causes flicker 

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#793]
I am seeing severe flickering when I call `VboMesh::mapAttrib3f( geom::Attrib::POSITION )` in the following test app:

```c++
#include "cinder/app/App.h"
#include "cinder/app/RendererGl.h"
#include "cinder/gl/gl.h"
#include "cinder/gl/VboMesh.h"
#include "cinder/MayaCamUI.h"

using namespace ci;
using namespace ci::app;

using std::vector;

class VboSampleApp : public App {
 public:
	void	setup() override;
	void	update() override;
	void	draw() override;

  private:
	gl::VboMeshRef	mVboMesh;
	MayaCamUI		mMayaCam;
};

void VboSampleApp::setup()
{
	auto plane = geom::Plane().size( vec2( 15, 15 ) ).subdivisions( ivec2( 4, 4 ) );

	vector<gl::VboMesh::Layout> bufferLayout = {
		gl::VboMesh::Layout().usage( GL_DYNAMIC_DRAW ).attrib( geom::Attrib::POSITION, 3 )
	};

	mVboMesh = gl::VboMesh::create( plane, bufferLayout );
}

void VboSampleApp::update()
{
	auto mappedPosAttrib = mVboMesh->mapAttrib3f( geom::Attrib::POSITION );
	for( int i = 0; i < mVboMesh->getNumVertices(); i++ ) {
		mappedPosAttrib->y = 0;
		++mappedPosAttrib;
	}
	mappedPosAttrib.unmap();
}

void VboSampleApp::draw()
{
	gl::clear( Color( 0.15f, 0.15f, 0.15f ) );
	gl::setMatrices( mMayaCam.getCamera() );
	gl::draw( mVboMesh );
}

CINDER_APP( VboSampleApp, RendererGl )
```

The flickering looks like [this](https://dl.dropboxusercontent.com/u/3905723/cinder/test/vbomesh_mapped_flickering.mov).

I originally ran into this when updating the VboMesh sample (used to be called VBOBasic), which is in [this branch](https://github.com/richardeakin/Cinder/tree/glNext_VboMesh_sample). The buffer setup in there is a bit more complex, but I'm seeing the same symptons with the above code. I also tried creating a Batch with the VboMesh / glsl, but I see the same problem with that too.

**Comment by lithium-snepo** [comment]
Not sure if this helps, but I ran into this issue recently, and i wound up "fixing" it by passing false to the optional `orphanExisting` argument in the `VboMesh::map*` functions, though admittedly without fully understanding the implications.

**Comment by richardeakin** [comment]
Doh!  I had forgotten about the orphanExisting flag... again. :) Thanks for pointing that out. Here is an explanation from Andrew the last time I raised this issue:

> 'orphanExisting' tells the driver that it can abandon the contents that are currently in the VBO before mapping. Keep in mind you are always working 1-3 frames ahead of what the GPU is currently processing (CPU is in the future, so to speak). So when you map a VBO and intend to read from it or not replace the whole thing (orphanExisting == false), you create a bubble - the CPU has to stall until the GPU has finished making use of that VBO 1-3 frames "ago". When you orphan it, you say "I don't care what's in that buffer; I'll be replacing it entirely. So don't wait around until we're done w/ the old data."

> The ideal is to always replace the whole buffer. It's the main use case for separating attributes into multiple different VBOs. Another technique would be store your data planar, and then bufferSubData() on it, or mapBufferRange().

Going to close the issue, though this is probably worth further documentation come ci::gl guide time.

**Comment by lithium-snepo** [comment]
Whoever made the decision to not show optional parameters in xcode's auto-complete needs to have their head examined. It's cost me so much time over the years.
