### ISSUE TITLE
glnext, void draw( const PolyLine2 &polyLine )  does not draw closed

### ISSUE THREAD

**Issue by Ahbee** [cinder/Cinder#794]
If I mark the polyLine as closed, the draw function still draws it as an open polyline

**Comment by gaborpapp** [comment]
I also noticed this recently and used `draw( Shape2d )` as a workaround.

**Comment by Ahbee** [comment]
@gaborpapp , do you find that the glnext version is significantly slower than the old school version. 
After I draw about 100 polylines I see significant slow down.

**Comment by gaborpapp** [comment]
@Ahbee, I don't draw that much polylines, although the gl::draw functions are for convenience only as far as I know. If you want speed build your own Batch/VboMesh.

**Comment by Ahbee** [comment]
@gaborpapp thanks for the tip, that being said, i dont see an easy way to create a Batch/VboMesh from a polyline, guess I have to add the points manually.

**Comment by richardeakin** [comment]
@Ahbee the typical way to do this is to use the `Triangulator` class to create a mesh and upload that. See [here](https://github.com/cinder/Cinder/blob/glNext/src/cinder/gl/draw.cpp#L584) for an example.

**Comment by Ahbee** [comment]
@richardeakin thanks

**Comment by richardeakin** [comment]
Fixed with  #800
