### ISSUE TITLE
Geometry shaders doesn't work

### ISSUE THREAD

**Issue by vorg** [cinder/Cinder#8]
Has anybody tried to use any geometry shaders? From documentation is seams that you have to set GL_GEOMETRY_INPUT_TYPE_EXT, GL_GEOMETRY_OUTPUT_TYPE_EXT and GL_GEOMETRY_VERTICES_OUT_EXT before linking the program. Without this I couldn't make it work.

Here is my patch. Feel free to remove #include <OpenGL/glu.h>. It was just for gluErrorString debugging.

http://github.com/vorg/Cinder/commit/a5e1b897fe92be0d8ae76899a404e22de428ff30

**Comment by andrewfb** [comment]
Apologies - cleaning up old issues; geometry shaders work these days.
