### ISSUE TITLE
glNext: gl::Batch::AttributeMapping by location ID

### ISSUE THREAD

**Issue by BanTheRewind** [cinder/Cinder#805]
Please look here:

https://github.com/BanTheRewind/Cinder/blob/glNext_DeferredInstanced/samples/_opengl/DeferredShadingAdvanced/src/DeferredShadingAdvancedApp.cpp#L199-L216

I'm trying to use a mat4 as a per instance attribute. In vanilla OpenGL, this is done on the CPU side using four vertex attributes. I would get the location of the mat4, then increment by one for each set of four floats. But because the second in AttributeMapping must be a string, I can't set my locations using Cinder's API. It would be nice to have the option to map CUSTOMn attributes to GLints

**Comment by ryanbartley** [comment]
This functionality is in progress. It is a part of a larger update that I'm almost finished with. Should be able to pr on Tuesday.

**Comment by BanTheRewind** [comment]
Thanks much.




In trying to optimize shadows for the deferred engine, I found that a shadow caster geometry pass with a shadow map is really the best way to go. Single-pass techniques yielded only marginal performance gain and had some limitations that made them hard to look good. As long as I have to draw shadow casters twice, I may as well do it efficiently. :)


I also have the deferred shading advanced sample running in the Rift. So I'll be switching a lot of stuff to instanced.






Anywho... just wanted to share what the use case is here. Looking forward to he update.

**Comment by BanTheRewind** [comment]
Hey, just wondering how this is going. I'm wrapping up my last few
optimizations on the DeferredShadingAdvanced sample. I just have a few
performance tweaks on the bloom and AO passes before I move onto instanced
drawing. Then I can finally call this one good.  :)

**Comment by ryanbartley** [comment]
I got hindered this week due to work. I'm finishing up what appears to be a bug in amd gpus. When that's solved today, it should be ready to go.

**Comment by BanTheRewind** [comment]
Awesome, thanks much!
