### ISSUE TITLE
FrustumCullingRedux not working correctly

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#815]
You can see the near hearts popping in and out, so the culling algorithm has become slightly off. Haven't had time to investigate, but I don't believe this was the case when we first updated the sample for glNext.

**Comment by paulhoux** [comment]
I have a fix, will push it later on. Sphere wasn't correctly transformed to world space.

**Comment by paulhoux** [comment]
![2015-04-13_180707](https://cloud.githubusercontent.com/assets/304908/7147034/0b873562-e2c6-11e4-9f00-08d03e7a7dbc.png)

Preview of the new WireSphere. I've updated the sample and cleaned it up. It had become rather a mess with all the new functionality.

**Comment by paulhoux** [comment]
Create a pull request (#823) containing the fix.
