### ISSUE TITLE
glNext: Cylinder weirdness

### ISSUE THREAD

**Issue by BanTheRewind** [cinder/Cinder#817]
I moved the advanced deferred sample into a nifty pentagonal room using geom::Cylinder. I'm getting some weird banding from it and a weird stripe sometimes. In the screenshots, you'll see that the floor and ceiling reflect OK, but the walls do not. Check out the debug view where it's just the normals. You can see a weird strip occuring. I'm using the same shader to render everything to the G-buffer, so it's definitely something weird with just this one shape.

![frame2986](https://cloud.githubusercontent.com/assets/954475/7128007/3b940a02-e201-11e4-9cbd-861f82553c91.png)
![frame7091](https://cloud.githubusercontent.com/assets/954475/7128011/3b95aca4-e201-11e4-89ff-7235e5b4a299.png)
![frame7212](https://cloud.githubusercontent.com/assets/954475/7128010/3b957df6-e201-11e4-9ac3-d1c11899df05.png)
![frame8825](https://cloud.githubusercontent.com/assets/954475/7128006/3b9295be-e201-11e4-8b53-64621262eee8.png)
![frame9318](https://cloud.githubusercontent.com/assets/954475/7128008/3b94b5a6-e201-11e4-9bf1-53f6a456c78c.png)
![frame10073](https://cloud.githubusercontent.com/assets/954475/7128009/3b94f944-e201-11e4-890a-089260c5eb9c.png)

**Comment by ryanbartley** [comment]
This may have nothing to do with it but I noticed in the gBuffer.vert you're asking for texCoords and then never using them, at least in the shader most current. I don't know that that would have anything to do with what you're seeing but definitely thought I'd mention it.

**Comment by BanTheRewind** [comment]
I took out the texcoords awhile ago. This is my shader.
https://github.com/BanTheRewind/Cinder/blob/glNext/samples/_opengl/DeferredShadingAdvanced/assets/deferred/gbuffer.vert

I'm inverting the normal so it faces inside, but that shouldn't mean anything. This shape has seven sides. It should have seven normals, not a gradient.

**Comment by ryanbartley** [comment]
Maybe you could put the normals out with the flat directive. That way they won't be interpolated.

**Comment by BanTheRewind** [comment]
I just thought of that when this post showed up. If course the UVs should be interpolated. Duh! Thanks!

**Comment by ryanbartley** [comment]
No problem. It's always those little stupid things. :) It looks great!

**Comment by BanTheRewind** [comment]
Thanks! Down to the last bit right now. Feel free to close this issue (I'm away from my machine right now).

**Comment by ryanbartley** [comment]
Awesome. I'm also pretty close to having the update finished.

**Comment by BanTheRewind** [comment]
Hmmm...
![frame1111](https://cloud.githubusercontent.com/assets/954475/7130022/173c8b58-e21e-11e4-97b2-662d735c1fe8.png)

**Comment by ryanbartley** [comment]
hmmm, indeed. There's seems to be more to this problem. May be a stupid question but are you sure they're all facing in?

**Comment by BanTheRewind** [comment]
Well, technically they are all facing out and I'm flipping the normals in the vertex shader. I have front face culling on which removes all the correct triangles, so I have to assume they are facing the same direction.

**Comment by BanTheRewind** [comment]
So it looks like the normal are all one triangle off. Here are pics from debug mode and with AO turned off.  See how one triangle from one face is not interpolated to a triangle on the next face?

![frame1294](https://cloud.githubusercontent.com/assets/954475/7130187/6648c502-e220-11e4-8d30-1f6347819c5b.png)
![frame1347](https://cloud.githubusercontent.com/assets/954475/7130188/664d2bd8-e220-11e4-8340-7c906241c036.png)

**Comment by BanTheRewind** [comment]
Though it looks kind of awesome from above...

![frame1087](https://cloud.githubusercontent.com/assets/954475/7130211/cfde4bc2-e220-11e4-80a7-48e9a8cce0b0.png)

**Comment by paulhoux** [comment]
Looks awesome indeed, but not what you might have expected. I don't know exactly what is going on, I can just share what I know regarding the cylinder. First of all, front-facing or back-facing has nothing to do with the normals, only with the winding order. I am pretty sure the winding order is correct. Next, the vertices share normals, because most people want their cylinders to be smooth. The top and bottom caps don't share vertices with the sides, though, so they should remain flat. This leaves us with the weird appearance of the sides. Can you draw the normals, so they become visible? There should be a modifier for that.

**Comment by paulhoux** [comment]
Oh wait a minute, you're not normalizing the normal in gbuffer.frag. Try normalizing it before encoding it. I am not sure this will solve the issue, but you should do it anyway because a normal passed as an attribute to a fragment shader will be interpolated and with polygons this big they will probably not have unit length.

**Comment by BanTheRewind** [comment]
I am normalizing (if not in the repo, I am here), but I might have to change the winding order since I'm flipping the normals.

**Comment by paulhoux** [comment]
Winding order has nothing to do with it. With normalizing, I mean this:
```oNormal = vec4( encodeNormal( normalize( vertex.normal ) ), 0.0, 1.0 );```

(just making sure we're talking about the same thing)

**Comment by BanTheRewind** [comment]
Ah, but I'm normalizing in the vert shader. Will give this a shot.

**Comment by paulhoux** [comment]
Also, using the ```flat``` directive might make things worse in this case.

Like I said, you *must* normalize in your fragment shader, especially with polygons this big and with normals pointing in such different directions.

**Comment by paulhoux** [comment]
*crosses fingers* :)

**Comment by BanTheRewind** [comment]
Bingo! Thanks!

![frame562](https://cloud.githubusercontent.com/assets/954475/7130575/c0be3e5c-e227-11e4-8952-4176a9daa3e9.png)

**Comment by ryanbartley** [comment]
Nice!

**Comment by paulhoux** [comment]
Kewl!
