### ISSUE TITLE
Weird issue with gl::GlslProg::Format copy assignment / constructor on iOS Simulator

### ISSUE THREAD

**Issue by simongeilfus** [cinder/Cinder#826]
I'm having a hard time figuring out what's going on and what did I changed since yesterday.

Basically with the current glNext version I can't copy a gl::GlslProg::Format anymore. It works fine on an iOS device and on desktop but for some reason when I try to do that in the iOS simulator the app breaks into the gl::GlslProg::Format constructor and deep into stl calls about std::map<.... / std::__1::__tree_node,... Well it's a bit hard to figure out what is exactly the issue so I would love to know if anyone else can reproduce this.

I managed to reproduce this on another computer where it was working fine yesterday by creating an empty app and just doing this:

```c++
void BreakingBadiOSApp::setup()
{
	gl::GlslProg::Format format1;
	gl::GlslProg::Format format2 = format1;
}
```

I've tried to go through previous commits on glNext branch, but couldn't find where it happened so I might have done something wrong locally!

Would be great if someone could confirm this behavior.
Thanks a lot.
Simon.

**Comment by ryanbartley** [comment]
It sounds like you need a clean and delete files and then rebuild. Xcode was not getting rid of my files after a clean and rebuild just a few weeks ago.

**Comment by simongeilfus** [comment]
Hey,
Thanks Ryan, I did clean and rebuild everything.

I found out my problem was that before pulling the last commit from github I discarded my changes to cinder.xcodeproj losing the previous CINDER_GL_ES_3 flag defined in its build settings. 

And well, this was defined in the preprocessor list of the different projets where I was having this issue!

Sorry for the false alarm!
