### ISSUE TITLE
geom::WireCube size is 2x

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#833]
My understanding of the term size is that it equals the length of the cube's sides, yet in [this calculation](https://github.com/cinder/Cinder/blob/glNext/src/cinder/GeomIo.cpp#L2956-L2982) it is treated like a radius, so to speak. So, `geom::WireCube( vec3( 1 ) )` produces a cube 2X unit size.

**Comment by paulhoux** [comment]
I made geom::WireCube to be the same as geom::Cube, so if we're going to change this, we need to change both. I do agree that a size of 1 in each direction should result in a cube that is 1x1x1 unit, instead of 2x2x2.

**Comment by thyrrestrup** [comment]
I ran into this a while back too.. I would also say that 1x1x1 is more intuitive.

**Comment by paulhoux** [comment]
Should be fixed in afab295c7f744a630784822db736e7c6459fa0d5
