### ISSUE TITLE
getScreenResolution

### ISSUE THREAD

**Issue by bradrothenberg** [cinder/Cinder#839]
Hi,

Is there a cinder function in glNext to get the screen resolution? 

I'm trying to use:

```
	// Get a handle to the desktop window
	const HWND hDesktop = GetDesktopWindow();

	// Get the size of the screen into a rectangle
	RECT rDesktop;
	GetWindowRect(hDesktop, &rDesktop);

	// The top left corner will have coordinates (0, 0)
	// and the bottom right corner will have coordinates
	//(width, height)
	width = rDesktop.right;
	height = rDesktop.bottom;
```

thanks!!

**Comment by pizthewiz** [comment]
Maybe not a function in the global namespace, but could you use [`Display::getSize()`](https://github.com/cinder/Cinder/blob/glNext/include/cinder/Display.h#L49)?

**Comment by bradrothenberg** [comment]
This works! thanks

**Comment by bradrothenberg** [comment]
However, I want to use it in the prepareSettings function, which is now global, rather than being part of the app...Any idea how to access the screen size from a global function?

**Comment by richardeakin** [comment]
Querying the displays before the app is constructed is not guarunteed to work on all platforms, but the following works for me on Mac OS X 10.10:

```cpp
CINDER_APP( IsosurfaceTestApp, RendererGl, []( App::Settings *settings ) {
	DisplayRef display = Display::getMainDisplay();
	ivec2 displaySize = display->getSize();

	cout << "main display size: " << displaySize << endl;
} )
```
Can't test on a win machine at the moment, but it probably works there too.

What's your use case anyway?

**Comment by andrewfb** [comment]
Just adding this should work everywhere but iOS.
