### ISSUE TITLE
Asset load runtime exceptions from Xcode All Samples project

### ISSUE THREAD

**Issue by jasonsturges** [cinder/Cinder#844]
Many of the sample projects throw exceptions from the _AllSamples Xcode project due to path issues when loading assets on Mac using Cinder 0.8.6.

Standalone versions work fine, but AllSamples targets fail.

**BezierPathIteration**
Exception at startup.  

    void BezierPathIterationApp::loadSvg( const fs::path &fsPath )
    {
    	mPathIters.clear();
    	mPathCaches.clear();
    
    	// pull in all the paths of the SVG
    	auto svg = svg::Doc::create( fsPath );

**EuroMap**
Exception at startup.

    void EuroMapApp::setup()
    {
    	mMapDoc = svg::Doc::create( loadAsset( "Europe.svg" ) );

**Falling Gears**
Exception on click to add gears.

    ci::gl::TextureRef SceneController::getRandomGearTex() const
    {
    	const auto &gears = Config::instance()->getGearData();
    	int32_t index = randInt( 0, gears.size() );
    
    	return gears.at( index ).mImageTex;

**GoodNightMorning**
Exception at startup.

    void GoodNightMorningApp::setup()
    {
    	mCityscapeSvg = std::shared_ptr<svg::Doc>( new svg::Doc( loadAsset( "cityscape.svg" ) ) );

**PaletteBrowser**
Exception at startup.

    void PaletteBrowserApp::setup()
    {
    	// fonts
    	Font smallFont = Font( loadAsset( "Signika-Regular.ttf" ), 16 );

**Comment by richardeakin** [comment]
I don't think the assets system will work via AllSamples because the resulting binary ends up in a different tree, where it can't find the assets folder residing in the sample's folder. Also, the AllSamples project is meant to be a quick and easy way to build all of the samples, I don't think it was meant to be used to run them all but I could be wrong.

**Comment by jasonsturges** [comment]
@richardeakin That makes sense, the *Samples* target building all projects is a nice convenience.  

Not sure why I thought it was also intended to launch targets.  Feel free to close this ticket, thanks.

**Comment by richardeakin** [comment]
Sure, I could see how it'd be nice to have a 'sample suite' type of app, perhaps one day we could try an arrangement like that, although there are some prerequisites (like a portable ui library).
