### ISSUE TITLE
glsl isampler*D type impossible 

### ISSUE THREAD

**Issue by m1keall1son** [cinder/Cinder#849]
I just made a pull request that makes usampler\*D possible, but isampler\*D is still not possible because there's no signed integer types for channel or surface.  

I can create a texture with the appropriate type (dataFormat = GL_R16I, type = GL_SHORT), but there's no way to update it with a ChannelT\<int16_t\>. 

isampler\*D is not an often used type in glsl, but this feels like it should be possible in the event that someone wants to use a texture without converting the data.

**Comment by andrewfb** [comment]
This should be fixed by #923 - the void* update() and constructors.

**Comment by m1keall1son** [comment]
👍
