### ISSUE TITLE
Compiler error with CINDER_GL_ES_3 preprocessor (iOS)

### ISSUE THREAD

**Issue by yderidde** [cinder/Cinder#854]
When adding the pre-processor CINDER_GL_ES_3 I get a compile error:

.../cinder/gl/GlslProg.cpp:327:3: Use of undeclared identifier 'glBindFragDataLocation'

I guess it is related to this commit: https://github.com/cinder/Cinder/commit/59feedc2824507876c44bf1c2c5d267d4b33c3cf

**Comment by paulhoux** [comment]
Sorry about that. I've rolled back these changes in 0bc9093e155959d8c7788a4ae2dc68112b288833 .
