### ISSUE TITLE
Adding support for loading Ktx cubemaps (with mipmaps)

### ISSUE THREAD

**Issue by simongeilfus** [cinder/Cinder#858]
Hey all,

I started looking at the current implementation for dds and ktx files and want to work on adding support for cubemaps. As mentioned on the forum, it's a much needed feature for 3d and it would be great to be able to deal with that with the builtin TextureCubemap class.

The current TextureData class would need to be a bit re-arranged to be able to deal with faces (or slices). Currently it only has a Level vector to store the pointer offsets of each mipmap level. Should we have different classes to deal with cubemap and 3d texture data or should it be done in the same place, with several containers?

I started playing around a bit on [this branch](https://github.com/simongeilfus/Cinder/tree/CubeMapKtxMipMaps). I think the [opengl part](https://github.com/simongeilfus/Cinder/blob/CubeMapKtxMipMaps/src/cinder/gl/Texture.cpp#L1824) is fine but the [parsing](https://github.com/simongeilfus/Cinder/blob/CubeMapKtxMipMaps/src/cinder/gl/TextureFormatParsers.cpp#L111) seems to be wrong. I'm having hard time figuring out how the ktx stream/buffer work. 

I want to start by understanding a bit better the current code and making it work before trying to find the appropriate API / implementation, which is obviously not the intent here.

I would love if someone could have a look at the two links above and point me in the right direction.

Thanks a lot.

**Comment by num3ric** [comment]
I'm *just* starting to look at dds 3d texture support too, and I guess the same questions about TextureData apply. Andrew if you have an approach in mind, please let us know.

**Comment by andrewfb** [comment]
I don't have a strong opinion on this; I think generalizing TextureData to support 3D / Cubemaps / (1D?) makes sense. Presumably the cubemap is stored as a special case of 3D that has a depth of 6, and then it probably makes sense to throw a bool on there to flag that is indeed a cubemap.

**Comment by andrewfb** [comment]
This should be fixed by #1000.
