### ISSUE TITLE
Capture on iOS broken. [glNext]

### ISSUE THREAD

**Issue by sansumbrella** [cinder/Cinder#860]
It looks like `Capture->checkNewFrame()` is returning true even when there isn't new frame data. Put another way: `Capture->getSurface()` doesn't always return valid data, even immediately after `Capture->checkNewFrame()` returns true.

When we crash inside the `Texture2d::setData` method, we see the following source information, which suggests that on the second frame, the source is invalid.

![camera-capture](https://cloud.githubusercontent.com/assets/81553/7414653/1be28296-ef22-11e4-8c8c-3513693fef0c.png)

The `BAD_ACCESS` happens in the sample code within the texture `update` call.
```c++
void CaptureBasicApp::update()
{
	if( mCapture && mCapture->checkNewFrame() ) {
		if( ! mTexture ) {
			// Capture images come back as top-down, and it's more efficient to keep them that way
			mTexture = gl::Texture::create( *mCapture->getSurface(), gl::Texture::Format().loadTopDown() );
		}
		else {
			mTexture->update( *mCapture->getSurface() );
		}
	}
}
```

The following modification to the source also crashes, when the second "new" frame is received.
```c++
void CaptureBasicApp::update()
{
	if( mCapture && mCapture->checkNewFrame() ) {
			// Capture images come back as top-down, and it's more efficient to keep them that way
			mTexture = gl::Texture::create( *mCapture->getSurface(), gl::Texture::Format().loadTopDown() );
	}
}
```

**Comment by sansumbrella** [comment]
Verified bug on iOS 7.1.2 and iOS 8.1.

**Comment by araid** [comment]
I reported the same a couple days ago, for iOS 8.3 https://github.com/cinder/Cinder/issues/846
Still haven't been able to find a workaround.

**Comment by andrewfb** [comment]
Sorry about that - should be fixed now.

**Comment by sansumbrella** [comment]
Super, thanks @andrewfb and @araid.
