### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by brucelane** [cinder/Cinder#869]
hi,
Raspberry PI2 can now run on Windows 10 preview.
I can't compile the ARM version.
I can't compile debug_ANGLE or release_ANGLE configs for ARM.
I'm using visual studio 2015 community RC on W10 preview, because it's needed to do remote debugging on the RPI2
The ANGLE samples compile and run fine on the RPI2

thank you

**Comment by andrewfb** [comment]
Related: https://forum.libcinder.org/#Topic/23286000002339009

For the time being we're not supporting Win10+ARM directly. However the ARM binaries should build now with the vc2013_winrt project. We will revisit this in the next Cinder release.
