### ISSUE TITLE
Cinder applications don't cleanup after receiving kill/killall signal. [glNext]

### ISSUE THREAD

**Issue by sansumbrella** [cinder/Cinder#878]
Closing a Cinder application via a signal from terminal causes the application to exit without cleaning up. This can cause OSX to think the application crashed, raising a prompt the next time the application starts.

Steps to reproduce:
```bash
open KillTest.app/
killall KillTest
# alternatively
kill 12345
```
Result: system console shows application setup message, does not show application cleanup message.

Minimal test app to reproduce:
```c++
#include "cinder/app/App.h"
#include "cinder/app/RendererGl.h"
#include "cinder/gl/gl.h"
#include "cinder/Log.h"

using namespace ci;
using namespace ci::app;
using namespace std;

class KillTestApp : public App {
public:
  void setup() override;
  void keyDown( KeyEvent event ) override;
  void cleanup() override;
};

void KillTestApp::setup()
{
  log::manager()->setSystemLoggingLevel( log::LEVEL_INFO );
  log::manager()->enableSystemLogging();

  CI_LOG_I( "Setting up application." );
}

void KillTestApp::keyDown( KeyEvent event )
{
  if( event.getCode() == KeyEvent::KEY_ESCAPE ) {
    quit();
  }
}

void KillTestApp::cleanup()
{
  CI_LOG_I( "Cleaning up application." );
}

CINDER_APP( KillTestApp, RendererGl )
```

**Comment by sansumbrella** [comment]
Note that `cleanup` is properly called if a user presses `ESC` or `cmd+Q`. It's only when receiving messages from the system that it fails to run.

**Comment by andrewfb** [comment]
I'm open to revisiting this one day in the future, but I think it's a subtle question whether Cinder should get into installing its own interrupt handlers. In the meantime, is there anything preventing you from installing your own `SIGTERM`/`SIGKILL` handler?

**Comment by sansumbrella** [comment]
Only lack of familiarity with how those signals enter the application.

**Comment by lucasvickers** [comment]
If they don't enter the application at all then we can catch them and call quit() or whatever is appropriate.  The question is whether or not the current app is supposed to catch the kills or not.

**Comment by andrewfb** [comment]
I think it makes more sense to leave this to the discretion of the user; Cinder essentially has no opinion on your interrupt handlers, which is the simplest solution to priorities and the like.
