### ISSUE TITLE
glNext could not compile in windows

### ISSUE THREAD

**Issue by fndisme** [cinder/Cinder#882]
1>e:\cinder\cinder\include\cinder\gl\draw.h : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss (..\src\cinder\gl\ConstantConversions.cpp)
1>e:\cinder\cinder\include\cinder\gl\draw.h(126): error C2146: syntax error : missing ',' before identifier 'GLsizei' (..\src\cinder\gl\draw.cpp)
1>e:\cinder\cinder\include\cinder\gl\draw.h(126): error C2146: syntax error : missing ',' before identifier 'GLenum' (..\src\cinder\gl\draw.cpp)
1>e:\cinder\cinder\include\cinder\gl\draw.h(126): error C2143: syntax error : missing ',' before 'const' (..\src\cinder\gl\draw.cpp)
1>e:\cinder\cinder\include\cinder\gl\draw.h(126): error C2146: syntax error : missing ',' before identifier 'GLsizei' (..\src\cinder\gl\ConstantConversions.cpp)
1>e:\cinder\cinder\include\cinder\gl\draw.h(126): error C2146: syntax error : missing ',' before identifier 'GLenum' (..\src\cinder\gl\ConstantConversions.cpp)
1>e:\cinder\cinder\include\cinder\gl\draw.h(126): error C2143: syntax error : missing ',' before 'const' (..\src\cinder\gl\ConstantConversions.cpp)

**Comment by andrewfb** [comment]
Sorry about that - should be fixed by 5027f63
