### ISSUE TITLE
Unable to get Boost submodule

### ISSUE THREAD

**Issue by BanTheRewind** [cinder/Cinder#890]
I get this from both my fork and cinder:glNext

```
$ git submodule update
Cloning into 'include/boost'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:cinder/Cinder-Boost.git' into submodule path 'include/b
oost' failed
```

**Comment by SethGibson** [comment]
I get this all the time to, the workaround i've been using is to change to the https link do a git submodule sync, but would be cool if there were a cleaner solution.

**Comment by BanTheRewind** [comment]
That's not working for me, either. Getting same error with the workaround. For now, I just cloned the repo and copied in manually. Would rather not mess with Cinder's modules file when I'm PRing.

**Comment by richardeakin** [comment]
Hm, worked for me - what about trying:

```
git submodule update --init
```
?

**Comment by richardeakin** [comment]
For completeness, you'll have to [upload you're ssh key](https://help.github.com/articles/generating-ssh-keys/) to be able to download anything off of git with the ssh protocol

**Comment by BanTheRewind** [comment]
Hmmm... Go ahead and close this. It works on my Mac, but not on Windows. It's definitely related to the switch, but probably something to solve from Git.

**Comment by andrewfb** [comment]
I changed the way the url is stored in the .gitmodules - does that address it?

**Comment by BanTheRewind** [comment]
No. A little more research leads to a bug with Git for Windows which needs an ugly workaround. Sorry about that.

**Comment by pizthewiz** [comment]
Actually, I've hit the same thing on OS X, so perhaps there is something larger at play:

```sh
~/sandbox/Cinder/Cinder 🍔  git pull
remote: Counting objects: 31, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 31 (delta 11), reused 0 (delta 0), pack-reused 1
Unpacking objects: 100% (31/31), done.
From github.com:cinder/Cinder
   0d655c0..e81a667  glNext     -> upstream/glNext
Updating 75d6f07..e81a667
…
~/sandbox/Cinder/Cinder 🍔  git submodule init
Submodule 'include/boost' (git://github.com:cinder/Cinder-Boost.git) registered for path 'include/boost'
~/sandbox/Cinder/Cinder 🍔  git submodule update
Cloning into 'include/boost'...
fatal: Unable to look up github.com:cinder (port 9418) (nodename nor servname provided, or not known)
Clone of 'git://github.com:cinder/Cinder-Boost.git' into submodule path 'include/boost' failed

```

**Comment by pizthewiz** [comment]
I think there is a syntax error in the boost module URL in `.gitmodules`:
```
[submodule "tools/TinderBox-Mac"]
        path = tools/TinderBox-Mac
        url = git://github.com/cinder/TinderBox-Mac.git
[submodule "tools/TinderBox-Win"]
        path = tools/TinderBox-Win
        url = git://github.com/cinder/TinderBox-Win.git
[submodule "include/boost"]
        path = include/boost
        url = git://github.com:cinder/Cinder-Boost.git
        branch = boost_1_58
```

Should that be:
```
        url = git://github.com/cinder/Cinder-Boost.git
```

**Comment by andrewfb** [comment]
@pizthewiz that looks likely - does 50b1df1f5c6074202ba56ac4683b8e3f85047a9d fix it?

**Comment by pizthewiz** [comment]
Yep, I had to manually edit the path in `.git/config` too since I'd already init the submodule:
```
[submodule "boost"]
        url = git://github.com/cinder/Cinder-Boost.git
```
