### ISSUE TITLE
User-defined array uniforms cannot be found

### ISSUE THREAD

**Issue by num3ric** [cinder/Cinder#902]
Updating a block sample to glNext latest, I faced some uniform problems. My `mat4` array uniform would not be recognized, and the data would never reach the gpu. AFAIK, the problem is that `glGetActiveUniform` appends '[0]' to the array uniform names, which are stored as is. Later when `findUniform` is called, no match is found.

Previously, `findUniform` would call `glGetUniformLocation` directly, which would still work because locations "can be retrieved by using **the name of the array**, or by using the name appended by "[0]". http://docs.gl/gl3/glGetUniformLocation

I did temporarily fix this problem by storing the name without '[0]':

```
inline bool ends_with( std::string const & value, std::string const & ending )
{
	if( ending.size() > value.size() ) return false;
	return std::equal( ending.rbegin(), ending.rend(), value.rbegin() );
}

Uniform uniform;
uniform.mName			= name;
if( ends_with( name, "[0]" ) ) {
	uniform.mName = uniform.mName.substr( 0, uniform.mName.length() - 3 );
}
```

I'm not sure yet what the optimal solution would be.

Note that the new mUniforms is modified in several places:
https://github.com/cinder/Cinder/blob/glNext/src/cinder/gl/GlslProg.cpp#L735
https://github.com/cinder/Cinder/blob/glNext/src/cinder/gl/GlslProg.cpp#L275
https://github.com/cinder/Cinder/blob/glNext/src/cinder/gl/GlslProg.cpp#L343
https://github.com/cinder/Cinder/blob/glNext/src/cinder/gl/GlslProg.cpp#L364

**Comment by ryanbartley** [comment]
We ran into this a couple of days ago and haven't decided what the solution should be. I would for right now just append the '[0]' to your uniform name. I think in the future we should accept both ways.

**Comment by ryanbartley** [comment]
The resin being that you'll be able to get uniform locations of specific array items and update only those rather than the whole array.

**Comment by num3ric** [comment]
Ok, good to know this is on your radar.

**Comment by araid** [comment]
I was just going to report this. I'm trying to pass a float array to the vertex shader.
Adding "[0]" to the end of the name got rid of the warning, but then the shader can't access the array values.

**Comment by ryanbartley** [comment]
What do you mean the shader can't access the array values? Like you're getting junk data in the shader?

**Comment by araid** [comment]
Ok, I tested this a bit more and I think I identified the actual bug:
- Adding [0] to the name lets you pass the array to the shader, that's ok.
- The array, however, is cached the first time you pass it. Following attempts to update the uniform have no effect.

You can test it with this code https://gist.github.com/araid/242a825b4dc07d3559f6. The color of the circle should change every frame.

**Comment by num3ric** [comment]
I am breakpoint-stepping through the code. Could the problem be related to this line? https://github.com/cinder/Cinder/blob/glNext/src/cinder/gl/GlslProg.cpp#L1218

Is it normal that `checkUniformValue()` is 1 instead of `count`?

**Comment by ryanbartley** [comment]
hmm. I'm seeing the same thing on my side. The 1 isn't being used and may need to be removed. It's using it's own dataSize from here...
https://github.com/cinder/Cinder/blob/glNext/src/cinder/gl/GlslProg.cpp#L731
...and that's being used here....
https://github.com/cinder/Cinder/blob/glNext/src/cinder/gl/GlslProg.cpp#L1145
I don't understand why it's comparing as though it's the same. Still looking into it.

**Comment by ryanbartley** [comment]
Hmmmm. So I figured out something. Basically, if you change the stack array to a heap array, it'll work. 
Change this line https://gist.github.com/araid/242a825b4dc07d3559f6#file-gistfile1-cpp-L52 to...
float* rgb = new float[3];
Don't totally understand why there's a difference between the byte block compare but still looking into it.

**Comment by ryanbartley** [comment]
@andrewfb found it. I'm taking the address of the local variable val and memcpy, memcmp it.

**Comment by andrewfb** [comment]
Thanks for the case @araid - should be addressed by 1435bc0d84399558d456f4c5cbcb6733c90842e3

**Comment by araid** [comment]
Awesome. Thank you guys for the quick response.

**Comment by andrewfb** [comment]
I have a WIP on this on the glNext_glslProgValueCacheIndices branch if anybody has any time to test it. I have not done so thoroughly yet but my very initial testing looks positive.

**Comment by ryanbartley** [comment]
That looks great. Super clean implementation and more functionality that makes GlslProg super sweet! Excited to use it.

**Comment by andrewfb** [comment]
Latest glNext should address using arrays directly( glsl->uniform( "example[2]", myValue ) ). If you have a use case I'd be grateful if you can test this.

**Comment by paulhoux** [comment]
Is this what it should look like?

![2015-05-16_194928](https://cloud.githubusercontent.com/assets/304908/7668405/d820aaca-fc04-11e4-8067-8ac44a2f422d.png)

**Comment by ryanbartley** [comment]
Something like that... It looks like there isn't a call to clear the color or depth buffer.

**Comment by paulhoux** [comment]
I figured out what's wrong. It's not so much the C++ code (although the AttribFn that sets the TEX_COORD0 should use a vec2 instead of a float). It's the fact that the color of the spheres is set in the fragment shader, using interpolated texcoords, causing it to either round up or down (per-pixel).

If you set the color in the vertex shader instead, it seems to be correct:
![2015-05-16_200101](https://cloud.githubusercontent.com/assets/304908/7668431/8f100cde-fc06-11e4-974e-56845773f429.png)

**Comment by paulhoux** [comment]
See ff404e1b94ad51ee92f9b9ef52eaffb53a1112b5
