### ISSUE TITLE
Make Texture::create( unsigned char* ... respect the data format?

### ISSUE THREAD

**Issue by paulhoux** [cinder/Cinder#906]
Would it make sense to change the GL_UNSIGNED_BYTE to a format appropriate for the passed in dataFormat? Like GL_FLOAT and such? 

See: https://forum.libcinder.org/#Topic/23286000002344001

**Comment by paulhoux** [comment]
Should we call ```getInternalFormatInfo()``` in each texture's ```create``` function?

**Comment by gaborpapp** [comment]
Besides `create`, `update` is also important, otherwise I'm not sure how we can update for example a texture with `GL_SHORT` data type.

**Comment by andrewfb** [comment]
This should be addressed by the changes merged in #923
