### ISSUE TITLE
Quicktime broken on Windows

### ISSUE THREAD

**Issue by jhurlbut** [cinder/Cinder#911]
I get an error with recent glNext commits about convertCVPixelBufferToSurface missing from QuicktimeUtils.cpp. It was removed 3/21/15 in commit da353bbe3c765f8d391c0711ab7a1a2be3c39703. I re-added the function and when I try to load a movie I get an OSStatus error 194513

**Comment by andrewfb** [comment]
Sorry about that - should be fixed 35685becfa2381f2a3d9efa7a6746aa6373505f5  Tested on a Win 8.1 machine.

If QuickTimeBasic sample doesn't work, you might confirm that QT can play the given movie file. You might try 0.8.6/master to confirm that.

**Comment by jhurlbut** [comment]
That works. thanks
