### ISSUE TITLE
Allow ObjLoader to not optimize vertices

### ISSUE THREAD

**Issue by araid** [cinder/Cinder#918]
In 0.86, ObjLoader had the option to not optimize vertices, but it seems it's gone in glNext.

My particular case: I have several OBJ files that represent variations of the same base model, which I'd like to load it exactly as is. Each file has 5042 vertices but:

- glNext outputs a different number of vertices for every OBJ file, I guess due to optimization.
- 0.86 shows 30240 vertices consistently. Not sure where the number is coming from but it's the same as the [threejs editor](http://threejs.org/editor/) shows. 
- other 3D software like MeshLab show 5042 vertices.

**Comment by paulhoux** [comment]
The ```ObjLoader``` code is foreign to me, especially after the added support for groups and materials. I kindly request someone else to look at this. 

I did notice that the code is trying to filter out similar tuples of (position, texcoord, normal), which should IMHO not be part of the code at all and may be the reason why the darn class is so *&^$# slow to begin with. It would be better to provide a separate optimization step (like in ```TriMesh```) or have the option to disable ```forceUnique```.

**Comment by araid** [comment]
I already tweaked the class to be able to always force unique in a pretty simple way. I'll try to PR later today or tomorrow. 
I agree that separating loading and optimization would be interesting, though. Like you say the class is quite slow, especially on iOS.

**Comment by araid** [comment]
Hey Paul, you can check the PR here https://github.com/cinder/Cinder/pull/955
