### ISSUE TITLE
Switch Xcode language dialect to C++14 for tinderbox templates and possibly samples

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#919]
It seems a good time to do this, and it is backwards compatible with C++11 dialect. The update to the project files is trivial (CLANG_CXX_LANGUAGE_STANDARD = "c++0x" becomes CLANG_CXX_LANGUAGE_STANDARD = "c++14"), should be doable via script. Also VS 2015 will support these features, which is right around the corner.

**Comment by pizthewiz** [comment]
Sounds good to me, though it looks like C++14 support wasn't complete until Clang 3.4 which was first shipped in Xcode 5.1, so we might need to raise the minimum Xcode version if C++14 features are used heavily? It appears that C++14 support began much earlier in Xcode so at the very least the `c++14` value should be recognized all the way back somewhere earlier than Xcode 4.3.3.

Here are two good support and version references:
- [Clang - C++14 implementation status](http://clang.llvm.org/cxx_status.html#cxx14)
- Gist of [Xcode clang versions](https://gist.github.com/yamaya/2924292)

**Comment by richardeakin** [comment]
I wasn't thinking to use any features that would require a newer version of Xcode to build, but rather just bump up the version for templates / samples.  I believe we're setting the min Xcode version to 5+ anyhow, the 4 series was absolute crud for C++ development.

**Comment by pizthewiz** [comment]
Ahh, that's even better news :wink:

**Comment by pizthewiz** [comment]
Still thinking about this one in the 0.9.0 timeframe? I just noticed Xcode seems to default to `GNU++11` now.

**Comment by richardeakin** [comment]
Can't see any reason not to, at minimum we should do it for the tinderbox templates. I'll update the title accordingly
