### ISSUE TITLE
Please add an explicit license file to the repo

### ISSUE THREAD

**Issue by mbrukman** [cinder/Cinder#932]
The [README.md](https://github.com/cinder/Cinder/blob/master/README.md) file says:

> Cinder is released under the Modified BSD License.

but there isn't a `LICENSE` file in the repo to clarify the exact terms of the license. Could you please select the intended license from [opensource.org](http://opensource.org/licenses/alphabetical)'s list of BSD licenses and add it? Thanks!

**Comment by paulhoux** [comment]
There is a license in the docs folder.

**Comment by mbrukman** [comment]
@paulhoux, thanks for the clarification! The full text from [README.md](https://github.com/cinder/Cinder/blob/master/README.md) is:

> Cinder is released under the Modified BSD License. Please read the [welcome document](http://libcinder.org/docs/dev/) for more information.

but the welcome document links to a website which does not discuss the license, hence my confusion.

Would it make sense to add a link to [`docs/COPYING`](https://github.com/cinder/Cinder/blob/master/docs/COPYING)? Happy to put together a patch if this would be accepted.

**Comment by richardeakin** [comment]
Done, hope that is easier to find now.

**Comment by mbrukman** [comment]
Thanks, @richardeakin!

**Comment by pizthewiz** [comment]
It might be worth considering a proper `./LICENSE` file - GitHub has [API support for licenses and repo license fetching](https://developer.github.com/changes/2015-03-09-licenses-api/) which does requires a `./LICENSE` file to work with the API.
