### ISSUE TITLE
Building glNext in OSX 10.9

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#938]
I can only build the latest glNext with the 10.10 SDK. Otherwise I get this error:

    cinder/include/cinder/qtime/QuickTimeImplAvf.h:181:10: Unknown type name 'NSDictionary'; did you mean '__CFDictionary'?

I tried to reply and start a new topic on the forum, but Zoho does not seem be very cooperative today unfortunately.

**Comment by andrewfb** [comment]
Sorry about that - should be fixed now.

**Comment by gaborpapp** [comment]
Thank you!
