### ISSUE TITLE
Cinder doesn't compile. Missing boost path

### ISSUE THREAD

**Issue by wdlindmeier** [cinder/Cinder#939]
I just pulled glNext today and tried to rebuild, but I got a compiler issue (both in Xcode and running fullbuild.sh) because it couldn't find boost files. 

The boost path wasn't in the project's header search paths, and adding ../boost fixed the issue.

Mac OS 10.10

**Comment by andrewfb** [comment]
The Boost location has been moved; is it fixed when you `git submodule init` and then `git submodule update`?

**Comment by ryanbartley** [comment]
If you just pulled glNext today, you probably didn't git submodule init and update. The boost directory was moved to the include folder. It'll screw with your current projects as well. You'll need to remove the {CINDER_PATH}/boost, and replace it with {CINDER_PATH}/include.

**Comment by wdlindmeier** [comment]
That'd be it. Thanks @andrewfb and @ryanbartley!
