### ISSUE TITLE
Make scoped objects movable

### ISSUE THREAD

**Issue by notlion** [cinder/Cinder#949]
After spending way too long tracking down a bug that amounted to 2 characters (`ScopedTextureBind(tex);` vs `ScopedTextureBind t(tex);`) I decided to use the `auto a = A()` form for constructing scoped objects. Using auto makes it impossible to have that type of bug.

```cpp
auto t = ScopedTextureBind(tex);
```

Thing is, ScopedTextureBind is not move-constructible and neither are the other ScopedXXX objects.

Would you guys would be open to adding default move constructors to these? It would require also adding one to Noncopyable.

I'd be willing to make a PR for this if people are open to it.

**Comment by andrewfb** [comment]
Sorry for the delay on this. I don't see a disadvantage to this other than some maintenance. I think we'd be up for a PR for it.

**Comment by notlion** [comment]
Awesome. I just made the changes in PR #965.

**Comment by notlion** [comment]
Closed the PR because of lack of default constructors in VC2013. Implementation would have been too ugly. I'll be careful to add variable names for now ;)
