### ISSUE TITLE
Quaternion::getAxis division by zero.

### ISSUE THREAD

**Issue by tek-nishi** [cinder/Cinder#954]
Hi.

if Quaternion angle == 0 or 2PI
w == 1 or -1.

Then, Quaternion::getAxis and Quaternion::getAxisAngle division by zero.

Thank you.

**Comment by richardeakin** [comment]
I believe you're looking at the Quaternion class in 0.8.6 (and current master branch)? In glNext / 0.9.0 we've switched to using GLM's quat class, which I believe is safe in this matter.  I suppose we can leave this issue open until that gets merged into master branch, which should be soon™.

**Comment by tek-nishi** [comment]
Thank you for comment.
I use Cinder 0.8.6. and wait marge.

**Comment by andrewfb** [comment]
Thanks for this report; I just confirmed that glm does not create a division by 0 in this circumstance, so this is fixed in master.
