### ISSUE TITLE
Frustum culling pch file mismatch

### ISSUE THREAD

**Issue by lab101** [cinder/Cinder#961]
Hey,

Small issue in the xcode project file of the FrustumCulling project.
The project file is looking for FrustumCulling_Prefix.pch but the actual file is FrustumCulling**Redux**_Prefix.pch.

Some quick renaming to fix it.

https://github.com/cinder/Cinder/blob/glNext/samples/FrustumCulling/xcode/FrustumCullingRedux.xcodeproj/project.pbxproj#L48

**Comment by andrewfb** [comment]
Thanks for this - should be fixed by 663e9d2
