### ISSUE TITLE
NormalMapping sample Mesh view

### ISSUE THREAD

**Issue by gaborpapp** [cinder/Cinder#970]
In the mesh view mode the wireframe output is not rendered.

**Comment by thomjordan** [comment]
UNSUBSCRIBE

**Comment by lithium-snepo** [comment]
[Here's the problem](https://github.com/cinder/Cinder/blob/glNext/samples/_opengl/NormalMapping/assets/wireframe_geom.glsl#L26)
Should be `gl_Position = gl_in[0].gl_Position;`

**Comment by gaborpapp** [comment]
This fixes it indeed. Thanks for hunting it down.
