### ISSUE TITLE
gl::draw(VboMeshRef) crashes after another VboMesh is created

### ISSUE THREAD

**Issue by araid** [cinder/Cinder#977]
Here's a weird one:

1. Create a VboMeshRef as a class member
2. Draw it for a while with ``gl::draw(VboMeshRef)``
3. Create another VboMesh anywhere.
4. OpenGL crashes when trying to draw the initial VboMesh again.

Here's the test app: https://gist.github.com/araid/2fdb8b902230ab62b5c4

To clarify, it crashes with an ``EXC_BAD_ACCESS`` on iOS, on Mac the ``gl::draw`` call just stops working.

On another note, the reason I draw the VboMesh directly is because I want to use the first / last vertex parameter. Is there any way that Batch could provide that functionality as well?

**Comment by ryanbartley** [comment]
Trying to ingest this. One thing quickly, the "draw" function of Batch allows for the first / last vertex functionality you're looking for.

**Comment by araid** [comment]
Oh, thanks, I didn't see that. That actually solves the problem for me so no rush with the bug :)

**Comment by ryanbartley** [comment]
I get an invalid operation error in opengl profiler when the other vbomesh is created.
![screen shot 2015-06-10 at 3 28 31 pm](https://cloud.githubusercontent.com/assets/2651863/8092010/1a90a0fc-0f85-11e5-8ae6-77749b77732b.png)
From the spec...
GL_INVALID_OPERATION is generated if a non-zero buffer object name is bound to an enabled array or the element array and the buffer object's data store is currently mapped.
Still looking though...

**Comment by andrewfb** [comment]
Thanks for the repro - should be fixed in 0808db2
