### ISSUE TITLE
MayaCamUI is missing in master branch

### ISSUE THREAD

**Issue by vijtad** [cinder/Cinder#986]
I don't find MayaCamUI.h  in include folder.
Is class MayaCamUI replaced with any different name ?

**Comment by richardeakin** [comment]
Yes, it has been replaced with a more feature rich [CameraUi](https://github.com/cinder/Cinder/blob/master/include/cinder/CameraUi.h). It is used throughout many of the samples, that'd be the first place to look for how to use.
