### ISSUE TITLE
Move GL preprocessor checks to GL_HAS_XXX system

### ISSUE THREAD

**Issue by richardeakin** [cinder/Cinder#994]
Currently we're using things like `#if ! defined( CINDER_GL_ES_ 2 )` for selectively adding gl features on different platforms, but the line for what is available on OpenGL ES and OpenGL desktop is becoming more and more gray, especially with the advent of android support.  Right now the discussed solution is to add feature macros to `cinder/gl/platform.h`, like `CINDER_GL_HAS_UNIFORM_BUFFERS`, and then the individual classes like `GlslProg` or `Context` will use those to determine what API to enable.

**Comment by andrewfb** [comment]
Addressed in #1006
