### ISSUE TITLE
iOS: bug with readPixels8u + msaa FBO

### ISSUE THREAD

**Issue by araid** [cinder/Cinder#999]
in iOS, the following combination causes some some weirdness with the viewport:

- have an app with MSAA
- create an FBO with MSAA
- in the ``draw()`` function of the app, call ``readPixels8u()`` on the FBO

Also, nothing is drawn if the RendererGl has been initialized without MSAA. Everything is OK if you call ``readPixels8u`` on ``update()`` instead, or if you are on Mac.

Test app: https://gist.github.com/araid/451403481d5c65c43858

**Comment by andrewfb** [comment]
@araid does the above fix this for you?

**Comment by araid** [comment]
I'm not on iOS right now, I'll try tonight and close if it's fixed. Thanks!

2015-06-30 12:36 GMT-04:00 Andrew Bell <notifications@github.com>:

**Comment by araid** [comment]
I'm testing on my iPad and it doesn't seem to work. As soon as I use ``readPixels8u()`` on ``draw()`` the screen becomes black.

**Comment by notlion** [comment]
FWIW I just tested on an iPad Air and get the same result as @araid.

**Comment by andrewfb** [comment]
OK - does 4ad0936 fix this on your devices?

**Comment by notlion** [comment]
Looks like the test works on my iPad now. Both spinning squares are visible. Thanks!

**Comment by andrewfb** [comment]
OK - going to mark this closed.
